### ISSUE TITLE
No exception when response is error

### ISSUE THREAD

**Issue by dvoikik** [proyecto26/RestClient#10]
Hi guys.
The problem is that regardless of what status code comes in response, an exception is not thrown.

    RestClient
        .Post(helper, body)
        .Catch(e => error(e))
        .Done(r => callback());

Perhaps I'm doing something wrong, but if the resource is not found, or the request is not authorized, or it was a bad request, there should not be an exception thrown? callback() is always called no matter what was the status code of the response. I even tried an invalid (or empty) host name and there is still no exception.
Thank you.

**Comment by jdnichollsc** [comment]
I think this issue is related with the following https://github.com/proyecto26/RestClient/issues/4#issuecomment-351763078
Can you confirm if that validation is enough? And I can to create a new release with that fix

Best regards, Nicholls

**Comment by davidorbelian** [comment]
@jdnichollsc I think you can close this issue
