### ISSUE TITLE
Can't change header.

### ISSUE THREAD

**Issue by jcanales89** [proyecto26/RestClient#100]
When using the method to add a header (I only use one) it seems that it is not working and I get an error such as "Missing Token".

my code looks like that for the DefaultHeader:

RestClient.DefaultRequestHeaders["Key1"] = "Value1";

Am I doing missing a step or missusing that line of code ?

**Comment by jdnichollsc** [comment]
What server code are you using? Can you try using the Authorization header instead of Key1?

**Comment by jcanales89** [comment]
I'll have more information on Monday, but the issue is that I need to put a header with a Key different from Authorization.

**Comment by jcanales89** [comment]
Hello again,

The server code is Javascript, 

unfortunatly I don't configure the server side so "Authorization" is not a valid key for the Header in my case.

I need to put another key in the header.

Is there a way to do that ?

**Comment by jdnichollsc** [comment]
You can put any other header 👍
