### ISSUE TITLE
Set-Cookie not persisting session

### ISSUE THREAD

**Issue by meroon** [proyecto26/RestClient#101]
I'm using RestClient to hit our backend service for authentication and then subsequent API calls after. The authentication call returns a session cookie using `Set-Cookie`, however the subsequent calls fail because the session is not being set in request cookie is not being set. Here is an example of the call sequence.

**Auth Request**

```
POST {auth-request-path} HTTP/1.1
Host: {auth-host}
User-Agent: UnityPlayer/2019.1.14f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)
Accept: */*
Accept-Encoding: identity
Content-Type: application/json
X-Unity-Version: 2019.1.14f1
Content-Length: 104

{"sessionTicket":"4CD5FD7324D652B0---966F-8D7569F9B2A349A-BtpCbzR0IEUoTw5iZORnf1h6lUmraUj+yu4fDayWTmA="
```

**Auth Response**

```
HTTP/1.1 200 OK
Date: Tue, 22 Oct 2019 03:26:22 GMT
Set-Cookie: bp-session=dnNGUGJ4UWlwN0E2TTFsRzU2MGduNmFIc3NFZUs4K1QvejZsbUV6Y1llejdneitmbUZEWmxJZmtVRGhoVE9BMTow;Version=1
Content-Type: application/json
Content-Length: 137
Via: 1.1 google
Alt-Svc: clear
Connection: keep-alive

{"playerId":"4CD5FD7324D652B0","sessionToken":"dnNGUGJ4UWlwN0E2TTFsRzU2MGduNmFIc3NFZUs4K1QvejZsbUV6Y1llejdneitmbUZEWmxJZmtVRGhoVE9BMTow"}
```

**API Request**
```
GET {api-request-path} HTTP/1.1
Host: {api-request-host}
User-Agent: UnityPlayer/2019.1.14f1 (UnityWebRequest/1.0, libcurl/7.52.0-DEV)
Accept: */*
Accept-Encoding: identity
Content-Type: application/json
X-Unity-Version: 2019.1.14f1
```

**API Response**
```
HTTP/1.1 401 Unauthorized
Date: Tue, 22 Oct 2019 03:26:24 GMT
bp-session: 
Content-Type: application/json
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Length: 2
Via: 1.1 google
Alt-Svc: clear
Connection: keep-alive

{}
```

I can't find much help regarding how the UnityWebRequest API handles cookies other than the static ClearCookieCache() method. That lead me to believe UnityWebRequest managed cookies seamlessly under the hood. However it doesn't appear to be working as expected, and I was hoping to see if this was a known issue with UnityWebRequest, or if I'm using RestClient incorrectly.

Here is a code snippet from my request method that wraps the RestClient request:

```
public void Request<TResponse>(CustomHttpRequest request, Action<TResponse> onSuccess, Action<CustomHttpError> onError)
        {           
            var restClientRequest = ConvertRequest(request);
            RestClient.Request(restClientRequest)
                .Then(response =>
                {
                    var body = default(TResponse);
                    if (response.Data != null && restClientRequest.ParseResponseBody)
                        body = DeserializeResponseBody<TResponse>(response.Data);
                    onSuccess(body);
                })
                .Catch(error => onError(new CustomHttpError(0, error.Message)));
        }

private RequestHelper ConvertRequest(CustomHttpRequest customlHttpRequest)
        {
            var request = new RequestHelper();
            request.Uri = BuildFullUriString(customlHttpRequest.Uri);
            request.Method = customlHttpRequest.Method;
            request.Retries = customlHttpRequest.Retries;
            request.Timeout = customlHttpRequest.Timeout;
            request.Headers = customlHttpRequest.Headers;
            request.Params = customlHttpRequest.Params;
            request.Body = customlHttpRequest.Body;
            request.EnableDebug = customlHttpRequest.EnableDebug;

            return request;
        }
```

I'm overriding the default deserialization because we are using NewtonSoft.JSON in our project, but other than that I'm not doing anything crazy. 

Appreciate any help you all can provide.

**Comment by jdnichollsc** [comment]
I recommend you stateless APIs using JWT tokens instead, this is important to be able to configure horizontal scaling, cookie sessions are not recommended unless you use external services like Redis. So try using tokens if you want to authenticate your users scaling your services using multiple server instances and without having problems by automatic load balancing 👍

**Comment by meroon** [comment]
I hear you about the using JWT tokens. We are moving over to that method of identity relatively soon. But to my initial question around cookie persistence, do you have any idea why Set-Cookie does not seem to be respected?

**Comment by KingZee** [comment]
> I hear you about the using JWT tokens. We are moving over to that method of identity relatively soon. But to my initial question around cookie persistence, do you have any idea why Set-Cookie does not seem to be respected?

We are not in a browser environment, so Set-Cookie is treated just like any other header.
Functionally speaking, JWTs would function the same anyways, they hold the state and need to be verified on the backend, as opposed to a session cookie that stores state in the backend.
From the client's perspective, since we're not in a browser, and there is no such thing as a http-only flag preventing you from modifying the cookie however you like, all you have to do is simply store the Set-Cookie header when you receive it from the server, and resend it in the header of any request that needs authentication.
