### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by galloperx** [proyecto26/RestClient#102]
Hello, the asset may be quite good, but there is an issue with the class names.
Try this: install Playfab SDK for Unity and then this asset.

**Comment by jdnichollsc** [comment]
What's that SDK? Do you have any official link?

**Comment by jdnichollsc** [comment]
We don't support third party SDKs, but any pull request is welcome! 👍

**Comment by galloperx** [comment]
I see, I mentioned it just because Playfab is quite big and common. Please see here:
https://playfab.com/

**Comment by jdnichollsc** [comment]
Did you try renaming namespaces of one of this libraries? :)

**Comment by galloperx** [comment]
Not really, after getting multiple errors yesterday, I just restored my backup (which I usually do before installing an asset into an ongoing project) and continued writing my own REST client, sure it's not as fancy as yours, but does the job for now..
I just wanted to inform you that such problem exists.

**Comment by jdnichollsc** [comment]
Do you know how to rename a namespace from your code?

**Comment by galloperx** [comment]
Well it's not about "just changing namespace" it's more about how Unity chokes on it under different conditions. When it's MY code I just control everything and prevent such things from happening in the first place... just saying.

**Comment by jdnichollsc** [comment]
Any pull request is welcome 🙂
