### ISSUE TITLE
How do you post image and JSON at the same time 

### ISSUE THREAD

**Issue by applegold** [proyecto26/RestClient#104]
newFilew = JSON information about the file 

bytes = the image 

BUT it does not work :(

RestClient.Request(new RequestHelper
        {
            Uri = url,
            Method = "POST",
            Timeout = 20,
            EnableDebug = true,
            UploadHandler = new UploadHandlerRaw(bytes),
            Body = newFilew

}

**Comment by jdnichollsc** [comment]
ohh no, you can't use both properties at the same time, You can attach the image from the `Body` object, you can send a Base64 image data from your JSON object, try converting your image to a base64 data before to generate the request :)

**Comment by jdnichollsc** [comment]
Check this example https://answers.unity.com/questions/712673/how-to-encode-an-image-to-a-base64-string.html
