### ISSUE TITLE
Retrieving RequestException data from Catch

### ISSUE THREAD

**Issue by leonps531** [proyecto26/RestClient#105]
Hi, I am really un-sure as to how I can get the RequestException in my catch statement. 

            RequestHelper helper = new RequestHelper
            {
                Uri = "",
                Method = "POST",
                Body = body,
                EnableDebug = true,
            };

            RestClient.Request<GenericResponse<SignIn>>(helper).Then(res =>
            {
                Debug.Log(res.data.token);
            }).Catch((error) =>
            {
            });

I am really wanting to be able to read my error messages.

**Comment by jdnichollsc** [comment]
Try casting the error as RequestException :)

**Comment by leonps531** [comment]
Thanks a lot! :))))
