### ISSUE TITLE
How to use IMultipartFormSection

### ISSUE THREAD

**Issue by applegold** [proyecto26/RestClient#106]
How to use 

List<IMultipartFormSection>

 FormSections = new List<IMultipartFormSection>() {}, //Content-Type: multipart/form-data

 I'm doing 

 List<IMultipartFormSection> sendStuff = new List<IMultipartFormSection>();
        sendStuff.Add("json",json);
        sendStuff.Add("file_1", bytes);
        
do you have example?

**Comment by applegold** [comment]
How would you do this with your plugin 

`  public IEnumerator UploadPhotoNowStandAlone(Texture2D tex, string json, string fileName) {
        yield return new WaitForEndOfFrame();
        var url = server + "/result/create";
        
        byte[] bytes = tex.EncodeToPNG();
        var formData = System.Text.Encoding.UTF8.GetBytes(json);
        
        Debug.LogError(formData); 
        
        WWWForm form = new WWWForm();
        form.headers.Add("Authorization", "Bearer " + apiKey);
        
        form.AddBinaryData("json", formData);
        form.AddBinaryData("file_1 ", bytes, fileName, "image/png");
        
        WWW w = new WWW(url, form);
        yield return w; 

        if (w.error != null) {
            Debug.Log(w.error);
        } else {
            Debug.Log("Finished Uploading");
        }
    }`

**Comment by jdnichollsc** [comment]
You can send a **WWWForm** via `FormData` property of `RequestHelper` class, check the README of the project 👍
