### ISSUE TITLE
Api token

### ISSUE THREAD

**Issue by brianrodrigues** [proyecto26/RestClient#108]
Opa tudo bem gostaria de saber se podem me ajudar como eu faria para implementar isso em c# com esse pacote 
<?php
  $url = "https://api.monetizze.com.br/2.1/token";
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_HTTPHEADER, ["X_CONSUMER_KEY: aabd7fe84e66f643e40c361f8340788d"];
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
  curl_setopt($ch, CURLOPT_URL, $url); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);    
  
  $res = curl_exec($ch);

  $dados = json_decode($res);

?>

Preciso implementar 
[Essa api](https://api.monetizze.com.br/2.1/apidoc/#api-_footer)
 para pegar email dos compradores e criar um login para eles com email e gerar uma senha provisória

**Comment by brianrodrigues** [comment]
`    <?php
  $url = "https://api.monetizze.com.br/2.1/token";
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_HTTPHEADER, ["X_CONSUMER_KEY: aabd7fe84e66f643e40c361f8340788d"];
  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
  curl_setopt($ch, CURLOPT_URL, $url); 
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);    
  
  $res = curl_exec($ch);

  $dados = json_decode($res);


?>   `

**Comment by jdnichollsc** [comment]
Share your Unity code with C# to be able to help you, also please use English or Spanish instead 👍
