### ISSUE TITLE
I cant get the GetArray<T> function to work.

### ISSUE THREAD

**Issue by krenerd** [proyecto26/RestClient#109]
I'm asking my question here because I can't think of another place that I could get a reply. I'm making a firebase database based on your RestClient from unity assetstore. I want to store the user's id on the database using a "User" class I defined with only int and string variables. 

I posted the data as followed
RestClient.Put("<URL>/Users/" + id + ".json", newUser).Then(response=>{ (some stuff) });

and got the data with the following code. 
RestClient.GetArray<User>("<URL>/Users.json").Then( response =>
        {
            Debug.Log(JsonHelper.ArrayToJsonString<User>(response, true));
            (some stuff);
        });

The problem is the reading part logs an empty array even though I manually checked the data. The Get<T> function applied on the same logic worked well. Is there any suspected problems you can think of?
Thank you.

**Comment by jdnichollsc** [comment]
Because Firebase works with objects instead of Arrays

**Comment by Azgraal** [comment]
Bump!
Were you able to solve this? I'm having the same issue; by targeting one "user" on the database it correctly retrieves the data as I want it, but using the Get Array function of the documentation I just get an "Unexpected node type" error.

**Comment by krenerd** [comment]
@Azgraal I implemented it using firebase's own API. Check out this video https://www.youtube.com/watch?v=Vdgd9TLczY4.
