### ISSUE TITLE
obsoletion warning for UnityWebRequest.chunkedTransfer

### ISSUE THREAD

**Issue by Extrawurst** [proyecto26/RestClient#110]
unity `2019.3.f03`:

```
Assets/RestClient/Packages/Proyecto26.RestClient/Helpers/Common.cs(63,17): warning CS0618: 'UnityWebRequest.chunkedTransfer' is obsolete: 'HTTP/2 and many HTTP/1.1 servers don't support this; we recommend leaving it set to false (default).'
```

**Comment by jdnichollsc** [comment]
Very odd, chunkedTransfer is false by default https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Helpers/RequestHelper.cs#L120

**Comment by Extrawurst** [comment]
@jdnichollsc the warning originates from the deprecation of the API in unity `2019.3`: see the docs https://docs.unity3d.com/2019.3/Documentation/ScriptReference/Networking.UnityWebRequest-chunkedTransfer.html

**Comment by Extrawurst** [comment]
@jdnichollsc any objections with the PR? anything I can improve?

**Comment by jdnichollsc** [comment]
Ohh no, it looks perfect! I'm busy right now, but let me publish a new version with these changes as soon as possible 🙏

**Comment by jdnichollsc** [comment]
Done!
