### ISSUE TITLE
Having Latency Issues on Mobile

### ISSUE THREAD

**Issue by umityayla** [proyecto26/RestClient#112]
Hello,

We've been using RestClient for a while now, but we have a problem that has been a burden for us. When we send a request on Unity Editor, it returns with 250-300 ms of response time. But when we build the project for iOS or Android; then we start to have problems. It mostly returns with 300-350 ms of response time but it sometimes spikes to 1000-3000 ms of response time. We currently use Unity 2019.1.4f1, tried upgrading to Unity 2019.2+, default http-keep-alive is true over there so it kind of hides our problem but the problem is still there. We can still see that there's a problem with beginning of the handshake. I believe there's a problem with the TCP/SSL handshakes. We sometimes have mysterious "Unknown Error" prompts, sometimes request timeout as expected... But once again, it has been quite a burden for us as we are increasing our API call counts throught the game.

Tried attaching a custom certificate handler and accepting every certificate, still didn't solve our problem. Tried disabling 100-Http-Continue, didn't solve either. 

Thank you for helping me and I hope we can figure this out.

**Comment by jdnichollsc** [comment]
This library is only a wrapper of `UnityWebRequest` system, so any issue related with the latency of the requests is handled by that Unity system, check these links:
- https://docs.unity3d.com/Manual/UnityWebRequest.html
- https://blogs.unity3d.com/2018/08/02/evolving-multiplayer-games-beyond-unet/
- https://support.unity3d.com/hc/en-us/articles/360001252086-UNet-Deprecation-FAQ

To avoid issues with the performance, latency, etc we're using **JsonUtility** function of Unity too.
Let me know if you find any issue with the code of this asset 👍

**Comment by umityayla** [comment]
Thank you for your reply, we'll look into it.
