### ISSUE TITLE
Get all user child

### ISSUE THREAD

**Issue by clar1s4** [proyecto26/RestClient#114]
i just want to know, there any method to show all of data from "Leaderboard" to .Json?
 
![image](https://user-images.githubusercontent.com/36913080/72987452-02ca2f80-3e1d-11ea-8cd4-c02c4d39b720.png)
 
i've trying using this code : 

RestClient.Get<UserLead>(databaseURL1 + "/" + ".json" ).
                Then(rsp =>
                {
                    EditorUtility.DisplayDialog("Json", JsonUtility.ToJson(userlead, true), "Ok");
                    Debug.Log(JsonUtility.ToJson(userlead));
                });

and wont show up anything from that code:

![image](https://user-images.githubusercontent.com/36913080/72987766-a4ea1780-3e1d-11ea-8e5d-3db2a5334eac.png)

thanks :)

**Comment by jdnichollsc** [comment]
Are you having problems with the library or are you asking about how to use JsonUtility with Firebase? because as you can see in that image Firebase returns an object instead of an Array
