### ISSUE TITLE
Wrong StatusCode in .Catch, when firebase return null

### ISSUE THREAD

**Issue by 1g0rrr** [proyecto26/RestClient#116]
For this code, Firebase return null, but the status code is 200. (I try to check if table exists)    

    RestClient.Get<DayMapData>($"some_firebase_url")
            .Then(
                //
            .Catch(except =>
            {
                RequestException re = except as RequestException;
                Debug.Log(re.StatusCode);
            });

I expected log "200", but I got a log "0".
It would be great to return the correct status code even if Json can't be parsed because of null.
With this behavior, I can check if table is missing and at the same time Firebase works correctly.

**Comment by jdnichollsc** [comment]
Hi @1g0rrr 
Can you help me to indicate where are we changing the status code from this asset?
