### ISSUE TITLE
Request OK but Json object not loading properly

### ISSUE THREAD

**Issue by giviz** [proyecto26/RestClient#117]
Hey guys :)
Testing the library for my game project, works fine so far except that issue I'm running into :

`public void GetVatoms()
        {
            currentRequest = new RequestHelper
            {
                Uri = basePath + "/v1/vatoms",
                Headers = new Dictionary<string, string> {
                    {
                        "Authorization", "Bearer " + token
                    }
                },
                EnableDebug = true
            };
            RestClient.Get<Vatoms>(currentRequest)
            .Then(res =>
                {
                    Debug.Log(JsonUtility.ToJson(res, true));
                    RestClient.ClearDefaultParams();
                }
            );
        }`

The response from the server is visible in the console

`{
    "data": [{
        "id": 3,
        "user_id": 1,
        "template_id": 1,
        "templatevariation_id": 1,
        // trucated here for lisibility
    }],
    "meta": {
        "draw": 0,
        "pagination": {
            "total": 2,
            "count": 2,
            "per_page": 10,
            "current_page": 1,
            "total_pages": 1,
            "links": []
        }
    }
}`

The model is as this
`using System;
using System.Collections.Generic;

namespace Vatomio.Models
{
    public class Value
    {
        public string resourceValueType { get; set; }
        public string value { get; set; }
    }

    public class Resource
    {
        public string name { get; set; }
        public string resourceType { get; set; }
        public Value value { get; set; }
    }

    public class Datum
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int? template_id { get; set; }
        public int? templatevariation_id { get; set; }
        // trucated here for lisibility
    }

    public class Pagination
    {
        public int total { get; set; }
        public int count { get; set; }
        public int per_page { get; set; }
        public int current_page { get; set; }
        public int total_pages { get; set; }
        public List<object> links { get; set; }
    }

    public class Meta
    {
        public int draw { get; set; }
        public Pagination pagination { get; set; }
    }

    public class Vatoms
    {
        public List<Datum> data { get; set; }
        public Meta meta { get; set; }
    }
}`

The last Debug return `{}` so it seems it just load an empty object.
My simpler tests work fine, but I can't get that one to work.

Any idea where I'm wrong ?

Thanks a lot !

PS : `Code` seems OK, no idea why the formatting is broken :/

**Comment by jdnichollsc** [comment]
Try using [JsonUtility](https://docs.unity3d.com/ScriptReference/JsonUtility.html) directly and let me know if it works for you :)

**Comment by giviz** [comment]
mmm it did not indeed, sorry I should have thought about testing that myself.

So it happened that I trusted too much the class generator for the json and I didn't added the `[System.Serializable]` not did I remove the `set; get;` that are not supported by JsonUtility.

Thank you, it's working now !
