### ISSUE TITLE
JSON is not being parsed correctly at times

### ISSUE THREAD

**Issue by mxsilva** [proyecto26/RestClient#118]
Hey! We've been using this awesome library in our Unity project for a few months and we're very happy with it. 

After we had some issues with some responses coming empty, took a look and found out this project is using Unity's JSON parsing library `JsonUtility`, which is not very robust. We replaced that in our projects with `Json.NET` library which is able, among other things, to parse properties on model classes which is kinda standard. Do you mind if I send a pull request replacing `JsonUtility`? Is there a specific reason why you had to use `JsonUtility` I'm ignoring? Thanks

**Comment by jdnichollsc** [comment]
In this wrapper we're using only utilities from Unity SDK, that's the reason :)
It would be better if we can add a handler here in order to inject any library to parse the response of the server, e.g: https://github.com/proyecto26/RestClient/issues/90

**Comment by mxsilva** [comment]
Yep, that would be a good approach. Using Unity's as default handler has the benefit of not having dependencies and supporting all listed platforms (now and in the future as long as Unity does not mess that up) which seems ok to me. That being said, not supporting plugins or handlers for JSON serialization severely limits the usefulness of the library, so it's a good idea in this context. I will take a look at it.
