### ISSUE TITLE
POST example from Readme doesn't properly send Body

### ISSUE THREAD

**Issue by votetuckie** [proyecto26/RestClient#119]
Hi,
I've been exploring node/express recently, and thought it would be interesting to see how to hook up unity to a webserver - this looks like one of the simplest solutions around for that.

Set up a simple hello world GET request that worked fine, and went on to try out a POST. For the life of me, it seems like I can't get that functioning - as on the node end - the body consistently was undefined. I set up a serializable class with a public name string and was just trying to get the server to print that out.

As a sanity check - just to make sure I wasn't glancing over something obvious - I copied the example (from the bottom of your README) and it appears to have the same issue - req.body being undefined.

For complete transparent reference - this is what I have set up - adapted from the code in your readme:

unity (monobehavior attached to an otherwise empty gameobject)
```c#
using UnityEngine;
using Proyecto26;
using System;

public class TwkyRestClient : MonoBehaviour {

    [Serializable]
    public class ServerResponse
    {
        public string id;
        public string date; //DateTime is not supported by JsonUtility
    }
    [Serializable]
    public class User
    {
        public string firstName;
        public string lastName;
    }

    public string base_uri; // this is set to localhost:port in the inspector

    void Start() {
        RestClient.Post<ServerResponse>(base_uri + "/", new User
        {
            firstName = "Juan David",
            lastName = "Nicholls Cardona"
        }).Then(response => {
            print(response.id);
            print(response.date);
        });
    }
}
```
express
```javascript
const express = require('express')
const app = express()

app.post('/', function (req, res) {
    console.log(req.body.firstName)
    res.json({
        id: 123,
        date: new Date()
    })
});

app.listen(3000)
```

In this case - console.log(req.body.firstName) gives `Cannot read property 'firstName' of undefined` which I guess is expected because console.log(req.bod) prints out `undefined`. Is there some configuration/setup that I've skipped somewhere, or is there some greater underlying issue causing this, like through JsonUtility/etc? For additional reference - I had this same issue both on the unitypackage hosted on this git page, and the asset store version. Sorry in advance if I'm just not paying proper attention to something here.

**Comment by jdnichollsc** [comment]
because you need to configure body-parser, check => https://stackoverflow.com/a/27855234/1532821

**Comment by votetuckie** [comment]
Thanks so  - i figured it was something really simple like that, hahah.
