### ISSUE TITLE
Does not work on Unity 5.6.1f1

### ISSUE THREAD

**Issue by BoRuDar** [proyecto26/RestClient#12]
Unity version: 5.6.1f1 
OS: Windows 7
Crashes with error:
```
MissingMethodException: Method not found: 'UnityEngine.Networking.UnityWebRequest.set_timeout'.
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Proyecto26.StaticCoroutine:StartCoroutine(IEnumerator)
Proyecto26.RestClient:GetArray(RequestHelper, Action`2)
Proyecto26.RestClient:GetArray(RequestHelper)
MainScript:Get() (at Assets/RestClient/DemoScene/Scripts/MainScript.cs:20)
UnityEngine.EventSystems.EventSystem:Update()
```

**Comment by jdnichollsc** [comment]
Same issue reported here https://github.com/proyecto26/RestClient/issues/6

**Comment by BoRuDar** [comment]
Thanks for the fast answer. Specify this in Readme please.

**Comment by jdnichollsc** [comment]
@BoRuDar Can you update your Unity version or the **5.6.1f1** version is required for your project?

**Comment by Tehmasip** [comment]
Anyone found the solution

**Comment by jdnichollsc** [comment]
This plugin works with the UnityWebRequest system :)

**Comment by Tehmasip** [comment]
SO WHAT SHOULD I DO?

**Comment by Tehmasip** [comment]
ITS WRKING IN 2018 BUT NOT IN VERSION 5.6

**Comment by Tehmasip** [comment]
KINDLY GUIDE A BIT

**Comment by jdnichollsc** [comment]
As you can see from the Unity Store the supported Unity versions are 2017.1.5 or higher 👍 https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501
