### ISSUE TITLE
Rest.Get() freezes the main thread 

### ISSUE THREAD

**Issue by Alastor87** [proyecto26/RestClient#120]
I'm trying to download a video file using Rest.Get(), but looks like the process runs on the main thread and therefore the app freezes for half minute.
 
I tried to run the method in a different thread but no luck.

**Comment by jdnichollsc** [comment]
Can you share the code please?

**Comment by Alastor87** [comment]
Sure, this is the code:

RestClient.Get(videoInfo.clipURL).Then(response =>
    {
        byte[] videoData = response.Data;
        ......   
    });
});

The parameter passed to the Get method is the URL to the clip stored on the server. As I mentioned, the download is successful but because it's a big file, it takes long and it's freezing the main thread (therefore the UI, interactions etc...).

Thanks for your support.

**Comment by jdnichollsc** [comment]
Where do you have the video stored? Are you using blob storage or any other cloud service like that? or are you using an On-Premise solution?

**Comment by Alastor87** [comment]
The video is stored on OneDrive.

**Comment by jdnichollsc** [comment]
@Alastor87 I was wondering if you have this same behavior using callback instead?
```
RestClient.Get(videoInfo.clipURL, (err, res) => {
  byte[] videoData = res.Data;
});
```
Please let me know! 👍

**Comment by Alastor87** [comment]
@jdnichollsc I've tried and the result is unfortunately the same.

Thanks for your effort so far!

**Comment by mhr** [comment]
I also have the same issue. I've found that Put() also blocks. It's not noticeable except when I download huge files, but I'm downloading mesh models, so the app ends up freezing while the download takes place.

**Comment by jdnichollsc** [comment]
What kind of content type are you using for this request?

**Comment by mhr** [comment]
I don't specify, so it's whatever the default is:
```
string api = apiUrl + query;
RestClient.Get(api).Then(res =>
{
    promise.Resolve(res.Text);
})
```

**Comment by jdnichollsc** [comment]
Can you try with the `DownloadHandler` option? It's used to download huge files like mesh models :)

**Comment by mhr** [comment]
I'm sorry, I'm a little confused as to what `DownloadHandler`'s `destPath` is supposed to be. Is that supposed to be the same as `Uri`, or is that supposed to be the eventual location at which the file is downloaded? Either way, I'm getting some exceptions. For the first, res was `{}` and `.Catch(err => print(err.Message))` gave me `Object reference not set to an instance of an object`, and for the second, I get `ArgumentException: path. System.IO.DirectoryInfo.CheckPath (System.String path) (at <9577ac7a62ef43179789031239ba8798>:0)`.

```
System.IO.Directory.CreateDirectory(Application.persistentDataPath + "/Meshes/");

string path = UnityWebRequest.EscapeURL("/Resources/Mesh/");
RestClient.Get(new RequestHelper
{
    Uri = apiUrl + String.Format("/stream?path={0}&filename={1}", path, "model.obj"),
    DownloadHandler = new DownloadHandlerFile(Application.persistentDataPath + "/Meshes/model.obj")
}).Then(res =>
{
    File.WriteAllBytes(Application.persistentDataPath + "/Meshes/model.obj", res.Data);
});
```

OR

```
System.IO.Directory.CreateDirectory(Application.persistentDataPath + "/Meshes/");

string path = UnityWebRequest.EscapeURL("/Resources/Mesh/");
RestClient.Get(new RequestHelper
{
    Uri = apiUrl + String.Format("/stream?path={0}&filename={1}", path, "model.obj"),
    DownloadHandler = new DownloadHandlerFile(apiUrl + String.Format("/stream?path={0}&filename={1}", path, "model.obj"))
}).Then(res =>
{
    File.WriteAllBytes(Application.persistentDataPath + "/Meshes/model.obj", res.Data);
});
```

**Comment by jdnichollsc** [comment]
Can you try the download handler directly with a UnityWebRequest? Let me know if this works for you, and with the code of example I can show you how to do that with this wrapper library https://docs.unity3d.com/ScriptReference/Networking.DownloadHandler.html

**Comment by jdnichollsc** [comment]
Ok let me know if you're still presenting this issue to reopen 👍
