### ISSUE TITLE
Are Proxies Supported

### ISSUE THREAD

**Issue by reganam** [proyecto26/RestClient#123]
Is it possible to use proxies to download?

**Comment by jdnichollsc** [comment]
It looks like UnityWebRequest system has no proxy support https://fogbugz.unity3d.com/default.asp?807081_p6p8jtakhuvskj2s&_ga=2.267899662.1654628586.1584762906-957388316.1584762906

**Comment by jdnichollsc** [comment]
More details here => https://stackoverflow.com/a/53214048

**Comment by jdnichollsc** [comment]
Let me know if you find any solution! 👍
