### ISSUE TITLE
Requests not being sent within a Timers.Timer call

### ISSUE THREAD

**Issue by oskarious** [proyecto26/RestClient#125]
Hello,

I am running into a strange issue where I have a timer that sends a heart beat to a master server every x seconds, however it doesnt seem to want to run once the timer sends it's elapsed event.

I am no c# expert, so it's entirely possible it's something to do with how the timers class works, but running Debug.Log within the callback works fine.

```cs
// Timer setup in a seperate function
            var heartBeatTimer = new System.Timers.Timer(60000);
            heartBeatTimer.AutoReset = true;
            heartBeatTimer.Enabled = true;
            heartBeatTimer.Elapsed += (e, f) =>
            {
                HeartBeat();
            };

        static void HeartBeat()
        {
            Debug.Log(extIp); // <- runs
            PostHeartBeat(); // <- runs
        }

        static void PostHeartBeat()
        {
            Debug.Log("asd") // <- runs

            // RestClient call does not run =(
            RestClient.Post($"{masterServerIp}/ms/heartbeat", new Game() { ip = extIp, port = "15937" }).Then(e =>
            {
                Debug.Log("Sending heart beat");
                Debug.Log(e.StatusCode);
            }).Catch(e =>
            {
                Debug.LogError(e);
            });
        }
```

Calling `HeartBeat()` outside of the timer call works fine and I get the response I expect, so I am kinda scratching my head. 

Any help would be appreciated, cheers!

**Comment by oskarious** [comment]
An update to this: when I ran the code on the main thread it worked fine, so I suppose RestClient needs to be ran on the main thread and timers runs on a seperate thread. Will close this for now as the workaround is sufficient for me.

**Comment by jdnichollsc** [comment]
Ohh ok, thanks for your info!
