### ISSUE TITLE
Nested JSON response

### ISSUE THREAD

**Issue by knelasevero** [proyecto26/RestClient#126]
Hi!

How would I use this RestClient to consume an API that has nested stuff in the JSON that it responds?

Something like:
```
{
"Name": "something",
"Email": "something",
"Metadata": {
    "list of stuff": [0,1]
    },
"Gender": "Masc"
}
```

**Comment by jdnichollsc** [comment]
We're using this Utility function by default: https://docs.unity3d.com/ScriptReference/JsonUtility.html
But you can use any other tool :)

**Comment by knelasevero** [comment]
Documentation shows how to use BodyString to serialize using other tool, but it does not show how to deserialize the response using custom tool.

**Comment by knelasevero** [comment]
To anyone with the same requirement. If you want to **send** a body with nested stuff, use the BodyString option like stated in the documentation. 

To **receive** nested stuff you will have to change the DefaultUnityWebRequest on HttpBase.cs of this RestClient to use the deserialization method of your choosing.

Would be nice to make this parametrizable, I will think about creating a merge request if I have time in the future.

**Comment by knelasevero** [comment]
I used this one https://github.com/jilleJr/Newtonsoft.Json-for-Unity

**Comment by jdnichollsc** [comment]
>Would be nice to make this parametrizable, I will think about creating a merge request if I have time in the future.

It would be awesome, thanks! 👍
