### ISSUE TITLE
Webgl The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by Lucidarme** [proyecto26/RestClient#127]
Everything works well on standalone, but when I try to make a request on webgl, Catch statement is reach with this error : 

> The given key was not present in the dictionary.

```
        RestClient.Post( new RequestHelper
            {
                Uri = ServerPath.loginPath,
                Body = new UserCredentials
                {
                    username = m_Username.text,
                    password = m_Password.text
                }
            }
        )
        .Then(res =>
        {            
            string dico = res.Headers["Authorization"];  // Catch error here
     
            RestClient.DefaultRequestHeaders["Authorization"] = dico; // this line is never reached
        })
        .Catch(err =>
        {
            Debug.LogError("catch " + err.Message);
        });
```

Here is the headers I received :
```
Server: nginx/1.17.0
Date: Thu, 16 Apr 2020 12:24:55 GMT
Content-Length: 0
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: http://localhost:55174
Access-Control-Allow-Credentials: true
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.ey.....
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
```

And here is the headers present in res.Headers : 
```
Content-Length: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
```

As you can see, the request is successfull and I receive the correct answer, with Authorization in headers, but i'm not able to find this header in res. In standalone, I can find this header without any problems.
Thanks for your help.

**Comment by jdnichollsc** [comment]
Authorization header is part of the request headers instead of response headers, so you need to use request helper instead

**Comment by Lucidarme** [comment]
Thanks for your answer but it doesn't work, res.Headers contains Authorization in standalone, whereas req.Headers contains nothing :

Here is the content of req.Headers: (empty for both standalone and webgl)
![req](https://user-images.githubusercontent.com/12626154/79464403-4d151400-7ffa-11ea-9c2e-1e032e24127d.png)

Here is the content of res.Headers in standalone: ( in webgl, there is only 4 headers for the same request )
![res](https://user-images.githubusercontent.com/12626154/79464019-daa43400-7ff9-11ea-95ec-1eaf068f46dc.png)

**Comment by jdnichollsc** [comment]
Are you sending that Header to your backend (Request Header) or are you receiving that header from backend (Response Header)?

**Comment by Lucidarme** [comment]
I am receiving that header from my backend. This request is for login.

**Comment by jdnichollsc** [comment]
I can't help you without an API to test, please share a reproducible demo to reopen this issue

**Comment by Lucidarme** [comment]
Here is a test. There is a button "login" and a script LoginController. It send a login request to my server and try to get Authorization header from Response. Please try it on unity editor and then on deployed webgl. You will see that it works on unity editor but not on webgl.

[This page from unity manual](https://docs.unity3d.com/Manual/webgl-browsercompatibility.html) talk about incompatibility with "Large-Allocation Http header" on some browsers but I tried with multiple browsers but the result is the same...


[issue127.zip](https://github.com/proyecto26/RestClient/files/4488946/issue127.zip)

Thank you for your help

**Comment by jdnichollsc** [comment]
Why are you not sending that Token (JWT, etc) from body of the response? It's more common for a login to return that data from the body. I'm busy for the moment, but let me check that later

**Comment by Lucidarme** [comment]
I am sending token in headers because usually it works haha I never had a problem since i'm using webgl. I should maybe reconsider my choice

**Comment by Lucidarme** [comment]
Well you were right, Authorization header is not standard in the response, so the server has to explicitly inform to expose it with 

> Access-Control-Expose-Headers: Authorization

I don't understand why I never had to do that when I worked on ios / android / desktop.
Anyway, that's not an issue from this library. Thanks for your time

**Comment by jdnichollsc** [comment]
You're welcome mate!
