### ISSUE TITLE
cannot debug error message

### ISSUE THREAD

**Issue by duraiDk9** [proyecto26/RestClient#128]
my errror response :Proyecto26.RequestException: HTTP/1.1 400 Bad Request

how to get error message like this below
{
  "error": {
    "code": 400,
    "message": "INVALID_PASSWORD",
    "errors": [
      {
        "message": "INVALID_PASSWORD",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

**Comment by jdnichollsc** [comment]
Can you share your code?
