### ISSUE TITLE
Array of null ?? 

### ISSUE THREAD

**Issue by skyfyx** [proyecto26/RestClient#129]
Hi , 

Sorry for my english in first.

I have an issue with RestClient , when i put a data in Firebase sometimes i have no object but an array with null key and sometimes it's the good structure (json) with object. Because i'm not really good to speak in english a bit of code it's better.

My file with post function : 
[Part of code](https://pastebin.com/Brng2ddV)

Then the call of this function in main.cs ( call AfterSceneLoad): 
[Main.cs](https://pastebin.com/UxQ0Yqdk)

Sometimes it's good i have the good structure in Firebase (json) : 
[Good Json](https://pastebin.com/X48c4HSa)

and the next call at this function i have someting like this : 
[Mystery Json](https://pastebin.com/7ss0pSxn)

I have this mystery just when i change the id "3" by an another id like 4, 5 etc..

Thanks for your help , and for your job with this Asset ;)

**Comment by jdnichollsc** [comment]
Te queda mejor el español? let me know

I don't understand, can you create the request from Postman and share me the collection to be able to debug here? are you using an external JSON serialization tool? As far as I know [JsonUtility](https://docs.unity3d.com/ScriptReference/JsonUtility.html) function of Unity is very limited, specially for arrays

**Comment by skyfyx** [comment]
No i'm not better in espagnol :) 

I'll have a look at this website that i did'nt know before. 
And for the "put" of "RestClient" he uses an external serialization tool? Because i use "FullSerializer" i don't know if it's important for "put".

**Comment by jdnichollsc** [comment]
We're using [JsonUtility](https://docs.unity3d.com/ScriptReference/JsonUtility.html) function by default to avoid external dependencies in this asset but you can use other tools to serialize the JSON response.
If you have the same issue from [Postman](https://www.postman.com/), the issue is not related with this asset, the issue comes from your backend (API, Firebase, etc)
