### ISSUE TITLE
Add more HTTP methods

### ISSUE THREAD

**Issue by ronneke1996** [proyecto26/RestClient#13]
Add more HTTP methods like the ones below:

- PATCH
- OPTIONS
- HEAD

**Comment by jdnichollsc** [comment]
Can you give me an example using these HTTP verbs?

**Comment by ronneke1996** [comment]
How do you mean an example. It's mostly "cosmetic" though, because you can use an PUT instead of an PATCH, but like said in this answer (https://www.quora.com/What-is-the-difference-between-PUT-POST-and-PATCH-for-RESTful-APIs). An PUT is for overwriting a whole entity and PATCH only for field updates.

HEAD is for only getting the header of a request, so without all the data (this could be handy for validating stuff before making a full request)

OPTIONS is used to receive information of the REST server like communication options. This can also be used for validation in an application.

**Comment by jdnichollsc** [comment]
ok, let me do the changes at weekend or you can create a pull request 👍

**Comment by ronneke1996** [comment]
Looks fine by me, but at the moment I'm not able to test the code. So only a code review on github has been done by me.

**Comment by jdnichollsc** [comment]
@ronneke1996 A moment ago, I reverted all the changes from the master branch to create a pull request to compare with the previous version of the plugin, I'm going to add a property `BodyString` from the `RequestHelper` class to send your JSON if you want to use other tool to serialize the code, so let me do that change and improve the code, any comments are really apreciated

Pull request => https://github.com/proyecto26/RestClient/pull/18

Regards, Nicholls

**Comment by jdnichollsc** [comment]
Check my friend the files modified, thanks for your help and patience! 💯  https://github.com/proyecto26/RestClient/pull/18/files

**Comment by jdnichollsc** [comment]
@ronneke1996 the issue was fixed in the last version
Any comment from the unity store is really appreciated! 👍 https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501
