### ISSUE TITLE
404 not found for a good API request

### ISSUE THREAD

**Issue by maximehelaine** [proyecto26/RestClient#130]
Thank you for your asset !
When i call a GET with a "Basic Auth" in Authorization Header field, i receive a 404 error whereas if I look at the response, there's a json object with a status code of 2 and not 404.

Error response :
`{"success":true,"data":{"id":**,"orderId":***,"productId":***,"userId":***,"licenseKey":"***","expiresAt":null,"validFor":0,"source":1,"status":2,"timesActivated":0}}`

So why is it not a success response and why send an exception ?

**Comment by jdnichollsc** [comment]
Please share your code and a screenshot of the response from Postman

**Comment by maximehelaine** [comment]
I'm using the API of woocommerce (Wordpress plugin) with HTTP Basic Auth by providing the REST API Consumer Key as the username and the REST API Consumer Secret as the password. No problem on Postman.
![image](https://user-images.githubusercontent.com/5764566/80993153-e2a60580-8e3a-11ea-8669-9115800ab1af.png)
I'm using exactly the same request on Unity with the same header as in Postman. On Unity i have 404 exception but the response in the exception is the same as in Postman. So i don't understand why it catch an exception.
![image](https://user-images.githubusercontent.com/5764566/80993244-0e28f000-8e3b-11ea-9db6-d2fe82b01220.png)
![image](https://user-images.githubusercontent.com/5764566/80993945-39600f00-8e3c-11ea-8141-f0bddfc6b92f.png)

**Comment by jdnichollsc** [comment]
That status code is returned by UnityWebRequest system 🤔

**Comment by jdnichollsc** [comment]
Can you put a breakpoint here and send me the info of the response please? https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Helpers/HttpBase.cs#L20

**Comment by maximehelaine** [comment]
Response:
![image](https://user-images.githubusercontent.com/5764566/80996610-64e4f880-8e40-11ea-9c22-46510be7170f.png)
Request:
![image](https://user-images.githubusercontent.com/5764566/80996785-abd2ee00-8e40-11ea-888c-57bd1be79bc4.png)
Request Download Handler:
![image](https://user-images.githubusercontent.com/5764566/80996917-e76db800-8e40-11ea-8dfb-57b0b0a1aed3.png)

**Comment by maximehelaine** [comment]
Looking at your code, I also had this impression that it would come from UnityWebRequest 🤔

**Comment by jdnichollsc** [comment]
exactly, this asset is only a wrapper for that system, very odd mmm

**Comment by jdnichollsc** [comment]
if you want you can avoid http errors by using the option `IgnoreHttpException` of the request helper:
````
RestClient.Get(new RequestHelper { 
  Uri = "https://jsonplaceholder.typicode.com/photos",
  IgnoreHttpException = true
})
````
Try and let me know if it works for you :)

**Comment by maximehelaine** [comment]
So i wrote :
```
RestClient.DefaultRequestHeaders["Authorization"] = basicAuthent;
        RestClient.Get(new RequestHelper
        {
            Uri = basePath,
            IgnoreHttpException = true
        })
        .Then(res => {
            this.LogMessage("Success", JsonUtility.ToJson(res, true));
        })
        .Catch(err => {
            this.LogMessage("Error", err.Message);
        });
```
But i have this result : 
![image](https://user-images.githubusercontent.com/5764566/81004650-04a88380-8e4d-11ea-8822-821e2668d25f.png)

**Comment by jdnichollsc** [comment]
If you don't use generics like Get<MyCustomClass> you need to serialize the response by your own, and response here is the request helper, so you can fin the response from res.Text or res.Data 🙂

**Comment by maximehelaine** [comment]
Ok thank you for your help, and well done again for your asset ;)
