### ISSUE TITLE
Getting arrays from firebase

### ISSUE THREAD

**Issue by Khaled-Awashreh** [proyecto26/RestClient#131]
Hello, im working on a game project where im trying to make a scoreboard for players. and to do that im trying to get all class's instance in unity. I tried to use the .getArray method as the following: 

 RestClient.GetArray<playerScore>("https://kohoisland-cef6e.firebaseio.com/"+".json").Then(users =>
        {
            Debug.Log(users.Length+"count");
        
        });
    }

but it is retreiving nll

**Comment by jdnichollsc** [comment]
Are you sure Firebase is returning an array? Because as far as I know, Firebase always return an object 🙂

**Comment by Khaled-Awashreh** [comment]
well, how do i handle several logs in firebase?

**Comment by jdnichollsc** [comment]
If you don't know how to serialize this kind of objects by using JSON Serialization tools like [JsonUtility](https://docs.unity3d.com/ScriptReference/JsonUtility.html), etc
I recommend you to use Firebase SDK instead for this specific situation https://firebase.google.com/docs/database/unity/retrieve-data#value-events
Regards

**Comment by Khaled-Awashreh** [comment]
I dont think you understand, my objects are  serialized and i do place them
on the server i just cant retrieve them. In addition, i already tried using
the SDK and it will require changing too much in able to use it in my
project

**Comment by jdnichollsc** [comment]
Please attach a screenshot of the response of your firebase endpoint from Postman

**Comment by Khaled-Awashreh** [comment]
im sorry for my ignorance, i really dont know what a postman is

**Comment by Khaled-Awashreh** [comment]
[image: image.png]

this is how i attempt to read the data, it does upload and both post and
put work perfectly but get does not work

**Comment by jdnichollsc** [comment]
Postman is a rest client to test your endpoints https://www.postman.com/

**Comment by Khaled-Awashreh** [comment]
small update: when i tried to retrieved a single entry and it worked fine.
But reading all data is where im stuck at the moment. im trying to learn
from this :

https://medium.com/@rotolonico/firebase-database-in-unity-with-rest-api-42f2cf6a2bbf


but is there already a built in way to read all database?

**Comment by jdnichollsc** [comment]
No, this Rest client is not designed for specific services or databases like Firebase, it follows the convention of any HTTP request :)
