### ISSUE TITLE
¿Cómo obtener el progreso de descarga?

### ISSUE THREAD

**Issue by xvita** [proyecto26/RestClient#132]
Hola, tengo una duda.

De acuerdo al ejemplo para descargar un Audio:

`var fileUrl = "https://raw.githubusercontent.com/IonDen/ion.sound/master/sounds/bell_ring.ogg";
var fileType = AudioType.OGGVORBIS;

RestClient.Get(new RequestHelper {
  Uri = fileUrl,
  DownloadHandler = new DownloadHandlerAudioClip(fileUrl, fileType)
}).Then(res => {
  AudioSource audio = GetComponent<AudioSource>();
  audio.clip = ((DownloadHandlerAudioClip)res.Request.downloadHandler).audioClip;
  audio.Play();
}).Catch(err => {
  EditorUtility.DisplayDialog ("Error", err.Message, "Ok");
});`

¿Cómo puedo obtener el porcentaje de descarga de dicho audio?
Se tiene que implementar en un Update? o se realiza dentro de un .Progress?

¡Muchas gracias!

**Comment by jdnichollsc** [comment]
Hola :)

Puedes hacerlo de esta manera:
```
var request = new RequestHelper {
  Uri = fileUrl,
  DownloadHandler = new DownloadHandlerAudioClip(fileUrl, fileType)
};
RestClient.Get(request)

// En el update o donde quieras ponerlo
// request.DownloadProgress
```
Aquí puedes ver todas las propiedades del request: https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Helpers/RequestHelperExtension.cs
