### ISSUE TITLE
Support upm?

### ISSUE THREAD

**Issue by 0xF6** [proyecto26/RestClient#133]
https://openupm.com/

**Comment by jdnichollsc** [comment]
Beautiful, let me check! thanks!

**Comment by are-chris** [comment]
Goes into the same direction. Please add the possibility to use Unitys Package Manager for your project. see here for some introduction:
https://docs.unity3d.com/Manual/upm-manifestPrj.html

**Comment by 0xF6** [comment]
Package approved! Yay!  🙃

Thanks

**Comment by jdnichollsc** [comment]
Awesome! Let me know if you have any issue and thanks for reporting this issue! <3

**Comment by jdnichollsc** [comment]
Hello @0xF6 @are-chris hope you're doing well folks

Do you know if we can indicate the branch to support upm? Now we're using a GitHub action to update the `upm` branch of this repository :)

Thanks for your help and happy new year! <3
