### ISSUE TITLE
Catch request Sending HTTP/1.1 400 Bad Request instead of full body message

### ISSUE THREAD

**Issue by nwnisworking** [proyecto26/RestClient#134]
Hi there developer, I am developing using RestClient and I found out that you can't get error body message from the response. Since I am using it together with Google Identity Toolkit API, status code is not going to be useful in this matter.

Response From Catch: 
HTTP/1.1 400 Bad Request

Original Response:
```

{
  "error": {
    "code": 400,
    "message": "EMAIL_NOT_FOUND",
    "errors": [
      {
        "message": "EMAIL_NOT_FOUND",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

**Comment by jdnichollsc** [comment]
If you need to check the response (body), in that case you can use the `IgnoreHttpException` parameter of the [RequestHelper](https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/Helpers/RequestHelper.cs#L152)
