### ISSUE TITLE
Response from server incomplete

### ISSUE THREAD

**Issue by DanielFilipe** [proyecto26/RestClient#136]
Hi. 

I'm trying to send a POST request and when I try to log the error message I don't get the full response. It returns me the error status but not the error message. Is there a way to access the payload or the JSON the server is returning?

Thanks

**Comment by DanielFilipe** [comment]
Casting RequestException to get the response did the trick.

**Comment by jdnichollsc** [comment]
Any pull request in order to improve the README is always welcome! <3
