### ISSUE TITLE
How to upload photos to firestore

### ISSUE THREAD

**Issue by Fun52** [proyecto26/RestClient#137]
Hello.
Could you please give me an example how to upload photos to google firestore. Please!
Thanks

**Comment by jdnichollsc** [comment]
Try using Firebase SDK for Unity https://firebase.google.com/docs/storage/unity/start
If you have any issue with this library, please provide an sample project to be able to reproduce

Regards

**Comment by Fun52** [comment]
Hello,
I have tried a lot to use the Firebase SDK, but have always had problems with APKs that refuse to install or crash on startup.
That's when I decided to switch to your REST API which works wonderfully with Firebase to record player’s data. But I have a hard time running it with Firebase Storage to save photos, hence my request to get an example.
thanks a lot for your help
Best regards

**Comment by jdnichollsc** [comment]
Did you try using [UnityWebRequest](https://docs.unity3d.com/es/530/Manual/UnityWebRequest.html) directly? Share the code if you have any issue 👍

**Comment by jdnichollsc** [comment]
Sorry, but this plugin is just a wrapper for UnityWebRequest, we can't help you if the UnityWebRequest is not working for you directly. If you fix the issue, please let us know and we can create an example for you with the code of this plugin 🙂

**Comment by Fun52** [comment]
Could you help me write its equivalence with your asset ?

**Comment by jdnichollsc** [comment]
Did you try using `BodyRaw` property of the RequestHelper with a PUT request? https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/Helpers/RequestHelper.cs#L54
Check the README of the project :)
