### ISSUE TITLE
GET with Bearer auth token failing

### ISSUE THREAD

**Issue by JoaoReallyInteractive** [proyecto26/RestClient#139]
I'm having problems executing a GET request with a Bearer authentication token.

I've tested the URL and Token in Postman and it worked perfectly. I've implemented my own WebRequest in Unity and it also worked. 
So I can only assume that either I've set up something wrong on the request using the RESTClient or there's some other issue going on.

Any help would be appreciated. Thanks!

code:
`RestClient.Request(new RequestHelper {
Uri = "<URL>",
                Method = "GET",
                Headers = new Dictionary<string, string> {
                    { "Authorization", "Bearer <TOKEN>" }
                },
                DownloadHandler = new DownloadHandlerTexture()
            }).Then(response => {
                GetUserImageSucceeded(((DownloadHandlerTexture)response.Request.downloadHandler).texture);
            }).Catch(GetUserImageFailed);`

**Comment by jdnichollsc** [comment]
It's working from **NodeJS**, can you try using this template please and let me know? https://github.com/proyecto26/MyAPI

**Comment by JoaoReallyInteractive** [comment]
I'm not quite sure what to do here.
Following the steps, I get:

[Nest] 2836   - 07/03/2020, 09:38:47   [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Done in 8.43s.

when I run 'yarn start'.


Maybe worth mentioning as well is that I'm running Unity 2019.1.14f1

**Comment by JoaoReallyInteractive** [comment]
It seems that if I add a WWWForm, even if it's just by instantiating with the default constructor without changing any fields.
Do you know why that would be the case?

**Comment by jdnichollsc** [comment]
I'm only have experience using REST APIs with JSON, sorry for the delay 😅
