### ISSUE TITLE
Type IPromise<> Error - UWP

### ISSUE THREAD

**Issue by ronneke1996** [proyecto26/RestClient#14]
I've build my unity project to UWP (because I'm building an Hololens app). But when i want to deploy it to my Hololens via Visual Studio 2017 this error shows up. 

```
Error CS0012 The type 'IPromise<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'RSG.Promise, Version=3.0.0.0, Culture=neutral, PublicKeyToken=7019fe0722eef3a4'.
```

**Comment by jdnichollsc** [comment]
Are you downloading the package from the unity store? https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501

**Comment by jdnichollsc** [comment]
You can find the **RSG.Promise.dll** from the **Packages** directory

**Comment by ronneke1996** [comment]
Yes I downloaded the package from the unity asset store insite Unity it self, then imported it and removed the example code (because I imported that as well). The dll's are in my project and I can also find the after building in Unity in the solution for visual studio. So I find it weird that it throws that error

**Comment by jdnichollsc** [comment]
But what happen if you run the example from Unity? 
Maybe with Visual Studio the installation via Nuget package is better, try and let me know

**Comment by ronneke1996** [comment]
Running my application in Unity works just fine.

In the inspector in Unity:
<details>
  <summary>
    Show
  </summary>
  ![image](https://user-images.githubusercontent.com/9202089/37815733-53a0b712-2e70-11e8-8ab1-a0f9c7ba9613.png)
</details>

Build window in Unity:
<details>
  <summary>
    Show
  </summary>
![image](https://user-images.githubusercontent.com/9202089/37815789-96fa46cc-2e70-11e8-8784-749a022035f4.png)
</details>

After building the project in Unity and when I open the project in Visual Studio:
<details>
  <summary>
    Show
  </summary>
![image](https://user-images.githubusercontent.com/9202089/37816015-9b8399a4-2e71-11e8-8593-7cc8a6aece87.png)
</details>

**Comment by ronneke1996** [comment]
Trying to install it via NuGet in VS17 results also in an error.

```Package Proyecto26.RestClient 1.2.2 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package Proyecto26.RestClient 1.2.2 supports: net35 (.NETFramework,Version=v3.5)
Package RSG.Promise 3.0.0 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package RSG.Promise 3.0.0 supports: net35 (.NETFramework,Version=v3.5)```

But it looks like RSG.Promise isn't compatible, I'll try to look at their GitHub if there's an issue.

**Comment by jdnichollsc** [comment]
Hi @ashleydavis

Sorry to tag you, Do you know about this issue?

**Comment by ashleydavis** [comment]
It sounds like a project set up issue.

Or maybe .Net incompatibility? Which version of .Net is being used?

**Comment by jdnichollsc** [comment]
@ronneke1996 what version of .NET are you using?

**Comment by ronneke1996** [comment]
I'm Using 3.5 in the Unity editor and UWP for the Hololens(I'm not sure which .NET version that uses).
But as described here [(#73 C-Sharp-Promise)](https://github.com/Real-Serious-Games/C-Sharp-Promise/issues/73) it's probably an issue with UWP. In the future this should be solved by creating a build for uwp on nuget

**Comment by jdnichollsc** [comment]
@ronneke1996 Hi @ronneke1996 
I'm going to publish a new version `2.0.1` with the last changes of **RSG.Promise** (https://github.com/Real-Serious-Games/C-Sharp-Promise/pull/81)
Can you help me to debug from **Visual Studio**?

**Comment by jdnichollsc** [comment]
@ronneke1996 Please debug with the following dlls https://github.com/proyecto26/RestClient/releases/tag/2.0.1
Let me know to publish the new version from Unity store 👍

**Comment by ronneke1996** [comment]
@jdnichollsc Hello, sorry at the moment i'm not working with Unity and uwp any more. And I'm using a Linux pc. In addition to that, I haven't got the time to set it all up again to test this. So sorry, but it's not possible for me to help testing

**Comment by jdnichollsc** [comment]
@ronneke1996 No problem 👍

**Comment by Thomas-6freedom** [comment]
Hello. Sorry to reopen this but I have issues also with Hololens, so I thought it could be a good idea to post it here.

I use Unity 2018.3.10f1 with these settings :
![image](https://user-images.githubusercontent.com/49686866/56586385-ee33df00-65df-11e9-8eb0-f94bef57b9e2.png)

![image](https://user-images.githubusercontent.com/49686866/56586397-f7bd4700-65df-11e9-98d4-4f473662d934.png)

![image](https://user-images.githubusercontent.com/49686866/56586414-fee45500-65df-11e9-9268-dd7c56f7cf4b.png)

![image](https://user-images.githubusercontent.com/49686866/56586432-0572cc80-65e0-11e9-8fd0-ab5f07989f3d.png)


And it failed to build :

![image](https://user-images.githubusercontent.com/49686866/56586462-102d6180-65e0-11e9-8d53-852944b28a74.png)
