### ISSUE TITLE
How can I use the 'response' value to change other varible values in a function Thx 

### ISSUE THREAD

**Issue by qWildManp** [proyecto26/RestClient#140]
Here is my code :
  public bool Upload_file(string file_path)
    {
        bool flag = false;
        string upload_file_name = Path.GetFileName(file_path);
        string upload_file_type = Path.GetExtension(file_path);
        Debug.Log(upload_file_name + upload_file_type);
        Stream stream = new FileStream(file_path,FileMode.Open);
        byte[] buffer = new byte[stream.Length];
        stream.Read(buffer, 0, (int)stream.Length);
        stream.Close();
        currentRequest = new RequestHelper
        {
            Uri = basePath + "/filesystem/",
            Method = "POST",
            FormData = new WWWForm(),
            EnableDebug = true
        };
        currentRequest.FormData.AddBinaryData(upload_file_name, buffer);
        currentRequest.FormData.AddField("file_name", upload_file_name);
        currentRequest.FormData.AddField("file_type", upload_file_type);
        RestClient.Post(currentRequest).Then(response =>
        {
            if (response.Text.Trim().Equals("Success"))
            {
                flag = true;
            }
           
        });
        return flag;
        
    }
I want to change the value of 'flag' if the upload is success.However, the 'response' value in '.Then()' seems a loacal variable which just works within '.Then()',the value of 'flag' won't change. Can anybody help me?

**Comment by jdnichollsc** [comment]
Where do you want to access to that variable?

**Comment by jdnichollsc** [comment]
If you want to learn more about Promises, check here: https://github.com/Real-Serious-Games/C-Sharp-Promise

**Comment by qWildManp** [comment]
> Where do you want to access to that variable?

you can see from my function that the post request is just a part of the function.The '.Then()' function will receive the http response from my backend and store the value in the 'response' variable. But I cannot access the 'response' value outside the '.Then()' function.If there is any solution to let me get this value outside the ".Then()"

**Comment by jdnichollsc** [comment]
I don't have context, please share your code to understand why do you need that, it looks like you need to learn about promises, please check the previous link

**Comment by qWildManp** [comment]
public void getItemPosition(int exhibition_id, int item_id)//get one item position
    {
       
        currentRequest = new RequestHelper()
        {
            Uri = basePath + "/iteminfo/item_loc",
            Method = "POST",
            FormData = new WWWForm(),
            EnableDebug = true
        };
        currentRequest.FormData.AddField("exhibition_id", exhibition_id);
        currentRequest.FormData.AddField("item_id", item_id);
        RestClient.Post(currentRequest).Then(response =>
        {
            EditorUtility.DisplayDialog("INFO", response.Text, "OK");
            Debug.Log(response.Text);

        });
    }
Here is my code of another function. In this function I will cent a post request to the backend to get all items position information, the backend will return the value in json format.I want to store these items positions into a globle varibale which will be used in another function for items rendering
