### ISSUE TITLE
UnityPackageManager

### ISSUE THREAD

**Issue by Avatarchik** [proyecto26/RestClient#146]
Hi! Would you like to add support?

I tried to fix it like this : https://github.com/proyecto26/RestClient.git?path=src/Proyecto26.RestClient
But Unity (2020.1) gives an error:
package.json] is invalid:
    '5' is not a valid `unityRelease` attribute value. Expected '<patch><a, b, p or f><iteration>'. [NotFound].See console for more details

Ie not a valid package...

**Comment by jdnichollsc** [comment]
What's the correct value for that attribute? https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/package.json#L7

**Comment by Avatarchik** [comment]
https://docs.unity3d.com/Manual/upm-manifestPkg.html
it can be removed altogether based on the documentation, you can make a separate upm branch and arrange everything there as expected)
Sample:
https://nagachiang.github.io/tutorial-working-with-custom-package-in-unity-2019-2/#
https://neogeek.dev/creating-custom-packages-for-unity-2018.3/

**Comment by Merichbier** [comment]
I found this package on OpenUPM :
https://openupm.com/packages/com.proyecto26.restclient/

Is it also an official way of installing this plugin ?

**Comment by jdnichollsc** [comment]
the official way is downloading the asset from Unity store directly, or what do you mean?

**Comment by Merichbier** [comment]
I mean it seems possible to install this repo through the UPM using OpenUPM (link above) but it's not stated in the README, so I was wondering if it was at risk to use OpenUPM package to use this plugin.

**Comment by waldobronchart** [comment]
I'm trying to use this through OpenUPM, but getting the following errors:
![image](https://user-images.githubusercontent.com/464795/103245665-da04c100-492e-11eb-829f-902740afd449.png)

**Comment by jdnichollsc** [comment]
Honestly I don't have experience with OpenUPM, can you attach a repo and the steps to reproduce this issue? As I said before, any pull request is welcome!

**Comment by benukhanov** [comment]
> Honestly I don't have experience with OpenUPM and I'm not using Unity, can you attach a repo and the steps to reproduce this issue? As I said before, any pull request is welcome!

@waldobronchart @jdnichollsc #162 :smiley:

**Comment by jdnichollsc** [comment]
Hello folks, thanks for your collaboration!

We're using a GitHub action now instead here: https://github.com/proyecto26/RestClient/pull/198/files

Please check the `upm` branch and let me know!

Happy holidays <3
