### ISSUE TITLE
Return result of GET request

### ISSUE THREAD

**Issue by mo-krautsalat** [proyecto26/RestClient#148]
Hello, 
first of all: great library. Simplifies working with my CMS. However I'm wondering how I can return the result of a GET request. In my case this would be an image that I want to download. This is my the important part of my code:

```csharp
    private Texture2D DownloadImage(string address)
    {
        Texture2D tex = null;

        RestClient.Get(new RequestHelper
        {
            Uri = address,
            DownloadHandler = new DownloadHandlerTexture()
        }).Then(response =>
        {
            tex = DownloadHandlerTexture.GetContent(response.Request);
            return tex;

        }).Catch(err =>
        {
            Debug.LogError("Failed to download image: " + err.Message);
        });

        return tex;
    }
```
The problem is, that the method completes before the promise is done (of course it does, thats the reason for using async programming). Therefore the returned tex == null. I'm not that familiar with promises so maybe someone can help me out. 

Thanks in advance, 
Mo

**Comment by jdnichollsc** [comment]
If you are working with promises, `DownloadImage` should return a promise too :)
Learn more about promises here https://github.com/Real-Serious-Games/C-Sharp-Promise
