### ISSUE TITLE
About method

### ISSUE THREAD

**Issue by HajiyevEl** [proyecto26/RestClient#149]
Hi! First of all, thanks for great free asset! It's very easy to work with even for beginner like me.

About issue. Can you please give me advice, what method should i use to just add string to .json file on server(firebase)? Without downloading file, adding string, and putting it back to database.
I have "AllCharacterNames.json" and i want to add string with name when new character created. 
Brgds

**Comment by jdnichollsc** [comment]
Sorry, I don't catch your point, please provide an example to understand you 👍
