### ISSUE TITLE
How do you post Form data using your client in unity ?

### ISSUE THREAD

**Issue by arjuntilt** [proyecto26/RestClient#15]
I have gone through your documentation and couldn't see any information regarding this. Could you please update some information or post an example of the same. I am trying to create a login page in unity using your plugin but I am not able to do it.

**Comment by jdnichollsc** [comment]
Hi @arjuntilt, thanks for post this issue
Are you using a `List<IMultipartFormSection>` to create the formData? Can you share your code?
Best regards, Nicholls

**Comment by jdnichollsc** [comment]
A moment ago, I reverted all the changes from the master branch to create a pull request to compare with the previous version of the plugin, I'm going to add a property `BodyString` from the `RequestHelper` class to send your JSON if you want to use other tool to serialize the code, so let me do that change and improve the code, any comments are really apreciated

Pull request => https://github.com/proyecto26/RestClient/pull/18

Regards, Nicholls

**Comment by jdnichollsc** [comment]
@arjuntilt ok, with the 1.3.0 version of this plugin
- Unity
```
List<IMultipartFormSection> form = new List<IMultipartFormSection>();

form.Add(new MultipartFormDataSection("firstName", "Juan"));
form.Add(new MultipartFormDataSection("lastName", "Nicholls"));

RestClient.Post(new RequestHelper {
	Uri = "http://localhost:8080",
	FormSections = form
})
.Then(res => EditorUtility.DisplayDialog ("Success", res.Text, "Ok"))
.Catch(err => EditorUtility.DisplayDialog ("Error", err.Message, "Ok"));
```

- Backend (NodeJS, etc)
```
var express = require('express');
var router = express.Router();
var multipart = require('connect-multiparty');
var multipartMiddleware = multipart();

router.post('/', multipartMiddleware, function(req, res, next) {
  console.log(req.body.firstName)
  console.log(req.body.lastName)
  res.json({
    id: 123,
    date: new Date()
  })
});
```

<img width="421" alt="captura de pantalla 2018-05-20 a la s 3 32 44 p m" src="https://user-images.githubusercontent.com/2154886/40283400-16d21dac-5c43-11e8-8e4b-b59607a000a4.png">
