### ISSUE TITLE
How to get which request failed when chaining requests

### ISSUE THREAD

**Issue by emrys90** [proyecto26/RestClient#150]
If you chain multiple requests using Then, is it possible in the Catch to know which request it was that failed? IE getting which url contacted that failed. I'm trying to provide a user friendly message over why a request failed, and it would be useful to parse the responses if I knew which request triggered it.

**Comment by jdnichollsc** [comment]
It think you can attach a catch to your promises and throw another custom exception with that additional info :)

**Comment by emrys90** [comment]
Thanks for the suggestion. I had tried that though, and for some reason any exceptions I throw in a Catch or a Then are not caught by a following Catch. Is that a supported feature? If it is, any ideas why it wouldn't be catching them for me?

**Comment by jdnichollsc** [comment]
Can you share your code?

**Comment by emrys90** [comment]
```            
RestClient.Get(ApiUrl)
                .Then(response =>
                {
                     throw new Exception("Some message");
                })
                .Catch(exception =>
                {
                });```

So with something like this, my Catch method would not be getting called.

**Comment by jdnichollsc** [comment]
Try using **Promise.Rejected(someException)** instead of throwing an exception https://github.com/Real-Serious-Games/C-Sharp-Promise#promises-that-are-already-resolvedrejected

**Comment by emrys90** [comment]
Would you mind providing a code example of what should work? I had tried doing something like that I thought and it didn't work either

**Comment by lyze237** [comment]
If you have a .Then() chain and want to figure out which request failed, you can rethrow a exception in it which contains data about the request, for example:

```csharp
Debug.Log("Starting download");
RestClient.Get("http://localhost:8080/10000-0100.avi")
    .Then(helper => Debug.Log("Finished 1"), e => throw new Exception("Error at 1", e))
    .Then(() => RestClient.Get("http://localhost:8080/10000-0100.avi"))
    .Then(helper => Debug.Log("Finished 2"), e => throw new Exception("Error at 2", e))
    .Then(() => RestClient.Get("http://localhost:8080/10000-0100.avi-error"))
    .Then(helper => Debug.Log("Finished 3"), e => throw new Exception("Error at 3", e))
    .Then(() => RestClient.Get("http://localhost:8080/10000-0100.avi"))
    .Then(helper => Debug.Log("Finished 4"), e => throw new Exception("Error at 4", e))
    .Then(() => Debug.Log($"Finished download"))
    .Catch(Debug.LogException);
```

Request 1 and 2 are valid, therefore printing "Finished X". 3 is a 404 and therefore the error callback gets triggered. In that we rethrow the exception with data so we can identify which request failed.
After that in the .Catch we simply do whatever we want with it.

![image](https://user-images.githubusercontent.com/11274700/92720276-aba1ac80-f364-11ea-96c1-f06f270f35ee.png)
