### ISSUE TITLE
Catch is not catching exceptions thrown in Then

### ISSUE THREAD

**Issue by emrys90** [proyecto26/RestClient#151]
Is this expected behavior? How can I exit out of any future Then statements and go straight to the Catch for failure?

I have a case where I want a conditional failure to happen based on the results of an API call.

**Comment by lyze237** [comment]
Here's a basic test I did and it works just fine:

```csharp
        RestClient.Get("http://localhost:8080/10000-0100.avi")
            .Then(helper => Debug.Log("Finished 1"))
            .Then(() => RestClient.Get("http://localhost:8080/10000-0100.avi"))
            .Then(helper => Debug.Log("Finished 2"))
            .Then(() => RestClient.Get("http://localhost:8080/10000-0100.avi-error"))
            .Then(helper => Debug.Log("Finished 3"))
            .Then(() => RestClient.Get("http://localhost:8080/10000-0100.avi"))
            .Then(helper => Debug.Log("Finished 4"))
            .Then(() => Debug.Log($"Finished download"))
            .Catch(Debug.LogException);
```

![image](https://user-images.githubusercontent.com/11274700/92718819-9af03700-f362-11ea-8424-061b92f2a5be.png)

What are you doing exactly?

**Comment by emrys90** [comment]
```
RestClient.Get(ApiUrl)
                .Then(response =>
                {
                     throw new Exception("Some message");
                })
                .Catch(exception =>
                {
                });
```
So with something like this, my Catch method would not be getting called. Chained RectClient calls do work, but what if my own code fails? What's the correct way to throw exceptions in a Then for it to be caught in Catch?

**Comment by lyze237** [comment]
```csharp
Debug.Log("Starting download");
RestClient.Get("http://localhost:8080/10000-0100.avi")
    .Then(helper =>
    {
        Debug.Log("First then");
        throw new Exception("Then exception");
    })
    .Then(() => Debug.Log($"Second then"))
    .Catch(e =>
    {
        Debug.Log("Exception!!!");
        Debug.LogException(e);
    });
```

![image](https://user-images.githubusercontent.com/11274700/92765011-3ef2d600-f395-11ea-9a14-677e1cf0893f.png)

Works for me, unsure why it wouldn't for you?

**Comment by emrys90** [comment]
Hmm I just tried your code, and confirmed it works for me. Now I know I must have been doing something wrong somewhere. Thanks!

**Comment by jdnichollsc** [comment]
Thanks @lyze237 for your help! <3
