### ISSUE TITLE
Progress reporting via Promise.ReportProgress(...) 

### ISSUE THREAD

**Issue by lyze237** [proyecto26/RestClient#152]
Hello!

Lovely library, thanks for creating it!

It would be nice if the library could report progress via [Promise#ReportProgress](https://github.com/Real-Serious-Games/C-Sharp-Promise#progress-reporting) in addition to `request.DownloadProgress`.

This would improve workflow on progress reporting quite a bit in my opinion, for example:

```csharp
RestClient.Get(url)
    .Progress(value => Debug.Log($"Downloaded {(int) (value * 100)} %"))
    .Then(...);
```

**Comment by jdnichollsc** [comment]
Interesting, do you have any advice to do that?

**Comment by lyze237** [comment]
Just hacked together a solution by passing a third argument to `CreateRequestAndRetry`: `Action<float> progressCallback = null`. 
Therefore, one could pass a progress reporting function to everything starting from `RestClientPromise.Get()` 

https://github.com/lyze237/RestClient/commit/0aefb1015cb734c370de8dabf0c35feaa536d22a


I'm unsure if that's an ok approach.

**Comment by jdnichollsc** [comment]
Or maybe **progressCallback** can be a new option :)

**Comment by lyze237** [comment]
Oh yeah, that sounds like a better idea! 

I'll create a PR tomorrow if that's ok :)

**Comment by jdnichollsc** [comment]
Hey folks, thanks for your collaboration!

Please check the changes of the new release and let me know! 👍  https://github.com/proyecto26/RestClient/pull/196

Best,
Juan
