### ISSUE TITLE
Using RestClient within a task?

### ISSUE THREAD

**Issue by heath3n** [proyecto26/RestClient#154]
I'm using Firebase Auth to get an auth token; once I have it I need to set it as a header so I can make requests to my backend server. However because I'm putting `RestClient` within a task, I get the error `Internal_CreateGameObject can only be called from the main thread.`

```
_auth.CreateUserWithEmailAndPasswordAsync(email, password).ContinueWith(task => {
    if (!task.IsCompleted) return;

    FirebaseUser user = task.Result;
    user.TokenAsync(false).ContinueWith(tokenTask => {
        if (!tokenTask.IsCompleted) return;
        
        RestClient.DefaultRequestHeaders["Authorization"] = "Bearer " + tokenTask.Result;
        RestClient.Post("https://...."), null);
    });
});
```

What is the correct approach here?

**Comment by jdnichollsc** [comment]
Can you attach a repo to reproduce that issue?

**Comment by heath3n** [comment]
@jdnichollsc Added one here, sorry for the delay: https://github.com/heath3n/RestClientTaskErrorRepro.

There should be a scene `Scenes/ExampleScene`, just run the project in Unity (I'm using 2019.4) and observe you get the described error in the console.

**Comment by jdnichollsc** [comment]
Thanks for let me know mate!
