### ISSUE TITLE
Error:  CS0535: 'Promise<PromisedT>' does not implement interface member 'IPromise<PromisedT>.Then(string)'

### ISSUE THREAD

**Issue by yellowface7** [proyecto26/RestClient#156]
Assets\RestClient\Packages\RSG.Promise\Promise.cs(223,39): error CS0535: 'Promise<PromisedT>' does not implement interface member 'IPromise<PromisedT>.Then(string)'

I am confused. I just want to use a Quote of the Day API. :(

I wanted to test something I made but this error came up came up with and without the script.

**Comment by jdnichollsc** [comment]
Try asking here https://github.com/Real-Serious-Games/C-Sharp-Promise
