### ISSUE TITLE
ProgressCallback release?!

### ISSUE THREAD

**Issue by rezakho** [proyecto26/RestClient#157]
There is no ProgressCallback handler in v2.6.1.

**Comment by jdnichollsc** [comment]
Oh Sorry for the delay, let me generate a new release for this, I was on PTO :)

**Comment by shahrairenayaty** [comment]
please generate new release as soon as possible

**Comment by jdnichollsc** [comment]
Hello folks, I'm taking vacations during this week, stay tuned 🙂

**Comment by DrzwiPercepcji** [comment]
@jdnichollsc, please take a moment to make a new release. I think a lot of people are waiting for new features added recently, which they have no way of using at the moment. :)

**Comment by MJantowski3DQR** [comment]
Am I correct that no progress update is currently working?

I have tried:
RestClient.Post(requestHelper).Progress(Progress).Then(OnResolved, OnRejected);
RestClient.Post(requestHelper).Then(OnResolved, OnRejected, Progress);
RestClient.Post(requestHelper).Progress(Progress).Then(OnResolved, OnRejected, Progress);

But with all variants I don't get any output ..: /

thanks

**Comment by Ahmed310** [comment]
Same @MJantowski3DQR 

And there is no ProgressCallback field in  RequestHelper as mentioned in documentation

RestClient.Get(new RequestHelper {
  Uri = "https://jsonplaceholder.typicode.com/users", 
  ProgressCallback = percent => Debug.Log(percent)
});

any update on that

**Comment by jdnichollsc** [comment]
Hello folks, my personal computer stopped working and I have not been working with Unity, I will try to publish it as soon as possible, sorry for the delay 🙏

**Comment by MJantowski3DQR** [comment]
its dead :( 
i build a version for my own.

**Comment by jdnichollsc** [comment]
I will publish this new version today, sorry for the delay... my mac dead :(

**Comment by jdnichollsc** [comment]
Hello folks, can you help me reviewing these changes? https://github.com/proyecto26/RestClient/pull/196

Thanks for your collaboration! <3

**Comment by jdnichollsc** [comment]
Ok, the release 2.6.2 is here https://github.com/proyecto26/RestClient/releases/tag/v2.6.2

Happy new year! <3

**Comment by MJantowski3DQR** [comment]
Is it also possible to create the corresponding nuget package? Would be the cherry on the cake. Thank you very much!

**Comment by jdnichollsc** [comment]
@MJantowski3DQR oh let me do that with a new GitHub action, I found an issue with the configuration of the current pipeline from Azure DevOps

**Comment by jdnichollsc** [comment]
Done! We need to improve the current GitHub action workflow to update package versions and release description, maybe using semantic release too <3
