### ISSUE TITLE
Error Codes (again)

### ISSUE THREAD

**Issue by hyperspace101** [proyecto26/RestClient#159]
I'm having the same issue as #60 (Error Codes?) I can't extract error codes from  Catch(err =>       I can't access error.Response.  How can I see the error codes returned by the server? I've tried all the suggestions posted in issue #60 but nothing works.

**Comment by jdnichollsc** [comment]
Can you attach your code please?

**Comment by swimgod** [comment]
You most likely need to cast the error as a RequestException, I had similar problem until I looked at the example on the Github.

```
 .Catch(err => {
  var error = err as RequestException;
  EditorUtility.DisplayDialog("Error Response", error.Response, "Ok");
});
```
