### ISSUE TITLE
JSON must represent an object type when trying to retrieve a string value

### ISSUE THREAD

**Issue by mastef** [proyecto26/RestClient#161]
I'm retrieving a valid json string ( e.g. `"abc"` ) from the server.

```c#
RestClient.Get<string>(vURL).Then(res => {
	Debug.Log("got a response");
	Debug.Log(res);
}).Catch(err => Debug.LogError(err.Message));
```

2 issues with that : 
a) the call fails silently when there was no `.Catch` attached. Not sure if this is intended.
b) the call fails with : `JSON must represent an object type.` thrown by `JsonUtility`

This is a limitation of the `JsonUtility` library, which ( surprisingly ) cannot handle non-objects in the `FromJson` method. In my own implementation I used the `SimpleJSON` library as a workaround ( `string myString = JSON.Parse(webRequest.downloadHandler.text);` )

But I didn't want to use my own UnityWebRequest implementation, and was hoping to use a popular Rest library instead. Do you have a workaround for the parsing of non-object return values?

**Comment by jdnichollsc** [comment]
Hello Markus, happy new year!

a. Yes, this is a promise so that's the expected behavior.
b. Use your own library to parse the response or you can change the content type if you want

```
RestClient.Get(vURL).Then(res => {
	Debug.Log("got a response");
	Debug.Log(res); // Unity response without parsing
}).Catch(err => Debug.LogError(err.Message));
```

**Comment by mastef** [comment]
@jdnichollsc 

a. Are you sure that this is expected behavior in promises? Node also currently throws depreciation warnings that unhandled promise rejections would finish the script if a catch block is not present : `DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
b. Thanks!

**Comment by jdnichollsc** [comment]
That's the expected behavior in the most famous libraries (axios, Bluebird, Q, etc) from the browser, if you want to modify that behavior you can ask here: https://github.com/Real-Serious-Games/C-Sharp-Promise/issues
