### ISSUE TITLE
Serializing List / Dictionaries

### ISSUE THREAD

**Issue by CraftedPvP** [proyecto26/RestClient#163]
I have the following as class

```cs
[Serializable]
public class PlayerData{
    public Dictionary<string,float> variables = new Dictionary<string, float>();
}
```
I use enums as keys:

```cs
public class Keys {
    public enum PlayerStats{
        Stamina
    }
}
```
There's no tutorial nor forum explaining how it can be done using this client. Can someone help me out?

**Comment by jdnichollsc** [comment]
Please attach your code using Rest client library in order to reopen this issue and be able to reproduce the error

**Comment by CraftedPvP** [comment]
here's my code:
```cs
public void Test(){
    PlayerData playerData = new PlayerData();

    // error: JSON must represent an object type.
    RestClient.Put<PlayerData>(documentReference,playerData).Then(response => {
        Debug.Log("Updated player data: " + response.variables.Count);
    }).Catch(err => ShowError(err));
    
    // error: JSON must represent an object type.
    RestClient.Get<PlayerData>(documentReference).Then(response => {
        Debug.Log("Updated player data: " + response.variables.Count);
    }).Catch(err => ShowError(err));
}
```

**Comment by jdnichollsc** [comment]
Firebase returns another JSON structure, why not using Firebase SDK instead? Can you try that endpoint using Postman or any other HTTP client? Let me know

**Comment by CraftedPvP** [comment]
university requires it unfortunately. I would rather use Firebase SDK if it allows. So, based from your reply, this isn't supported with this package. thanks. feel free to close this now

**Comment by jdnichollsc** [comment]
> university requires me to use this package unfortunately

Sorry, It looks like you're learning how to use the Firebase REST API :)

> this isn't supported with this package

That's not true, you need to learn about [JsonUtility](https://docs.unity3d.com/ScriptReference/JsonUtility.html) of Unity or use any other JSON serialization tool with a REST Client, this is a simple wrapper for [UnityWebRequest](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html) system, you can find some good tutorials like [this](https://medium.com/@rotolonico/firebase-database-in-unity-with-rest-api-42f2cf6a2bbf).

Best
