### ISSUE TITLE
error CS0103: The name 'RestClient' does not exist in the current context

### ISSUE THREAD

**Issue by Indieaiden** [proyecto26/RestClient#165]
Hi, I've installed the package but when I try to call the class just by:
`RestClient.Put<User>($"{databaseURL}users/{userId}.json", user).Then(response => {
            callback();
        });`
it throws an error as the one in the title. I've been searching everywhere and reading but don't know if I've installed it wrong,
if I'm making any mistake or whatever.

Does somebody know how to fix it? thank you

**Comment by jdnichollsc** [comment]
Please share your file to review your code 👍
