### ISSUE TITLE
Body Raw

### ISSUE THREAD

**Issue by prabhupravan** [proyecto26/RestClient#167]
How to pass value to post man "body raw" through rest client, I need to change BodyRaw value dynamically 
![Body_Raw](https://user-images.githubusercontent.com/33712424/112996619-f1e81d00-9189-11eb-961a-ade213b69090.PNG)

I am following the below code 

RestClient.Request(new RequestHelper { 
  Uri = "https://jsonplaceholder.typicode.com/photos",
  Method = "POST",
  Timeout = 10,
  Params = new Dictionary<string, string> {
    { "param1", "Query string param..." }
  },
  Headers = new Dictionary<string, string> {
    { "Authorization", "Bearer JWT_token..." }
  },
  Body = newPhoto, //Serialize object using JsonUtility by default
  BodyString = SerializeObject(newPhoto), //Use it instead of 'Body' to serialize using other tools
  BodyRaw = CompressToRawData(newPhoto), //Use it instead of 'Body' to send raw data directly

**Comment by jdnichollsc** [comment]
If you have a serializable class you can use `Body` property, if you are using other tools to serialize data, you can use BodyString/BodyRaw, as you want 👍  Check our examples from README :)

**Comment by prabhupravan** [comment]
> I am following the below code
> 
> RestClient.Request(new RequestHelper {
> Uri = "https://jsonplaceholder.typicode.com/photos",
> Method = "POST",
> Timeout = 10,
> Params = new Dictionary<string, string> {
> { "param1", "Query string param..." }
> },
> Headers = new Dictionary<string, string> {
> { "Authorization", "Bearer JWT_token..." }
> },
> Body = newPhoto, //Serialize object using JsonUtility by default
> BodyString = SerializeObject(newPhoto), //Use it instead of 'Body' to serialize using other tools
> BodyRaw = CompressToRawData(newPhoto), //Use it instead of 'Body' to send raw data directly



> If you have a serializable class you can use `Body` property, if you are using other tools to serialize data, you can use BodyString/BodyRaw, as you want 👍 Check our examples from README :)

its not working, i need to send value to body Raw  to the API in postman, send and receive link request working fine through rest client, i have to send a value amount to the body raw 'serializable class' is not working

**Comment by jdnichollsc** [comment]
Please attach a reproducible demo to be able to debug your issue.

Thanks for your collaboration

**Comment by prabhupravan** [comment]
> Please attach a reproducible demo to be able to debug your issue.
> 
> Thanks for your collaboration


[bl_Extensions.zip](https://github.com/proyecto26/RestClient/files/6392255/bl_Extensions.zip)
i have attach my script, please help me out

**Comment by prabhupravan** [comment]
once the player killed i need to send amount value 1 to the API through the rest client
