### ISSUE TITLE
Errors in U2020.2.6f1

### ISSUE THREAD

**Issue by robhafey** [proyecto26/RestClient#169]
Hello.  I was happy to run across the RestClient for Unity but after importing it into U2020.2.6f1 I got a bunch of errors.  I then tried creating a new project in U2020.1.2f1 and it compiled fine.  My first thought was to dig in and fix the errors but thought I should check to see if a fix is on the way.  

Here are the errors...

![CompileErrors](https://user-images.githubusercontent.com/913605/113942141-39d3f900-97b5-11eb-96e2-f146a1cff8c5.png)

**Comment by jdnichollsc** [comment]
That's a dependency for Promises, can you report that issue [here](https://github.com/Real-Serious-Games/C-Sharp-Promise) please? <3

**Comment by robhafey** [comment]
Thanks for your reply.  I posted a question/request on C-Sharp-Promise.
