### ISSUE TITLE
Why throwing on error ?

### ISSUE THREAD

**Issue by antoine-pous** [proyecto26/RestClient#170]
Hi!

I'm using your client and i would like know why are you throwing on standard errors? Errors are part of a normal process, then having to catch errors 3xx 4xx 5xx instead of getting them through the promise resolution looks pretty weird to me.

Exception must be for unexpected errors, nothing more like it's done on most popular libraries in other languages :thinking: 

Thank you for your answer

**Comment by jdnichollsc** [comment]
Hello!

That's handled by Unity, this library is only a wrapper for **UnityWebRequest**, did you try **IgnoreHttpException** option?

Best,
Juan

**Comment by jdnichollsc** [comment]
Any pull request is welcome, thanks for your help! <3
