### ISSUE TITLE
webgl http cros?

### ISSUE THREAD

**Issue by sd63534790** [proyecto26/RestClient#171]
from origin 'http://localhost:8087' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by jdnichollsc** [comment]
Please attach a reproducible demo to be able to debug your issue 🙂

**Comment by sd63534790** [comment]
![1619065107(1)](https://user-images.githubusercontent.com/5291257/115655126-3324b480-a365-11eb-9223-ba83138c84c7.png)
I user Demo, package webgl,But Like the screenshots

**Comment by jdnichollsc** [comment]
I can see wrong values from your query string params, please share your code

**Comment by sd63534790** [comment]
oh sorry, I didn't look carefully,but use demo GetRquest,There's an error
![1619071618(1)](https://user-images.githubusercontent.com/5291257/115664413-5efb6680-a374-11eb-8f60-173bb75437c7.png)
![1619071659(1)](https://user-images.githubusercontent.com/5291257/115664418-5f93fd00-a374-11eb-8eaf-59296b377f71.png)

**Comment by sd63534790** [comment]
Access to XMLHttpRequest at 'http://localhost:8088/spms-ibms-api/web/authentication/login' from origin 'http://localhost:8087' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by jdnichollsc** [comment]
Did you enable CORS from your REST API? :)

**Comment by sd63534790** [comment]
Oh i know the problem, It's complex request, Send the options request, Server not configured,So CORS,But I don't konw why It's complex request

**Comment by jdnichollsc** [comment]
complex? you know, your WebGL project comes from another domain, that's why you need to enable CORS from Server :)
