### ISSUE TITLE
[bug] Post result comes empty

### ISSUE THREAD

**Issue by marcusx2** [proyecto26/RestClient#174]
When using Post method, the result comes empty, even though the request does work. I just can't inspect the result. Because of this, I had to use UnityWebRequest instead. If it helps anything, I used the BodyString option.

Unity 2020.3.0f1

**Comment by jdnichollsc** [comment]
Can you share a reproducible example please to be able to reproduce your issue?

**Comment by jdnichollsc** [comment]
Any pull request is welcome, thanks in advance! <3
