### ISSUE TITLE
Request return status code 0 and cUrl error 28

### ISSUE THREAD

**Issue by davidfio** [proyecto26/RestClient#176]
Hi everyone, since some weeks almost every request I do reproduce two results:

1) Everything is fine, status code 200 but I receive **Curl error 28: Operation timed out after 10000 milliseconds with 0 bytes receive** 
2) Request go inside the catch with status code 0 and no error body

Have anyone experienced this? I need to resolve this whatever it takes.

I'm using Unity 2020.3.3f1 and latest release of RestClient 2.6.1 of 11 June 2020

**Comment by jdnichollsc** [comment]
Can you share your code please?

**Comment by jdnichollsc** [comment]
Please attach a demo project to be able to reproduce your issue, thanks for your help!
