### ISSUE TITLE
Consume primitive type directly

### ISSUE THREAD

**Issue by maifeeulasad** [proyecto26/RestClient#180]
Like I've an API, that returns some `int` or `string` directly. Then I can't use those API directly here. I need to make some changes on the backend and then consume it as a JSON object.

And all primitives are valid JSON, as per JSON grammar.

If this is something that can/should be implemented, you guys can count me in.

Thanks.

**Comment by jdnichollsc** [comment]
Ohh can you share your code please? Any pull request is welcome! 👍
