### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sainsjas** [proyecto26/RestClient#186]
I am facing this error when i am running my game on ios device, In Unity Editor its working fine.

Autoconnected Player NullReferenceException: Object reference not set to an instance of an object.
  at Sweep.APIManager+<>cDisplayClass3_0`1[T].<Request>b0 (Proyecto26.RequestException err, Proyecto26.ResponseHelper res, T data) [0x00000] in <00000000000000000000000000000000>:0 
  at Proyecto26.HttpBase+<>cDisplayClass5_0`1[TResponse].<DefaultUnityWebRequest>b0 (Proyecto26.RequestException err, Proyecto26.ResponseHelper res) [0x00000] in <00000000000000000000000000000000>:0 
  at Proyecto26.HttpBase+<CreateRequestAndRetry>d__0.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by jdnichollsc** [comment]
Hello @sainsjas, hope you're doing well

Can you share your code please?

Best,
Juan

**Comment by sainsjas** [comment]
internal class APIManager : MonoBehaviour
    {

        public static APIManager instance = null;

        void Awake()
        {

            if (instance != null && instance != this)
            {
                Destroy(this.gameObject);
            }
            else
            {
                instance = this;
            }
        }

        [SerializeField] GameObject loader;


        public static void Request<T>(RequestHelper request, Action<RequestException, ResponseHelper, T> callback, bool loaderNeeded = false)
        {
            Debug.Log("Requesting------");
            if (loaderNeeded)
            {
                APIManager.instance.loader.SetActive(true);
            }


            RestClient.Request<T>(request, callback: (err, res, data) =>
             {
                 Debug.Log("Response---------");
                 Debug.Log(res.Text);

                 var values = JsonConvert.DeserializeObject<Dictionary<string, object>>(res.Text);

                 int statusCode = Convert.ToInt16(values["statusCode"]);
                 string message = (string)values["message"];

                 APIManager.instance.loader.SetActive(false);

                 switch (statusCode)
                 {

                     case 200:
                     case 201:

                         callback(err, res, data);
                         Debug.Log("Message--------" + message);
                         break;

                     case 401:

                         GameUIManager.instance.ResetData();
                         ToastManager.instance.showToast(message);
                         Debug.Log("Unauthorized--------" + message);
                         break;

                     case 400:
                     case 404:
                     case 409:
                     case 500:

                         RequestException ex = new RequestException(message);

                         ToastManager.instance.showToast(message);

                         Debug.Log("Error--------" + message);
                         callback(ex, res, data);
                         break;

                 }

                 if (err != null)
                 {
                     Debug.Log("Error--------" + err.Message);

                 }

             });

        }

    }
    
    
    @jdnichollsc Please check this is my api request class, This error happens only in case if array is coming from server.

**Comment by sainsjas** [comment]
<img width="928" alt="Screenshot 2021-08-24 at 6 17 04 AM" src="https://user-images.githubusercontent.com/80745038/130537802-084902e7-6f10-4651-8c71-9cde062192a0.png">

@jdnichollsc These are the two errors on api request, you can check in screenshot

**Comment by sainsjas** [comment]
@jdnichollsc Its resolved, I was sending data in body in get type api that's why its creating issue.

**Comment by jdnichollsc** [comment]
Thanks for letting me know! ❤️
