### ISSUE TITLE
How can I use this asset to fetch data from Firebase?

### ISSUE THREAD

**Issue by geekyJock8** [proyecto26/RestClient#19]
I was trying to use firebase's asset to when a ran into this error [WebSocket: ws_0 - could not connect](https://github.com/firebase/quickstart-unity/issues/106) and I was redirected here from that page.
I read your instruction and sample code but none of them showed how to integrate with firebase. Any help would be appreciated!

**Comment by jdnichollsc** [comment]
WebSockets? This package is for HTTP requests...

**Comment by jdnichollsc** [comment]
@mirzasohailbaig but in your link you have different endpoints that you can call with this library, check the readme to learn how you can use it
