### ISSUE TITLE
stuck trying to implement JSON nested array

### ISSUE THREAD

**Issue by MrPatrickHenry** [proyecto26/RestClient#192]
This plugin should be part of Unity. way you guys have this seems familiar to other languages for calling restful apis.

one thing I can't seem to do is get it to work with a nested array.
if my json is at the first level then it's ok

Is this a shortfall on jsonUtility or am i missing something?
sample of my work
call this url :https://badwolf.com/api/v1/system like so
I couldn't also see how to debug.log the response 

` 

  [Serializable]
  public class BusinessData
  {
    public string key1;
    public saveIt[] SystemObjects;
  }

[Serializable]
public class SystemObjectskey4
{
    public string url;
}

 public void Get(){

  RestClient.DefaultRequestHeaders["Authorization"] = BearerKey;
  RestClient.DefaultRequestHeaders["Ocp-Apim-Subscription-Key"] = Key;
  RequestHelper requestOptions = null;  
  RestClient.Get<BusinessData>(basePath + "work/" + engagementID).Then(response => {
  jsonString = JsonUtility.ToJson(response, true);
  JSONNode itemsData = JSON.Parse(jsonString);
  BusinessData workspace = JsonUtility.FromJson<BusinessData>(jsonString);
  w_Object.text = workspace.name;
  endData_Object.text = "End Date: " + workspace.endDate;

  }).Catch(err => {
  EditorUtility.DisplayDialog ("Error", err.Message, "Ok");
});

 }
`

`{
  "ID": null,
  "Key1": "",
  "SystemErrors": [
    {
      "commonDataModel": "Unable to get access token for common data model integration"
    }
  ],
  "SystemObjects": {
    "SystemObjectskey1": {
      "status": "Completed",
      "url": "https://xxxxxx"
    },
    "SystemObjectskey2": {
      "status": "Failed"
    },
    "SystemObjectskey3": {
      "featureInstanceId": "c96b7e21-dabe-4b68-9565-74a5cfbbe0df",
      "provisionStage": "Initialize",
      "status": "In Progress"
    },
    "SystemObjectskey4": {
      "featureInstanceId": "ecdeddf5-12f9-40a3-a57d-ee562be21fa4",
      "provisionStage": "Completed",
      "status": "Completed",
      "url": "https://xxx"
    },
    "SystemObjectskey5": {
      "featureInstanceId": "b3808396-eaec-4eb5-b1f8-d9153e088115",
      "groupId": "f16362db-fa99-4784-9a2d-7ec661d09de0",
      "provisionStage": "Completed",
      "reportConfigStatus": {
        "5466e66c-d9cc-4f65-8a76-4817d576d177": "Completed",
        "86110f66-3cf5-42d3-b8d2-792e5cf44738": "Completed",
        "aa92d984-f59a-4652-8680-33bd7ffda42d": "Completed",
        "ad0a2fa7-c986-4875-9628-3a51cc1939fa": "Completed",
        "af53571a-1ab3-46d7-83e1-cad08b2a8637": "Completed"
      },
      "status": "Completed",
      "url": "https://xxxxxx"
    },
    "SystemObjectskey6": {
      "driveUrl": "",
      "guid": "03faa9a5-b5bf-4177-867d-1cbe8b4dd632",
      "status": "Completed",
      "url": "https://xxxxxxxxxxx",
      "workspaceStatus": false
    },
    "SystemObjectskey7": {
      "driveId": "b!GBKQ2uxNckSYm6GP3id6IKKJVyetWW1ImP6oF7BKGV5Di4nHtEsWTLApj4RV-8-8",
      "folderId": "01XEBX5IW5IXAHDUXLXJG34VND33DNPD2G",
      "folderUrl": "https://xxxxxxxx",
      "siteId": "xxxxxx",
      "siteUrl": "xxxxxxxxx"
    },
    "SystemObjectskey8": {
      "featureInstanceId": "33a8fd5e-ffbd-490e-8cb1-7a27447966f3",
      "provisionStage": "Completed",
      "status": "Completed",
      "url": "https://xxxxxxx"
    }
  },
  "details": "value",
  "issues": false,
  "lookup": "business",
  "name": "sample",
  "projectMgmtSysData": {
    "projMgmtSys": "System Native"
  }
}

**Comment by jdnichollsc** [comment]
Hello mate, hope you're doing well

Did you try another alternative instead of using **JsonUtility**? It's very limited as far as I know, also check our example here: https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/Helpers/JsonHelper.cs

Maybe you can add some logic here to be able to work with nested arrays, hope this can help you!

Best,
Juan
