### ISSUE TITLE
Json.NET support?

### ISSUE THREAD

**Issue by P-Why** [proyecto26/RestClient#194]
Is it possible to use Json.NET instead of JsonUtility for JSON de/serialization?
In the README, it is said that "other tools are supported".

Great lib btw

Thanks!

**Comment by jdnichollsc** [comment]
Hello mate, hope you're doing well

Oh yes, you can use any other library and send that JSON using BodyString option, please let me know if you have any error!

Best,
Juan

**Comment by P-Why** [comment]
Thank you for your response, that helps a lot

What about the deserialization when receiving JSON in an HTTP response?

**Comment by jdnichollsc** [comment]
That's already supported by the library, please share your code if you have any issue :)

**Comment by victornor** [comment]
I can't find documentation for this anywhere. 
Would you mind elaborating on how to specify which library to use for deserialization?
