### ISSUE TITLE
Foo, Bar

### ISSUE THREAD

**Issue by Droptable9** [proyecto26/RestClient#2]
I only started learning about JSON maybe 2 weeks ago so this has been a great learning curve for me, still working on deserializing this but will get it soon i hope.

just one question, where does foo and bar fit into this ?

![foobar](https://user-images.githubusercontent.com/33234011/32252562-08746572-beea-11e7-8c6c-d26d28a966ae.jpg)

**Comment by jdnichollsc** [comment]
**2 Questions:**
1. What data do you want to send to the server?
2. What data do you expect to receive from the server?

**Comment by Droptable9** [comment]
so do you mean title = "foo" is a question of what data it is sending to the server and body = "bar" is what type of data to receive from the server. foo and bar being in  "" is saying  that the type of data is between "s ?

**Comment by jdnichollsc** [comment]
No, for example... I want to send my **firstName** and **lastName** to the server and I want to receive a message with the **date** of creation of the new register and the **id**, so my jSONs of example are:
**JSON sent to the server (Request)**
```
{
  "firstName": "Juan David",
  "lastName": "Nicholls Cardona"
}
```
**JSON received from the server (Response)**
```
{
  "id": "111",
  "date": "2017-10-31T23:31:10.229Z"
}
```
And I want to send the data using a PUT request, so the code is the following:
```
[Serializable]
public class ServerResponse{
  public string id;
  public DateTime date;
}
// code code code...
RestClient.Put<ServerResponse>("www.nicholls.co/myendpoint", new {
  firstName = "Juan David",
  lastName = "Nicholls Cardona"
}).Then(response => {
  EditorUtility.DisplayDialog("ID: ", response.id, "Ok");
  EditorUtility.DisplayDialog("Date: ", response.date.ToString(), "Ok");
});
```

Best regards, Nicholls

**Comment by Droptable9** [comment]
ok great, Thanks Nicholls

**Comment by jdnichollsc** [comment]
@Droptable9 after reviewing with NodeJS as the Backend, we can't send anonymous objects, a **Serializable** class is required. Example:
```
[Serializable]
public class ServerResponse {
  public string id;
  public DateTime date;
}
[Serializable]
public class User {
  public string firstName;
  public string lastName;
}
RestClient.Post<ServerResponse>("www.myapi.com/myendpoint", new User {
  firstName = "Juan David",
  lastName = "Nicholls Cardona"
}).Then(response => {
  EditorUtility.DisplayDialog("ID: ", response.id, "Ok");
  EditorUtility.DisplayDialog("Date: ", response.date.ToString(), "Ok");
});
```

Best regards, Nicholls
