### ISSUE TITLE
Problem in install with .meta file 

### ISSUE THREAD

**Issue by Vaxela** [proyecto26/RestClient#202]
After following the step to install from UPM I receive lot's of error for exemple : 

Asset Packages/com.proyecto26.restclient/Sample has no meta file, but it's in an immutable folder. The asset will be ignored.

Asset Packages/com.proyecto26.restclient/Properties has no meta file, but it's in an immutable folder. The asset will be ignored.
UnityEditor.AssetDatabase:Refresh ()
Packages.Rider.Editor.RiderScriptEditor:SyncAll () (at Library/PackageCache/com.unity.ide.rider@2.0.7/Rider/Editor/RiderScriptEditor.cs:273)
System.Reflection.MethodBase:Invoke (object,object[])
JetBrains.Rider.Unity.Editor.UnityUtils:SyncSolution ()
JetBrains.Rider.Unity.Editor.PluginEntryPoint/<>c__DisplayClass33_0:<AdviseRefresh>b__2 ()
JetBrains.Rider.Unity.Editor.MainThreadDispatcher:Queue (System.Action)
JetBrains.Rider.Unity.Editor.PluginEntryPoint/<>c:<AdviseRefresh>b__33_0 (JetBrains.Lifetimes.Lifetime,JetBrains.Rider.Model.Unity.BackendUnity.RefreshType)
JetBrains.Rd.Tasks.RdCall`2<JetBrains.Rider.Model.Unity.BackendUnity.RefreshType, JetBrains.Core.Unit>:OnWireReceived (JetBrains.Serialization.UnsafeReader)
JetBrains.Rd.Impl.MessageBroker:Execute (JetBrains.Rd.Base.IRdWireable,byte[])
JetBrains.Rd.Impl.MessageBroker/<>c__DisplayClass8_0:<Invoke>b__0 ()
JetBrains.Rider.Unity.Editor.MainThreadDispatcher:DispatchTasks ()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

Do you have clue ?

**Comment by jdnichollsc** [comment]
Are you installing the lib using `upm` branch? I don't see `Properties` folder from [that branch](https://github.com/proyecto26/RestClient/tree/upm)

Check the instructions here: https://github.com/proyecto26/RestClient/tree/upm#upm-package

Please let me know! <3

**Comment by jdnichollsc** [comment]
Please try latest changes and let us know, thanks for your collaboration! <3

**Comment by heath3n** [comment]
@jdnichollsc This is still a problem. I just installed through UPM using the URL `https://github.com/proyecto26/RestClient.git#upm`. I get 50+ errors (non-blocking of course but they constantly spam the console which makes it unusable).

```
Asset Packages/com.proyecto26.restclient/CHANGELOG.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.proyecto26.restclient/CONTRIBUTING.md has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.proyecto26.restclient/Docs has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.proyecto26.restclient/Docs/RestClient.docx has no meta file, but it's in an immutable folder. The asset will be ignored.
Asset Packages/com.proyecto26.restclient/Docs/RestClient.pages has no meta file, but it's in an immutable folder. The asset will be ignored.
...
```

**Comment by jdnichollsc** [comment]
@heath3n Hey mate, do you know if we can generate these meta files from CLI with GitHub actions? 🤔

**Comment by heath3n** [comment]
I'm not really sure. I know that from [this post](https://forum.unity.com/threads/how-to-generate-meta-file-by-dll-file.854770/#post-5832586) by a Unity employee, it should be possible to generate the files from the CLI:

> I would suggest that you don't craft the meta files yourself, but instead rely on Unity to do this. It can be automated by a small CLI script like you're thinking of: just launch Unity in batch mode against a fake empty project that contains your package in it (`-batchmode -quit -projectpath <absolute-path-to-project>`), to make it import and generate the files with the proper format.

The problem is accessing an instance of Unity from GitHub Actions. I found [this Action](https://github.com/marketplace/actions/unity-builder) that purports to let you build a Unity project so I assume they have the engine up on a VM somewhere. I don't know if anything is exposed that can help us though.
