### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by TheSeanLavery** [proyecto26/RestClient#207]
I'm able to get valid responses from some endpoints on a server, but with other endpoints those are returning 400 Bad request.

I've tested those endpoints with Swagger and CURL, and its working just fine there.

Someone on the backend team said it looks like the body I'm sending might not be valid JSON.

How could I go about debugging this and seeing what I'm sending over in the body?

**Comment by TheSeanLavery** [comment]
It looks like if any body being sent over will cause this error on specific endpoints.

Is there a way to send an empty body?

**Comment by jdnichollsc** [comment]
Please attach your code to be able to reproduce your issue 🙂

**Comment by noname77** [comment]
hey, I think I'm seeing a similar issue.
running the latest RestClient release (2.6.2) and a flask with [flask-restplus](https://github.com/noirbizarre/flask-restplus) backend server

for me, the issue seems to be with flask (restplus) arguments parser. I managed to set up a 'minimal' example, but now after writing it down I'm wondering if this is due to old versions of Werkzeug (0.16.1) and flask (1.1.1). Either way, things work fine when I test the server from a web browser or curl, but not when using RestClient

server (python) code:
`test.py`
```
import traceback
from flask import Flask, Blueprint
from flask_restplus import Resource, Api, Namespace


app = Flask(__name__)

blueprint = Blueprint('api', __name__)

api = Api(blueprint,
    title='Test API',
    version='0.1',
    description='Test API tests stuff.',
    doc='/docs'
)

ns1 = Namespace('', description='Root endpoint')

api.add_namespace(ns1, path='/')

app.register_blueprint(blueprint, url_prefix='/api/v1')

test_parser = api.parser()
test_parser.add_argument('arg1', type=str)
test_parser.add_argument('arg2', type=str)

@api.route('/test')
class Test(Resource):
    @api.expect(test_parser)

    def get(self):
        print("[DEBUG] test endpoint called")
        try:
            params = test_parser.parse_args()
        except Exception as e:
            print("[WARN] Exception during params parsing: " + str(e))
            print(traceback.format_exc())

            raise

        print("[DEBUG] args parsed")

        return {'arg1': params['arg1'], 'arg2': params['arg2']}, 200

if __name__ == "__main__":

    print('[DEBUG] flask app started.')

    app.run()
```

to run the server create an empty directory, create the test.py file like above and run:
```
python3 -m venv env
. env/bin/activate
python -m pip install Werkzeug==0.16.1 flask==1.1.1 flask-restplus
python test.py
```

c# code:
```
        public void RunTest()
        {
            var baseUrl = "http://127.0.0.1:5000";
            var requestPath = "/api/v1/test";

            var requestUrl = String.Format("{0}{1}", baseUrl, requestPath);
            var requestParams = new Dictionary<string, string>()
            {
                { "arg1", "hello" },
                { "arg2", "world" }
            };

            var request = new RequestHelper
            {
                Uri = requestUrl,
                Params = requestParams
            };

            var context = new LogContext().Add(() => request.Uri, () => request.Params);
            UnityEngine.Debug.Log(String.Format("GET: {0}", context));

            RestClient.Get(request).Then(response =>
            {
                UnityEngine.Debug.Log(String.Format("GET response: {0}", response.StatusCode));
            }).Catch(err =>
                {
                    var error = err as RequestException;

                    UnityEngine.Debug.Log(String.Format(
                        "GET error: {0}, {1}", error.StatusCode, error.Response));
                });
        }
```


When visiting the url from the browser: "http://127.0.0.1:5000/api/v1/test?arg1=hello&arg2=world", I'm receiving the expected:
```
{"arg1": "hello", "arg2": "world"}
```

same happens when I go to the swagger docs "http://127.0.0.1:5000/api/v1/docs" and run it from there
![image](https://user-images.githubusercontent.com/5903414/150533804-6fb95f4b-95a7-4c2f-9b82-ab7338dc2b34.png)

and also the same, when running directly with curl:
```
% curl -X GET "http://127.0.0.1:5000/api/v1/test?arg1=hello&arg2=world" -H "accept: application/json"
{"arg1": "hello", "arg2": "world"}
```

However, when calling the `RunTest()` method which uses RestClient, I'm getting:
`400` with an exception from werkzeug. logs from the server after running all requests:
```
% python test.py
[DEBUG] flask app started.
 * Serving Flask app "test" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)



[DEBUG] test endpoint called
[DEBUG] args parsed
127.0.0.1 - - [21/Jan/2022 14:37:54] "GET /api/v1/test?arg1=hello&arg2=world HTTP/1.1" 200 -

[DEBUG] test endpoint called
[DEBUG] args parsed
127.0.0.1 - - [21/Jan/2022 14:38:04] "GET /api/v1/test?arg1=hello&arg2=world HTTP/1.1" 200 -

[DEBUG] test endpoint called
[DEBUG] args parsed
127.0.0.1 - - [21/Jan/2022 14:38:22] "GET /api/v1/test?arg1=hello&arg2=world HTTP/1.1" 200 -

[DEBUG] test endpoint called
[WARN] Exception during params parsing: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 119, in get_json
    rv = self.json_module.loads(data)
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/flask/json/__init__.py", line 253, in loads
    return _json.loads(s, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 34, in get
    params = test_parser.parse_args()
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/flask_restplus/reqparse.py", line 360, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/flask_restplus/reqparse.py", line 199, in parse
    source = self.source(request)
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/flask_restplus/reqparse.py", line 135, in source
    value = getattr(request, l, None)
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 69, in json
    return self.get_json()
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 128, in get_json
    rv = self.on_json_loading_failed(e)
  File "<PROJECT_PATH>/env/lib/python3.8/site-packages/flask/wrappers.py", line 27, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

127.0.0.1 - - [21/Jan/2022 14:38:29] "GET /api/v1/test?arg1=hello&arg2=world HTTP/1.1" 400 -
```

best,
wiktor

**Comment by jdnichollsc** [comment]
I'm not sure why you're using **Body** for a **GET** request here, that makes no sense 🤔

**Comment by TheSeanLavery** [comment]
``@jdnichollsc If there is no body defined, it seems to send over a malformed body?

The standard usage examples are giving me issues.
Able to use standard Unity WebRequest, or curl work fine for this endpoint.

Here is a small example snippet:

`void GetFleetMetrics()
    {
        var deviceName = DeviceType.ToString();
        var fleetName = FleetType.ToString();
        RestClient.Get(Endpoints.FormatURLDeviceFleet(Endpoints.fleet_metrics, deviceName, fleetName)).Then(res =>
        {
            EditorUtility.DisplayDialog("Response", res.Text, "OK");
        }).Catch(err =>
        {
            EditorUtility.DisplayDialog("Error", err.Message, "Ok");
        });
    }`

**Comment by jdnichollsc** [comment]
It looks like an issue from that external python lib because we don't expect a body from a GET request :)

**Comment by TheSeanLavery** [comment]
@jdnichollsc I don't expect a body from a GET request either.

I think this library is adding a malformed body. I can send this via curl with no body and it works fine.

Could you reopen this issue? I don't think this is a problem with an external python lib.

**Comment by jdnichollsc** [comment]
Please attach a reproducible demo or project repository to be able to debug the error, then I can reopen this issue :)

**Comment by TheSeanLavery** [comment]
@noname77 Would you be willing to create a repo for that little test project? Or if you don't want to. Could I?

I'd really like to get this issue solved.

**Comment by TheSeanLavery** [comment]
@jdnichollsc 

noname77 attached sample python based server and a test script above. Does that work?

**Comment by jdnichollsc** [comment]
I don't have experience with Python for Rest APIs, please let me know the commands to run the server 🙂

**Comment by noname77** [comment]
> Try using Content Type header instead and please let me know 👍

thanks, I did that and it fixed my issue. I think by default `application/json` is used which was causing issues on the backend server side, even for the **GET** request with an **empty** body.

I now use `text/html` for **GET** and the default `application/json` only for **POST** requests.

@TheSeanLavery, I'm pretty busy recently so not sure when would I get around to setting up a repo.
since things are working as expected for me now, feel free to do so with the files I posted
