### ISSUE TITLE
RestClient.Put function doesnt work to set string variable in an object 

### ISSUE THREAD

**Issue by ama9999** [proyecto26/RestClient#208]
I'm new to RestClient   and data read and write on Firebase. I have a problem as below
I would like to change the variable that is string in an object, but it doesn't work(name)
I can change the variable in the same object that is integer.(tel,tax number)

![image2](https://user-images.githubusercontent.com/82452000/152774716-db329dd7-00a7-455d-809f-3b5e9775bad5.png)

Is there a problem with the way I use it or is there a different way of using it?

**Comment by jdnichollsc** [comment]
I'm not sure, please share your code and provide a reproducible demo to be able to debug your issue 👍

**Comment by ama9999** [comment]
thank you for your attention :)

public class Center 
{
    public string id;
    public string name;
    public string email;
    public string password;
    public string taxNumber;
    public string taxAdministration;
    public string adress;
    public string tel;
}
Note:
Since all centers taxnumber variable is special under "Centers" in firebase database, this variable is set under it.

RestClient.Put(realtimedatabaseURL + "/Centers/" + taxNumber + "/tel" + ".json?auth=" + firebaseAuthentication.idToken, telEditInput.text); **(Update  string that contains only  numbers)**

RestClient.Put(realtimedatabaseURL + "/Centers/" + taxNumber + "/name" + ".json?auth=" + firebaseAuthentication.idToken, nameEditInput.text); **(not Update string )**

I hope this example was enough to explain my problem :)

**Comment by jdnichollsc** [comment]
Hello mate, what answer is the server giving you? Can you share the logs of the responde please?

**Comment by ama9999** [comment]
no errors and no logs it just doesn't update the variable  :( very interesting, it sets when one of the two variables at the same level and with the same method is only a number, but it does not set the string structure with variables other than numbers and there is no error code.
I was wondering if I am using it wrong because I am new in this field, but it is really interesting that it works in one and not in the other :)

**Comment by jdnichollsc** [comment]
Hey mate, did you try using another ContentType for the request? We're using `application/json` as default

Please let me know!
