### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by arashrasoulzadeh** [proyecto26/RestClient#21]
hi , i use the following code : 
` var  promise=RestClient.Post<Menu_LoginModel>(url, loginModel).Then(response => {
            print("done");
        }).Catch(err => EditorUtility.DisplayDialog("Error", err.Message, "Ok"));
`

but its not working ,nothing happes

**Comment by jdnichollsc** [comment]
Can you attach the class of your loginModel? By other hand, can you attach a screenshot of the response of the server using Postman or some like that?

**Comment by arashrasoulzadeh** [comment]
hi 
even get request sample from your documentation is not working 
im on mac os mojave

**Comment by jdnichollsc** [comment]
I'm on Mac too and the example is working very well... so, without code of example I can't help you... Please, attach all your code to reopen this issue

**Comment by jdnichollsc** [comment]
Check the GET request...

<img width="662" alt="captura de pantalla 2018-06-11 a la s 10 59 43 a m" src="https://user-images.githubusercontent.com/2154886/41242989-ad532896-6d66-11e8-84c4-42e9371c68b8.png">

What version of Unity are you using?
What's the response of the server?
Do you need to convert the response of the server using the **Menu_LoginModel**? Can you attach the code of that class?
Can you try using the generic method with a timeout?
