### ISSUE TITLE
404 Error when using DELETE

### ISSUE THREAD

**Issue by CZHach** [proyecto26/RestClient#213]
Hi, when I try to delete an object via my API that doesn't exist, I get a 404 error.  Shouldn't the RestClient library handle this?

Here is my code:
`
RestClient.Delete("gamerConnection/api/UserGames/" + GameId).Done(res => Debug.Log("DELETE GameData...."));`

**Comment by jdnichollsc** [comment]
That should be handled from your API, if you want to ignore an error here you can use the `IgnoreHttpException` option, but I don't see an issue here 🤔

**Comment by CZHach** [comment]
@jdnichollsc  Ok thanks, I don't manage the API but I was worried that my Unity c# code was wrong because it doesn't match the example here:

```
RestClient.Delete("https://jsonplaceholder.typicode.com/posts/1").Then(response => {
  EditorUtility.DisplayDialog("Status", response.StatusCode.ToString(), "Ok");
});
```

**Comment by jdnichollsc** [comment]
Sure, that's the expected behavior, thanks for reporting this issue! <3
