### ISSUE TITLE
can not debug anything/not getting any debugs in console after adding this package

### ISSUE THREAD

**Issue by devSyed72** [proyecto26/RestClient#215]
using unity 2020.3.31
after this package, i dont recieve any debug.log,logerror,logwarning from any script attatched to gameobject in editor. i have debugs enables in console window but still cant get. as soon as i delete this package, i start getting debugs. please help

**Comment by jdnichollsc** [comment]
Hey mate, thanks for reporting this issue

How are you installing this library?
Please let us know! ❤️
