### ISSUE TITLE
Unable to run in Editor

### ISSUE THREAD

**Issue by Kmess** [proyecto26/RestClient#22]
It looks like it only supports runtime operations, anyway to support in editor requests?

**Comment by jdnichollsc** [comment]
editor requests? what's that? I'm learning Unity haha

**Comment by madeeliqbal** [comment]
Not sure but it seems like a Same problem. 
I am beginner in programming that’s why bit stuck. And the Error is  
Assets\RestClient\DemoScene\Scripts\MainScript.cs(23,13): error CS0103: The name 'EditorUtility' does not exist in the current context
 
As of I know about the error : Editor Utility is not supporting the display dialog I guess and if want to display the result on a specific Text box game object how to do it. If you could help me out that would be amazing.

**Comment by madeeliqbal** [comment]
![button](https://user-images.githubusercontent.com/12182028/41536407-d33a503a-7305-11e8-885f-6f37ce3c006c.png)

So this button should be called and display should be available on the UI TEXT PREFAB but Editor Utility is allowing right now to display on Unity UI but not allowing on Holographic buttons. 


how can make change it from Unity UI to Holographic Buttons

**Comment by jdnichollsc** [comment]
@madeeliqbal you can remove the demo to fix the issues about EditorUtility references...
