### ISSUE TITLE
Can this library be called by hololens2

### ISSUE THREAD

**Issue by songguanqing** [proyecto26/RestClient#223]
Can this library be called by hololens2

**Comment by jdnichollsc** [comment]
Did you try? Are you getting an error?

**Comment by maifeeulasad** [comment]
It'll be great.

It's an open source library.

**Comment by jdnichollsc** [comment]
UnityWebRequest system is used by this lib internally, so it should work as well

**Comment by songguanqing** [comment]
If I want to use this library in hololens2, I need to compile the version of the arm architecture under the windows platform
