### ISSUE TITLE
change from Editor Utility to GameObject 

### ISSUE THREAD

**Issue by madeeliqbal** [proyecto26/RestClient#23]
![button](https://user-images.githubusercontent.com/12182028/41540096-ab9f0502-730f-11e8-99ff-59d961db0522.png)

Not sure but it seems like a Same problem.
I am beginner in programming that’s why bit stuck. And the Error is
Assets\RestClient\DemoScene\Scripts\MainScript.cs(23,13): error CS0103: The name 'EditorUtility' does not exist in the current context

As of I know about the error : Editor Utility is not supporting the display dialog I guess and if want to display the result on a specific Text box game object how to do it. If you could help me out that would be amazing.

And i am using Holographic buttons in my project and on the Click event i am calling REST apis (Only GET for time being). I want to call from my button and result should be available on the UI TEXT prefab (Microsoft provided interactable objects ) So how should i point it to my GameObject (UITextPrefab) rather than Unity UI. Editor Uitlity is not allowing me to display and click event should be HolographicButton.

**Comment by jdnichollsc** [comment]
@madeeliqbal You can remove the **DemoScene** folder, it's only an example about this plugin.
Check the [README](https://github.com/proyecto26/RestClient/blob/master/README.md) to know how you can create GET Requests 👍
