### ISSUE TITLE
Can i use this asset to make my offline game multiplayer?

### ISSUE THREAD

**Issue by REFFER69** [proyecto26/RestClient#234]
Please let me know if and how this asset can help or if there is another asset that might be more "Turnkey" in adding multiplayer?

My game is a Trivia Game
https://play.google.com/store/apps/details?id=com.GamersQuest.TwentyQuestionsTriviaGame

**Comment by maifeeulasad** [comment]
>>**This is just a rest client.**

It has nothing to do with online ya offline; if you are connected to some player's hotspot, and that guy has a server running, then you can call APIs with it.

*Running server on Android drains the battery, personal experience. But indeed can be done. You will surely find some GitHub repos, or write from very scratch. If you are writing from scratch try C++ (with NDK)*
