### ISSUE TITLE
Default seralizer JsonUtility cannot serialize records

### ISSUE THREAD

**Issue by okankayhan** [proyecto26/RestClient#235]
`record LinkRequest(string game_service_id)`

Below code works fine since I serialize myself with Json.NET
```
RestClient.Post(new RequestHelper
            {
                Uri = linkUrl,
                BodyString = JsonConvert.SerializeObject(new LinkRequest(platformUserId))
            });
```

However below code sends out an empty body
```
RestClient.Post(linkUrl, new LinkRequest(platformUserId));
```

Currenty users of this library have to either avoid using records or give up on default serialization and use Json.NET. Would you consider changing the default serializer?

**Comment by jdnichollsc** [comment]
@okankayhan thanks for reporting this issue, we have that **BodyString** option to allow users to choose another serializer because we only use Unity SDK to make this library easier to maintain over time.

Thanks for understanding!
