### ISSUE TITLE
Why not async/await?

### ISSUE THREAD

**Issue by tomkail** [proyecto26/RestClient#236]
Hey! Bit new to async programming, and I was curious why this uses Promises rather than Async/Await?
My limited experience has shown async to work pretty well, avoid callback hell, and it works in edit mode which is nice.
Just curious!
Ta!

**Comment by maifeeulasad** [comment]
Why I don't want to use `async/await`:
 - I need to make the whole function `async`
 - promise handler gives me scope
 - `await` doesn't tell me if I'm getting an error or a result; but promise does with `catch` and `then`, respectively
 - I can wait for all promises, for few, or one; things like these
 - make the code more readable, manageable, scalable, and also strictly typed
 - it is cool

And break code into chunks. Always follow chunk over bulk. I don't know if it is a concept, pattern, or anything.

I'm going to close this issue now. But feel free to continue this thread.


-----------------

*And seriously, I'm so comfortable with `Promise` that, I never had the time to even check if our library supports `async/await` with `Promise` or not (Just like we do in JS/TS).*

**Comment by maifeeulasad** [comment]
Good read:
 - https://betterprogramming.pub/should-i-use-promises-or-async-await-126ab5c98789

I will try to put some more resources here. In case someone finds them helpful.

:beers: cheerio :beers:
