### ISSUE TITLE
Using RestClient as a dependency in a unity package

### ISSUE THREAD

**Issue by royibernthal** [proyecto26/RestClient#239]
Hi,

I'd like to use this RestClient package as a dependency in a new unity package I'm creating.

Is there any package name I can specify in the dependencies in package.json?

I'd ideally like to do it without Nuget for compatibility reasons.

Regards,
Royi

**Comment by jdnichollsc** [comment]
Please check the code of the repository, let me know if that works for you!
https://github.com/proyecto26/RestClient/blob/develop/src/Proyecto26.RestClient/package.json
