### ISSUE TITLE
Unable to complete SSL connection (iPhone)

### ISSUE THREAD

**Issue by gw1108** [proyecto26/RestClient#25]
On iOS I seem to get stuck while calling RestClient.get(Request helper).

The helper also has `helper.Timeout = 5000;`

After getting stuck for 3-5 minutes it'll properly give Unable to complete SSL connection message. Error code 0. Seems to be related to my Cellular Data. If it's on I'll get this problem. If Cellular Data is disabled or disabled just for my app I'll quickly get a No Internet Connection message. Shouldn't the timeout parameter make it quickly fail after 5000 milliseconds?

Also, the iPhone does not have a data plan even though you can enable Cellular Data.

**Comment by jdnichollsc** [comment]
@gw1108 Honestly, I don't know... the **timeout** is handled by the ** UnityWebRequest** object of Unity, so I have no control over that behavior, check the code here https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/Extensions.cs#L66

Let me know what you think, Nicholls

**Comment by gw1108** [comment]
Figured it out. Timeout is not milliseconds it's just seconds. Changing that to 15 fixed the issue more or less.

**Comment by jdnichollsc** [comment]
@gw1108 ohh thanks to share that, I thought that it was in milliseconds, it was my mistake 👍
