### ISSUE TITLE
POST is just a GET request?

### ISSUE THREAD

**Issue by hallsofvallhalla** [proyecto26/RestClient#252]
When I try to POST with Params it just sets them as a get request

```
 currentRequest = new RequestHelper
        {
            Uri = basePath + "/login.php",
            Params = new Dictionary<string, string> {
                { "username", Username.text },
                { "password", Password.text },
                 { "email", "" },
                 { "type", "2" }
            },
            EnableDebug = true
        };
        RestClient.Post<Post>(currentRequest)
        .Then(res => {

```

in Unity Debug it shows 

Url: https://mydomain.com/server/login.php?username=&password=&email=&type=2

Then I get a 500 error.

**Comment by hallsofvallhalla** [comment]
After a while of fooling with it I fixed the 500 error but I cannot get it to return data. I found another Asset that worked out of the box so going to use it. Thanks.

**Comment by lordexecutor** [comment]
What asset please
