### ISSUE TITLE
How to use UnityWebRequest to make REST requests in Unity?

### ISSUE THREAD

**Issue by castana1962** [proyecto26/RestClient#27]
Hi
I am interested in using UnityWebRequest to make REST requests to the Watson Machine Learning( this service is not included in the Watson SDK for Unity at the moment)
Since that Watson SDK for Unity does not support PUT operations( by RESTConnector class), I would need to create a new Class that use UnityWebRequest( this one support PUT operations) to make REST requests to the Watson Machine Learning service, for it, Could I use your Unity Plugin to do it?
Thanks for your time
Alejandro Castan

**Comment by jdnichollsc** [comment]
With this plugin you can make HTTP Requests... don't care the technology used to create the REST service, so you can make REST requests to the Watson Machine Learning service 👍

**Comment by castana1962** [comment]
Hi jdnichollsc 
So I will try it...
Thanks for your help !!!
Alejandro

**Comment by jdnichollsc** [comment]
@castana1962 any good comment from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501) would be really appreciated :)
