### ISSUE TITLE
Add Support for a specific DownloadHandler

### ISSUE THREAD

**Issue by rengaw83** [proyecto26/RestClient#28]
Currently for each `UnityWebRequest ` the `DownloadHandlerBuffer` are used.
See the [extension class](https://github.com/proyecto26/RestClient/blob/2.0.1/src/Proyecto26.RestClient/Utils/Extensions.cs#L47)

In my unity project i has to download large files (>100mb) to a file on the pc or device.

With the byte buffer download handler the whole content of the file was loaded into the ram and when the download was finished the content can be written to the local file.

For these large files it would be nice to set a download handler manualy to the RequestHelper like this:
```C#
string srcUri = "http://myapi/ressource/load/bigfile";
string destPah = Path.Combine(Application.persistentDataPath, "bigfile");

DownloadHandlerFile dh = new DownloadHandlerFile(destPah);
dh.removeFileOnAbort = true;

Proyecto26.RequestHelper request = new Proyecto26.RequestHelper()
    {
        Uri = srcUri,
        DownloadHelper = dh,
    }
;

Proyecto26.RestClient.Get(request)
    .Then(
        () => {
            Debug.Log("Downloaded to " + destPah);
        }
    )
    .Catch(
        err => {
            Debug.Log("Error during download:" + err);
        }
    )
;
```

In the extension class the options can be checked like this:
```C#
if (options.DownloadHelper is DownloadHandler)
    request.downloadHandler = options.DownloadHelper;
else
    request.downloadHandler = (DownloadHandler)new DownloadHandlerBuffer();
```

To add the download helper to the request helper the request helper needs to become the download helper property like this:
```C#
public class RequestHelper {
        public DownloadHandler DownloadHandler { get; set; }
}
```

There are a lot of useful download helpers out there. Like AssetBundle or Texture, ....

It wold be nice when you can add the support of a configurable download helper.

My currently workaround is to perform the web request by myself without your RestClient (without all the features and much more code).
```C#
public static RSG.IPromise LoadRessourceToFile(
    System.Uri url,
    string dest
)
{
    RSG.Promise promise = new RSG.Promise();

    UnityWebRequest request = new UnityWebRequest(url.AbsoluteUri, UnityWebRequest.kHttpVerbGET);

    DownloadHandlerFile dh = new DownloadHandlerFile(dest);
    dh.removeFileOnAbort = true;
    request.downloadHandler = dh;

    StartCoroutine(
        SendRequest(request, promise)
    );

    return promise;
}

private static System.Collections.IEnumerator SendRequest(
    UnityWebRequest request,
    RSG.Promise promise
)
{
    yield return request.SendWebRequest();

    if (request.isNetworkError || request.isHttpError)
        promise.Reject(new Exception(request.error));
    else
        promise.Resolve();

    yield break;
}
```

**Comment by jdnichollsc** [comment]
Done, thanks! 👍
