### ISSUE TITLE
Exception when DownloadHandlerFile are used

### ISSUE THREAD

**Issue by rengaw83** [proyecto26/RestClient#29]
In #28 you have add support for a specific DownloadHandler.
Thank you for the fast implementation!

I tried it out, unfortunately i missed a problem.

For whatever reason, the `UnityEngine.Networking.DownloadHandlerFile` throws a `NotSupportedException` for [GetData](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequest/Public/DownloadHandler/DownloadHandler.bindings.cs#L227) and [GetText](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequest/Public/DownloadHandler/DownloadHandler.bindings.cs#L232)

When i use the DownloadHandlerFile now, the [ResponseHelper](https://github.com/proyecto26/RestClient/blob/2.1.0/src/Proyecto26.RestClient/Utils/Extensions.cs#L77) tries to get the data and text from the DownloadHelper.  
This inevitably leads to the NotSupportedException.

I have checked all Unity build in Downloadhelpers.  
The following handlers throw an exception on data and/or text calls:

|       DownloadHelper         |                                                                                       GetData                                                                                         |                                                                                       GetText                                                                                        |
|------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DownloadHandlerAssetBundle   | [NotSupportedException](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequestAssetBundle/Public/DownloadHandlerAssetBundle.bindings.cs#L48)  | [NotSupportedException](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequestAssetBundle/Public/DownloadHandlerAssetBundle.bindings.cs#L53) |
| DownloadHandlerAudioClip     | returns byte[]                                                                                                                                                                        | [NotSupportedException](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequestAudio/Public/DownloadHandlerAudio.bindings.cs#L38)             |
| DownloadHandlerBuffer        | returns byte[]                                                                                                                                                                        | returns string                                                                                                                                                                       |
| DownloadHandlerFile          | [NotSupportedException](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequest/Public/DownloadHandler/DownloadHandler.bindings.cs#L227)       | [NotSupportedException](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequest/Public/DownloadHandler/DownloadHandler.bindings.cs#L232)      |
| DownloadHandlerMovieTexture  | returns byte[]                                                                                                                                                                        | [NotSupportedException](https://github.com/Unity-Technologies/UnityCsReference/blob/2018.2.4f1/Modules/UnityWebRequestAudio/Public/DownloadHandlerAudio.bindings.cs#L79)             |
| DownloadHandlerScript        | returns null                                                                                                                                                                          | returns string                                                                                                                                                                       |
| DownloadHandlerTexture       | returns null                                                                                                                                                                          | returns string                                                                                                                                                                       |

I can't see a interface or another way to find out if a download handler supports the properties.

So i think the fastest solution is to catch the exceptions like this:

```C#
public static Proyecto26.ResponseHelper CreateWebResponse(this UnityWebRequest request)
{
    byte[] data = null;
    try { data = request.downloadHandler.data; }
    catch (NotSupportedException) { }

    string text = "";
    try { text = request.downloadHandler.text; }
    catch (NotSupportedException) { }

    return new Proyecto26.ResponseHelper
    {
        StatusCode = request.responseCode,
        Data = data,
        Text = text,
        Headers = request.GetResponseHeaders(),
        Error = request.error
    };
}
```

Ore use a helper/wrapper/mapper for that like this:
```C#
class DownloadedData
{
	private DownloadHandler _downloadHandler;

	public byte[] data
	{
		get
		{
			try
			{
				return _downloadHandler.data;
			}
			catch (NotSupportedException)
			{
				return null;
			}
		}
	}

	public string text
	{
		get
		{
			try
			{
				return _downloadHandler.text;
			}
			catch (NotSupportedException)
			{
				return "";
			}
		}
	}

	public DownloadedData(DownloadHandler dh)
	{
		_downloadHandler = dh;
	}
}
```
```C#
public static ResponseHelper CreateWebResponse(this UnityWebRequest request)
{
	var responseData = new DownloadedData(request.downloadHandler);

	return new ResponseHelper
	{
		StatusCode = request.responseCode,
		Data = responseData.data,
		Text = responseData.text,
		Headers = request.GetResponseHeaders(),
		Error = request.error
	};
}
```

Can you fix the issue with a solution that is best for you, please?
Thanks a lot and sorry that i have not seen the problem sooner.

**Comment by jdnichollsc** [comment]
Ok, let me fix that issue tommorrow 😅

**Comment by rengaw83** [comment]
No hurry, I have family time this weekend :)

**Comment by jdnichollsc** [comment]
Done, check the version 2.1.1 from Nuget 👍

**Comment by jdnichollsc** [comment]
@rengaw83 any good comment from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501) would be really appreciated :)
