### ISSUE TITLE
TypeLoad Exception

### ISSUE THREAD

**Issue by devesh2605** [proyecto26/RestClient#3]
TypeLoadException: Could not load type 'UnityEngine.Networking.UnityWebRequestAsyncOperation' from assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jdnichollsc** [comment]
But what happen if you download the demo? it works? 🤔

**Comment by jdnichollsc** [comment]
what's the version of Unity you are using? What's your SO? 👍

**Comment by devesh2605** [comment]
Hello,

I am using Unity 5.6 and OS is Windows, I have even tried the same on OSX but same issues.

Thanks,
Devesh V

**Comment by jdnichollsc** [comment]
@diegoossa what version of Unity do you have installed in your Windows? I don't know if it's an issue with the path of the Unity dependency

**Comment by devesh2605** [comment]
@jdnichollsc I am using Unity 5.6, I do not think if it's an issue with path..

**Comment by jdnichollsc** [comment]
@devesh2605 Sorry, I was talking with Diego Ossa 👍 
Let me check this tomorrow

**Comment by devesh2605** [comment]
@jdnichollsc Hello, 

It's working with Unity 2017.2.0f3, but please look after Unity 5.6

**Comment by jdnichollsc** [comment]
@devesh2605 [UnityWebRequestAsyncOperation](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequestAsyncOperation.html) doesn't exist in that version of Unity

**Comment by jdnichollsc** [comment]
The `Send` method was deprecated:
- [UnityWebRequest.Send](https://docs.unity3d.com/560/Documentation/ScriptReference/Networking.UnityWebRequest.Send.html) (5.6)
- [UnityWebRequest.SendWebRequest](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.SendWebRequest.html) (2017.2)

Sorry my friend, but that method doesn't exist in the current version of Unity
