### ISSUE TITLE
Error making Android build: dll is not allowed to be included or could not be found.

### ISSUE THREAD

**Issue by fractalfrenzy** [proyecto26/RestClient#30]
I am getting this error attempting to make a build for Android:

> ArgumentException: The Assembly netstandard is referenced by RSG.Promise ('Assets/RestClient/Packages/RSG.Promise_netstandard.dll'). But the dll is not allowed to be included or could not be found.
> UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:155)
> UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:195)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I tried setting Api Compatibility Level to .NET 2.0 but to no avail. Thanks for your help.

**Comment by jdnichollsc** [comment]
@fractalfrenzy you only need the RSG.Promise_netstandard.dll to support UWP with DotNet Standard :)

**Comment by jlubeck** [comment]
Hey @jdnichollsc , what does that mean? "you only need the RSG.Promise_netstandard.dll to support UWP with .Net Standard :)"

**Comment by jdnichollsc** [comment]
@jlubeck the RSG.Promise library has 2 dlls, one of them to support UWP (HoloLens) with .Net Standard, and the other one for the rest of the platforms 😅

**Comment by richfuns** [comment]
> I resolved the issue. In case anyone has this trouble I solved by changing Scripting Runtime Version to .NET 4.x Equivalent under Configuration in Player Setting (Other Settings).

Works for me. Thanks

**Comment by jdnichollsc** [comment]
@jlubeck @richfuns thanks for report this, so the other option is by removing **RSG.Promise_netstandard.dll** if you don't want to support Universal Windows Platforms (HoloLens) 👍
