### ISSUE TITLE
RestClient.Post<ResultBean<PageBean2<Student>>>(currentRequest)  is not working.

### ISSUE THREAD

**Issue by richfuns** [proyecto26/RestClient#32]
`RequestHelper currentRequest = new RequestHelper
        {
            Uri = "",
            Body = new User
            {
            },
        };
        RestClient.Post<ResultBean<PageBean2<Bank>>>(currentRequest)
            .Then(res => { EditorUtility.DisplayDialog("Success", JsonUtility.ToJson(res, true), "Ok"); })
            .Catch(err => { EditorUtility.DisplayDialog("Error", JsonUtility.ToJson(err.Message, true), "Ok"); });`

Why this library can not parse response entity just like:  ResultBean<PageBean2<Bank>>

But if I use ResultBean<PageBean2>, the data can be parsed smoothly.

Please help me. 
Thank you all.

**Comment by jdnichollsc** [comment]
@richfuns this library is using the `JsonUtility` class of **Unity**, if you want you can use other tools to deserialize the response of the server 👍

**Comment by richfuns** [comment]
@jdnichollsc  Thanks friend
But I think you did not answer the question clearly. 
"This library is using the JsonUtility " Is that means this library can not parse the response data structure like: 
RestClient.Post<ResultBean<PageBean2<Bank>>>(currentRequest)

Am I correct? 

If not, how could I change deserialize tools to others?  Rewrite this library or something? 

Look forward to your replying.
thanks.

**Comment by jdnichollsc** [comment]
@richfuns this library is only a wrapper to improve the code to make http requests, what library do you want to use to parse the response? I can attach an example with the tool you want to use to deserialize the JSON :)

**Comment by jdnichollsc** [comment]
If you want to use other JSON library, you need to modify the code to use the ResponseHelper class: https://github.com/proyecto26/RestClient/issues/31#issuecomment-417841544

In the previous example you can replace the JsonUtility class of Unity to user a third party library instead :)

**Comment by richfuns** [comment]
@jdnichollsc  ok  thanks friend
