### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by Elvishrdz** [proyecto26/RestClient#33]
i just open the demo in Unity 5.6.6f2 and when i click each button show me this error:

MissingMethodException: Method not found: 'UnityEngine.Networking.UnityWebRequest.get_isHttpError'.
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Proyecto26.StaticCoroutine:StartCoroutine(IEnumerator)
Proyecto26.RestClient:Request(RequestHelper, Action`3)
Proyecto26.RestClient:Post(RequestHelper, Action`3)
Proyecto26.RestClient:Post(RequestHelper)
Proyecto26.RestClient:Post(String, Object)
MainScript:Post() (at Assets/MainScript.cs:47)
UnityEngine.EventSystems.EventSystem:Update()

![captura](https://user-images.githubusercontent.com/11337143/46160514-26d52b00-c240-11e8-99f6-2f8b95c031aa.PNG)

**Comment by jdnichollsc** [comment]
@Elvishrdz any good comment from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501) would be really appreciated :)
