### ISSUE TITLE
Building for IOS Platform occurs error using this library.  Android is fine. 

### ISSUE THREAD

**Issue by richfuns** [proyecto26/RestClient#35]
**Unity version: 2018.2.4 (Have tried in other platform, still got this issue)**

Fatal error in Unity CIL Linker
Mono.Linker.MarkException: Error processing method: 'System.Void HTTP.HttpClient`2::Request()' in assembly: 'Assembly-CSharp.dll' ---> 
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'RSG.Promise, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null'
   �� Unity.Linker.Steps.AddUnresolvedStubsStep.GetTypeModule(TypeReference type, AssemblyDefinition[] assemblies)
   �� Unity.Linker.Steps.AddUnresolvedStubsStep.MarkAssemblyOfType(UnityLinkContext context, TypeReference type)
   �� Unity.Linker.Steps.UnityMarkStep.HandleUnresolvedType(TypeReference reference)
   �� Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   �� Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   �� Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   �� Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   �� Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   �� Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method)
   �� Mono.Linker.Steps.MarkStep.ProcessQueue()

**So I located the code that pointing to Restclient library.** 

FileNotFoundException: Could not find file "E:\unity-game\testProject\Temp\StagingArea\Data\Managed\tempStrip\RSG.Promise.dll"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, 
System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) 
(at <f2e6809acb14476a81f399aeb800f8f2>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share)
 (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) (at <28cdca1704d2491781795499c297b78b>:0)
Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) (at <28cdca1704d2491781795499c297b78b>:0)
UnityEditor.AssemblyReferenceChecker.CollectReferencesFromRootsRecursive (System.String dir, System.Collections.Generic.IEnumerable`1[T] roots,
 System.Boolean ignoreSystemDlls) (at C:/buildslave/unity/build/Editor/Mono/Utils/AssemblyReferenceChecker.cs:51)
UnityEditor.AssemblyReferenceChecker.CollectReferencesFromRootsRecursive (System.String dir, System.Collections.Generic.IEnumerable`1[T] roots,

Please help me, thanks in advance.

**Comment by richfuns** [comment]
The Demo of this library also have the issue.

**Comment by jdnichollsc** [comment]
Hi @ashleydavis
Sorry to tag you again, Do you know about this issue?

**Comment by richfuns** [comment]
@jdnichollsc  Thank you for noticing this issue.

You can download the demo from the release address if you please. https://github.com/proyecto26/RestClient/releases/tag/2.1.1

The issue will occur when you build it for IOS platform then. 

Please help me. Thanks again.

**Comment by jdnichollsc** [comment]
@richfuns what .NET version are you using in the project? It looks an issue with **RSG.Promise** library => https://github.com/Real-Serious-Games/C-Sharp-Promise

**Comment by richfuns** [comment]
@jdnichollsc  RestClient requires .Net 4.x Equivalent for building.  That is the version I am using and android platform building works fine.

![version](https://user-images.githubusercontent.com/1400999/46712747-10d65a00-cc85-11e8-9ba0-1e1e9e6da8db.png)

**Comment by richfuns** [comment]
> @richfuns no, .NET 4.x is required to support **HoloLens** with **RSG.Promise_standard.dll**, but you can remove that dll and later try renaming **RSG.Promise_net35.dll** to **RSG.Promise.dll**.
> Please, let me know

**### This tip fixed my problem. Awsome!!!!

I just did what you told and built it in .Net 4.x and .Net 3.5 successfully. 

So RSG.Promise_standard.dll is the key of the problem, I do not know why.  

Will RSG.Promise_standard.dll  affect my functionality if I just remove it?**  

Thank you so so much friend.

**Comment by jdnichollsc** [comment]
>Will RSG.Promise_standard.dll affect my functionality if I just remove it?**

No, it works perfect for other platforms except UWP 👍

**Comment by richfuns** [comment]
@jdnichollsc Noted.  We are just need Android and IOS at present. 

Thanks.

**Comment by jdnichollsc** [comment]
@richfuns any good comment from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501) would be really appreciated :)
