### ISSUE TITLE
"Unknown error"

### ISSUE THREAD

**Issue by fpv999** [proyecto26/RestClient#36]
I was using your Proyecto26 library in Unity project. And it worked pretty well.
Problem showed on 1 Android device.
Then(..) section is never called, and only Catch(..) get called.
where err contains only enigmatic error "Unknown error".

The same app works in Unity and on other phones.

Any hint?

**Comment by jdnichollsc** [comment]
I don't know (I don't have a lot of experiencie with Unity), I need logs, see your code, the Unity version, etc to analyze this issue

**Comment by fpv999** [comment]
Android 9.0 blocks non-TLS HTTP channels unless special section is added within AndroidManifest.xml - https://stackoverflow.com/questions/51902629/how-to-allow-all-network-connection-types-http-and-https-in-android-9-pie

I switched to HTTPS, and now I receivethose messages:
Could not load type 'System.Action' from assembly 'Assembly-CSharp'. (RSG.Promise) at RSG.Promise'1+<>c__DisplayClass44_o...

any idea?

**Comment by jdnichollsc** [comment]
@fpv999 any good comment from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501) would be really appreciated :)
