### ISSUE TITLE
Problems with self-signed SSL certificate

### ISSUE THREAD

**Issue by DominiqueD** [proyecto26/RestClient#37]
Hello,

I am using RestClient to connect my Unity client application to an Amazon AWS EC2 instance which runs an Nginx Webserver. The server is set up to use TLS. Since I apparently cannot simply create a valid certificate for my AWS-owned domain, I have to use a self-signed certificate. 
When I try to connect to the server from Unity (App in editor-mode), every request fails with following error message: "Unable to complete SSL connection"
I highly suspect it has something to do with Unity not accepting my self-signed certificate. The same request works fine when I send it from Postman.

Is there a way to deactivate certificate checks in RestClient, preferably without altering the source code and rebuilding the package?

Thanks for the help

**Comment by jdnichollsc** [comment]
Hi @DominiqueD,
We're using the **[UnityWebRequest](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html)** of Unity, you need to check the documentation to validate that

**Comment by DominiqueD** [comment]
Ok, thanks for the reply. According to the Unity forums, there is a (buggy) way to deactivate the certificate check by using a callback attached to the specific Unity Web Request. I will try to change that in the source code of RestClient and then repackage it for my project.

**Comment by jdnichollsc** [comment]
@DominiqueD Any pull request is welcome! 👍
