### ISSUE TITLE
Breaks build out of the box

### ISSUE THREAD

**Issue by meds** [proyecto26/RestClient#39]
DemoScene\Scripts\MainScript.cs uses EditorUtility so trying to do an actual build breaks as EditorUtility is not present.

Can fix this by wrapping in #if UNITY_EDITOR/#endif.

Is this deliberate or am I missing something? Happy to submit a pull request if former.

**Comment by jdnichollsc** [comment]
Any pull request is welcome to improve the demo 👍

**Comment by jdnichollsc** [comment]
You can see this conversation (it's related) https://github.com/proyecto26/RestClient/issues/22#issuecomment-398039066

**Comment by meds** [comment]
No worries, I'm a bit inexperienced with github but I will figure out how to submit a pull request, it should be a fairly minor change :)
