### ISSUE TITLE
Network connection error checking works only with get method

### ISSUE THREAD

**Issue by czuczorf** [proyecto26/RestClient#4]
Hello,
Great work! 
Just found a little bug, i've tried the latest unitypackage with demoscene, and disconnected my computer from the internet and only the "get" button noticed the connection error.

Thanks

**Comment by jdnichollsc** [comment]
@czuczorf ohh can you share a screenshot? I had not thought about that situation 😅

**Comment by czuczorf** [comment]
![get_without_internet](https://user-images.githubusercontent.com/2247388/33179315-44ee3678-d069-11e7-8622-a28f40e2fcbc.jpg)
![post_without_internet](https://user-images.githubusercontent.com/2247388/33179316-4527825c-d069-11e7-8977-d4611cc40517.jpg)
Thanks

**Comment by jdnichollsc** [comment]
@czuczorf And can you share me your code please? 👍

**Comment by czuczorf** [comment]
@jdnichollsc  i've just tried running the latest release and run into this
https://github.com/proyecto26/RestClient/releases/download/1.2.1/RestClient.unitypackage

**Comment by jdnichollsc** [comment]
yes, let me check in a moment. Thanks for notify this issue 👍

**Comment by itsharshdeep** [comment]
Hi, Thanks a lot for updating the package, but I believe the issue is still present, `Get()` is showing the no internet error but `Post()` is not showing the same. Post method is only showing the success. You can check the screenshot attached. 
I have tried :
1. Disconnect the wifi
2. Change the APIs address to something else

<img width="816" alt="sucessmessage while internet off" src="https://user-images.githubusercontent.com/13733291/33996693-f5574db6-e107-11e7-8474-97b904d9085c.png">

**Comment by czuczorf** [comment]
I've found a work around about this, you can catch the error in res variable

      RestClient.Post<Info>(rh, new Info(), (err, res, body) =>
        {
            if (!String.IsNullOrEmpty(res.error))
            {
                Debug.Log("Errorr : " + res.error);

**Comment by jdnichollsc** [comment]
Excellent, I need to add that validation with the promises 👍

**Comment by jdnichollsc** [comment]
I think the solution is modifying the following lines to validate if an error exist:
- https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/HttpActions/HttpBase.cs#L17
- https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/HttpActions/HttpBase.cs#L34
Example:
```
if (request.isDone && !String.IsNullOrEmpty(res.error))
```

What do you think @czuczorf? :)

**Comment by davidorbelian** [comment]
Hey. I accidentally wrote yesterday from the second, old account, I'm sorry.
Do you think it is enough to just check the `res.error`? May be also check for the status code to be "2xx"? What do you think @jdnichollsc?

**Comment by jdnichollsc** [comment]
@davidorbelian I don't know if validating by the status code is the correct way, because exist a lot of different status, or if validating by a range would be better... What do you think? 🤔

**Comment by davidorbelian** [comment]
@jdnichollsc I will check today after work if checking error value is enough and post the results here.

**Comment by jdnichollsc** [comment]
@davidorbelian thanks for your help! 👍

**Comment by davidorbelian** [comment]
@jdnichollsc I've tried that with some public APIs as well as my own ASP.NET Core project. Looks like checking the error will be OK.

**Comment by jdnichollsc** [comment]
ok, let me fix that issue at night

**Comment by jdnichollsc** [comment]
Fixing this issue with the version 1.2.2

**Comment by jdnichollsc** [comment]
@czuczorf @davidorbelian @itsharshdeep check the last release and let me know! 👍 https://github.com/proyecto26/RestClient/releases/tag/1.2.2
