### ISSUE TITLE
How can I use the downloaded data outside of the Promise?

### ISSUE THREAD

**Issue by kevbrun** [proyecto26/RestClient#42]
Hello !

I am using your wonderful framwork. I try to load the model data from an external server. I am able to download it, but I cannot use the data from outside the Promise structure.

e.g.

`

         RestClient.Request(request).Then(response =>
                    {

                        UberDebug.LogChannel(LogChannels.NETWORK, "Received from Server : " + response.Text);
                        responseAsModel = JsonConvert.DeserializeObject<GameContextMessage>(response.Text);

                    }).Catch(error => { UberDebug.LogErrorChannel(LogChannels.NETWORK, error.Message); }).Done();

`

The variable responseAsModel is always empty, after filling the data. Can you give me an advice about that? Also I would like to now how I can execute the queries in a synchronous way.

Thank you for your input in advance.

Regards
KB

**Comment by jdnichollsc** [comment]
You need to learn about promises here https://github.com/Real-Serious-Games/C-Sharp-Promise
