### ISSUE TITLE
How to post data to server by using key value pair? 

### ISSUE THREAD

**Issue by richfuns** [proyecto26/RestClient#44]
I would like to post data to server like ?param1=value1&param2=value2...

But this library seems not supporting it.  And I tried put  ?param1=value1&param2=value2   to  BodyString in RequestHelper, but still not working. 

Could anyone help me? thanks in advance.

**Comment by jdnichollsc** [comment]
You can send the params in the url, what's the problem with that?

**Comment by jdnichollsc** [comment]
@richfuns or do you want a helper class to include `params` from the `RequestHelper` class like this? https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.WebUtilities/QueryHelpers.cs

**Comment by richfuns** [comment]
> You can send the params in the url, what's the problem with that?
Thank you for you reply.
I tried in this way. I put below code to a requesthelper and post it to server
 FormSections = new List<IMultipartFormSection>()
                {
                    new MultipartFormDataSection("?param1=value1&param2=value2")
                },

But it seems not working.

**Comment by richfuns** [comment]
> @richfuns or do you want a helper class to include `params` from the `RequestHelper` class like this? https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.WebUtilities/QueryHelpers.cs

Yes, this helper also is useful.

**Comment by jdnichollsc** [comment]
Try my example https://github.com/proyecto26/RestClient/issues/15#issuecomment-390510322

**Comment by jdnichollsc** [comment]
But if you need query string params you can modify the url property to send these params

**Comment by richfuns** [comment]
> Try my example [#15 (comment)](https://github.com/proyecto26/RestClient/issues/15#issuecomment-390510322)

This solution also works, thanks a lot friend
