### ISSUE TITLE
Unloading broken assembly Assets/Plugins/myhttp.dll, this assembly can cause crashes in the runtime

### ISSUE THREAD

**Issue by richfuns** [proyecto26/RestClient#45]
```
**Unloading broken assembly Assets/Plugins/myhttp.dll, this assembly can cause crashes in the runtime
TypeLoadException: Could not load type 'HTTP.HttpClient`2' from assembly 'http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.**
```

Hello everyone, I have created a dll file which inclues my own http module. 

But when I called that dll from another new project, it occuring above errors.(HTTP.HttpClient is my namespace and filename)

I have included both Proyecto26.RestClient.dll and RSG.Promise.dll when  I was creating that dll file(dll file is based on .Net 3.5) 
But I guess the issue may comes from these two dll files.

My Unity runtime version: .Net 3.5 and Api level is .net 2.0 subset
(Also tried other version .Net 4.0 but still have this issue)

Could anyone help me? 

Thanks in advance.

**Comment by jdnichollsc** [comment]
I can't see an issue related with this project, and I don't know what's the issue if you can't share the code of your dll

**Comment by jdnichollsc** [comment]
If you want you can copy the code of this project instead of use the dlls and try again

**Comment by richfuns** [comment]
Sorry, maybe I dit not make it clear

For example, I have a HttpClient.cs file

I just put below codes:

using Proyecto26;
namespace a
{
    public class Test
    {
        public void TestHttp()
        {
            RestClient.Get("https://jsonplaceholder.typicode.com/posts/1").Then(response => {
                EditorUtility.DisplayDialog("Response", response.Text, "Ok");
            });
        }
    }
}

At last I want to package Httpclient.cs to a dll file and it will be called from other project.

So It will have above issues that I have mentioned when you put that dll to other project and run. 

But If I remove all http request code like RestClient.Get()......., that dll is working fine.

You can try it friend if you still doubt me.

Thanks.

**Comment by jdnichollsc** [comment]
Can you remove EditorUtility from your code and try again please?

**Comment by jdnichollsc** [comment]
Can you attach your project here in a zip file?

**Comment by richfuns** [comment]
> Yeah, because RSG.Promise is a dependency

I have found that the issue comes from  RSG.Promise.dll

**Comment by richfuns** [comment]
> Can you attach your project here in a zip file?

[HttpDll.zip](https://github.com/proyecto26/RestClient/files/2706690/HttpDll.zip)

Below is the project for creating dll 

[Testdll.zip](https://github.com/proyecto26/RestClient/files/2706691/Testdll.zip)

**Comment by jdnichollsc** [comment]
Ok, let me see today

**Comment by richfuns** [comment]
> Ok, let me see today

I see there is light.  Thank you so much friend.

**Comment by jdnichollsc** [comment]
Ok, I can see the issue. You need to use **NuGet** packages to add references or [create project libraries from Visual Studio](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio) because that structure only works for Unity projects but not for Libraries (dlls)

**Comment by richfuns** [comment]
> Ok, I can see the issue. You need to use **NuGet** packages to add references or [create project libraries from Visual Studio](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio) because that structure only works for Unity projects but not for Libraries (dlls)

Merry Christmas friend. 

I am sure I created .net framework for dll project from Visual Studio 2017.   
Above Testdll.zip 
![Uploading image.png…] is the demo project from Visual Studio.   Have you tired it?

**Comment by jdnichollsc** [comment]
Do you have the dlls as references? or are you adding the dlls into a custom folder?
Check my example (I added a dlls folder into my solution to include the dependencies required for my library) https://github.com/proyecto26/RestClient/tree/master/src

Example: https://stackoverflow.com/a/7831409/1532821
