### ISSUE TITLE
Working on all Platforms except WebGL

### ISSUE THREAD

**Issue by mawak93** [proyecto26/RestClient#46]
Hi
![pppp](https://user-images.githubusercontent.com/9941509/50570747-ddedbf00-0db8-11e9-90d3-cde97bf4f118.png)

Amazing Package and does the job quite well.

But whenever i try to Call it on a WebGL , it shows no data.

Can you tell me as to if i need an additional .dll file or any specific settting for that platform ?

Thanks

**Comment by jdnichollsc** [comment]
You need to enable CORS from your service

**Comment by mawak93** [comment]
Where can i enable that ?

**Comment by jdnichollsc** [comment]
I don't know what backend language are you using from your service

**Comment by jdnichollsc** [comment]
In the case of images, you should use CDNs, services like the Azure blob storage or something like that to have CORS enabled by default

**Comment by mawak93** [comment]
Ok

i will let the backend developer know about it.

Thanks !
