### ISSUE TITLE
need help for POST method 

### ISSUE THREAD

**Issue by Vinita18** [proyecto26/RestClient#5]
This is my code and I am trying to post gender = "male".
but this code is not working for me.

RestClient.Post<Models.RootObjectData> (url, new
	     {
		gender = "male"
	        }, (err, res,body) => {
		if (err != null) {
			EditorUtility.DisplayDialog ("Error", err.Message, "Ok");
		} else {
			EditorUtility.DisplayDialog ("Success", JsonUtility.ToJson (body, true), "Ok");
			}
		});

Model Classes:
	[Serializable]
	public class Data
	{
		public int timestamp_created;
		public int id;
		public string gender;
		public string access_token;

		public override string ToString(){
			return UnityEngine.JsonUtility.ToJson (this, true);
		}
	}

	[Serializable]
	public class RootObjectData
	{
		public bool status;
		public int statusCode;
		public Data data;
		public string message;

		public override string ToString(){
			return UnityEngine.JsonUtility.ToJson (this, true);
		}
	}

**Comment by jdnichollsc** [comment]
@Vinita18 Can you attach the log of the error please? I don't know if it's an error from your service and we need to validate that configuration of CORS works well from the service

**Comment by jdnichollsc** [comment]
Can you attach the response of your service? I need to know what's the JSON returned from your service to check if your code is correct. Closed this issue for the moment, let me know more details to reopen the issue

**Comment by jdnichollsc** [comment]
@Vinita18  after reviewing with NodeJS as the Backend, we can't send anonymous objects, a **Serializable** class is required. Example:
```
[Serializable]
public class ServerResponse {
  public string id;
  public DateTime date;
}
[Serializable]
public class User {
  public string firstName;
  public string lastName;
}
RestClient.Post<ServerResponse>("www.myapi.com/myendpoint", new User {
  firstName = "Juan David",
  lastName = "Nicholls Cardona"
}).Then(response => {
  EditorUtility.DisplayDialog("ID: ", response.id, "Ok");
  EditorUtility.DisplayDialog("Date: ", response.date.ToString(), "Ok");
});
```

Best regards, Nicholls

**Comment by Vinita18** [comment]
Okay. Thanks.
I will try it next time in my code.
