### ISSUE TITLE
ArgumentException: JSON must represent an object type. UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:50) UnityEngine.JsonUtility.FromJson[Goalkeeper] (System.String json) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:33) Proyecto26.HttpBase+<>c__DisplayClass5_0`1[Goalkeeper].<DefaultUnityWebRequest>b__0 (Proyecto26.RequestException err, Proyecto26.ResponseHelper res) Proyecto26.HttpBase+<CreateRequestAndRetry>d__0.MoveNext () UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

### ISSUE THREAD

**Issue by mhadji05** [proyecto26/RestClient#54]
using Proyecto26;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class firebaseTEST : MonoBehaviour {

    static string DB_URL = ""; // url deleted only now for security in my code exists

    Coach coach = new Coach("coachP", "goalkeeperK", 10);

    // Use this for initialization
    void Start () {

        OnSubmit();
    }

    void OnSubmit()
    {
        //PostToDatabase();  // i can Post

        RetrieveFromDatabase(); // i have a runtime red warning
    }

    private void PostToDatabase()
    {
        int[] stats = new int[] { 5, 10, 3 };
        Coach coach = new Coach("coachP", "goalkeeperK", 50);
        Goalkeeper goalkeeper = new Goalkeeper("goalkeeperK", 15);
        
        RestClient.Post(DB_URL + coach.coachName + ".json", goalkeeper);

        
    }

    private void RetrieveFromDatabase()
    {
        RestClient.Get<Goalkeeper>(DB_URL + "goalkeeperK" + ".json").Then(response =>
        {
            coach.goalkeeper= response;

            Debug.Log(coach.goalkeeper); //this line not printed in console

        });
    }
}

--------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class Goalkeeper{

    public string keeperName;
    public int Totalstats;

    public Goalkeeper(string keeperName, int Totalstats)
    {
        this.keeperName = keeperName;
        this.Totalstats = Totalstats;
    }
}

--------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class Coach {

    public string coachName;
    public Goalkeeper goalkeeper;

        public Coach(string coachName, string keeperName, int Totalstats)
    {
        this.coachName = coachName;

        goalkeeper = new Goalkeeper(keeperName, Totalstats);

    }

}

**Comment by jdnichollsc** [comment]
Can you share the code of the class Goalkeeper?

**Comment by jdnichollsc** [comment]
Try without using generics to inspect the response of the GET request

**Comment by mhadji05** [comment]
i update my code.

Basicly i need to make a DB on unity that a every coach can save goalkeepers stats. 1 coach can have many goalkeepers and a goalkeeper can make many different stats for every training and i need to retrieve all of the stats of 1 goalkeeper.

Is that possible with RestClient and firebase?

**Comment by jdnichollsc** [comment]
Try this code:

**firebaseTEST.cs**
```

private void RetrieveFromDatabase()
{
    RestClient.Get(DB_URL + "goalkeeperK" + ".json").Then(response =>
    {
        Debug.Log(response.data);
    });
}
```

**Comment by jdnichollsc** [comment]
Also, add a constructor without params like this:
**Goalkeeper.cs**
```
[Serializable]
public class Goalkeeper {
  public string keeperName;
  public int Totalstats;

  public Goalkeeper() {}

  public Goalkeeper(string keeperName, int Totalstats)
  {
    this.keeperName = keeperName;
    this.Totalstats = Totalstats;
  }
}
```

**Comment by mhadji05** [comment]
i have compile error

Assets/_Completed-Game/_FScripts/firebaseTEST.cs(47,32): error CS1061: Type `Proyecto26.ResponseHelper' does not contain a definition for `data' and no extension method `data' of type `Proyecto26.ResponseHelper' could be found. Are you missing an assembly reference?

**Comment by jdnichollsc** [comment]
@mhadji05 `response.Data` 😅

**Comment by jdnichollsc** [comment]
or `response.Text`

**Comment by mhadji05** [comment]
print null

**Comment by jdnichollsc** [comment]
ok, so that's your issue... 😅

**Comment by mhadji05** [comment]
Basicly i need to make a DB on unity that every coach can save goalkeepers stats. One coach can have many goalkeepers and a goalkeeper can make many different stats for every training and i need to retrieve all of the stats of 1 goalkeeper.

Is that possible with RestClient and firebase?

**Comment by jdnichollsc** [comment]
Why not? You need a service to connect to the DB, maybe using FireBase Cloud Functions or creating a backend, later you can create the HTTP requests with this library to get the data of your service 👍

**Comment by mhadji05** [comment]
thanks a lot!
