### ISSUE TITLE
Tls/ssl related questions.

### ISSUE THREAD

**Issue by dev-shinyu** [proyecto26/RestClient#55]
Hi!! 

The support item has confirmed TLS/SSL

The following error occurs only in ANDROID. 

http: TLS handshake error from 211.108.***.***:10164: remote error: tls: unknown certificate

The editor or Windows platform is normally accessible.

You used the Let's encrypt certificate and the port is 448.

Why is this? I want you to give me a solution.

help me~~

I'll wait for an answer

Thank you :)

**Comment by jdnichollsc** [comment]
Any issue related with certificates and platforms => https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html
