### ISSUE TITLE
CustomCertificateHandler

### ISSUE THREAD

**Issue by Zartris** [proyecto26/RestClient#57]
I am creating a UWP application for Hololens and I need to be able to use the CertificationHandler, but I cannot seem to find your:
CertificateHandler = new CustomCertificateHandler(), //Included in the source code of this library
anywhere in the source code.
The reason is, I need to be able to use certificates without using the standard "System.Security.Cryptography.X509Certificates", since this is not supported on UWP applications.
Did you get past this or should i keep on looking?

**Comment by jdnichollsc** [comment]
Sorry @Zartris, you need to use the forums of Unity to ask that, I don't have experience using certificates from Unity 👍
