### ISSUE TITLE
Help with DownloadProgress

### ISSUE THREAD

**Issue by IamChrister** [proyecto26/RestClient#58]
Hi,
thank you for the great repo!

I'm having some issues implementing the downloadProgress. When I try to get the progress of a request, it always displays 0.

I'm setting the 'Content-Length' header in Node as such (no luck without setting the header either):
```
 res.setHeader('Content-Length', Buffer.byteLength(message, 'utf-8'));
            res.send(message);
```

And trying to get the downloadprogress like this:
```
 if(currentRequest != null && isDownloading)
            {
                Debug.Log("Downloading: " + currentRequest.DownloadProgress);
            }
```

No difficulty using the uploadProgress which makes me think the issue is on my back-end somehow or it is because I'm not using the downloadHandler in any way. If you could shed light on this issue, it would be greatly appreciated.

Using Unity 2018.3.6f1

**Comment by jdnichollsc** [comment]
Hi mate! I'm not sure because I don't have experience sending the content length from NodeJS, are you downloading a file?

**Comment by IamChrister** [comment]
Hey!

Yeah, trying to download a file, however the download progress remains 0 throughout and the total bytes to download displays 0 as well. No errors.

The content length header should be set correctly, but the download progress continues to be 0 in Unity :/

**Comment by jdnichollsc** [comment]
Can you debug using UnityWebRequest system directly?
Let me know please
