### ISSUE TITLE
Unity 3d Version 5.6.3 Error

### ISSUE THREAD

**Issue by racingdevtech** [proyecto26/RestClient#6]
TypeLoadException: Could not load type 'UnityEngine.Networking.UnityWebRequestAsyncOperation' from assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Proyecto26.StaticCoroutine:StartCoroutine(IEnumerator)
Proyecto26.RestClient:GetArray(RequestHelper, Action`2)
Proyecto26.RestClient:GetArray(RequestHelper)
MainScript:Get() (at Assets/MainScript.cs:18)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by jdnichollsc** [comment]
Can you attach a demo of your code to verify if it's an issue with the plugin?

**Comment by jdnichollsc** [comment]
It's not an issue because `UnityWebRequestAsyncOperation` was added with Unity 2017.2 👍
