### ISSUE TITLE
Error codes?

### ISSUE THREAD

**Issue by zsculpt** [proyecto26/RestClient#60]
Trying to interact with a Firebase endpoint (which works fine), but when it fails, the only error code I ever get is "Generic/unknown HTTP error", which I am checking with the .Catch( error =>... I need to know the actual error like "password invalid" etc. How do I check it?

**Comment by jdnichollsc** [comment]
error.StatusCode

**Comment by zsculpt** [comment]
This doesn't exist for me. I just installed from the Unity Asset Store 2 days ago:

https://imgur.com/a/tFNJdV0

**Comment by zsculpt** [comment]
RestClient.Post<SignupResponse>( "https://www.testserver.com", “testdata" ).Then( response =>
        {
	         Debug.Log( “Success!" );

        }).Catch( error =>
        {
            Debug.LogError( error.Message );
        });

With this syntax, error does not have a .StatusCode property.

**Comment by jdnichollsc** [comment]
This is our `RequestException` class https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/RequestException.cs

**Comment by zsculpt** [comment]
I’ve been looking at your demo code and trying to understand the syntax you are using and how it’s different from the example I found. For a new user sign up Firebase requires a JSON string in the following format:

{
	“email” : “myname@server.com <mailto:myname@server.com>”,
	“password” : “12345”,
	“returnSecureToken” : true
}

So based on your example, I tried sending the data like this: (but only get back the usual 400 error)

RestClient.Post<Signup>( new RequestHelper
        {
            Uri = “https://www.testserver.com”,
            Body = new Signup
            {
                email = “myname@server.com",
                password = “12345",
                returnSecureToken = true
            },
            Retries = 5,
            RetrySecondsDelay = 1,
            RetryCallback = (err, retries) =>
            {
                Debug.Log( string.Format( "Retry #{0} Status {1}\nError: {2}", retries, err.StatusCode, err ) );
            }
        }, (err, res, body) =>
        {
            if(err != null)
            {
                Debug.LogError( "Error: " + err.Message );
            }
            else
            {
                Debug.Log( "Success: " + res.Text );
            }
        });

**Comment by zsculpt** [comment]
OK, I was able to get Firebase signup to work using your code example and the RequestHelper class (I had a type-o in my string, apologies!), however, the error I get back STILL only contains a Generic 400 error. I looked at every property such as error.StatusCode, error.ServerMessage, etc. and there is no other data. Could you please re-open this issue until we can find a solution?

**Comment by jdnichollsc** [comment]
That status code is returned from the server side, I don't understand what you want to do here

**Comment by zsculpt** [comment]
Finally found the solution! The real error message is actually returned in res.Text (ResponseHelper). When parsed into a JSON node can be read from the "message" key. Hope this is helpful to someone:

{
  "error": {
    "code": 400,
    "message": "EMAIL_EXISTS",
    "errors": [
      {
        "message": "EMAIL_EXISTS",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

**Comment by jdnichollsc** [comment]
OMG hahaha

**Comment by zsculpt** [comment]
I still can't figure out how to use any of the "IPromise" methods to get back this data tho. Are you able to assist with that?

**Comment by jdnichollsc** [comment]
```
        RestClient.Post( new RequestHelper
        {
            Uri = “https://www.testserver.com”,
            Body = new Signup
            {
                email = “myname@server.com",
                password = “12345",
                returnSecureToken = true
            },
            Retries = 5,
            RetrySecondsDelay = 1,
            RetryCallback = (err, retries) =>
            {
                Debug.Log( string.Format( "Retry #{0} Status {1}\nError: {2}", retries, err.StatusCode, err ) );
            }
        }).Then(response => {
            response.Text
        });
```

**Comment by zsculpt** [comment]
Thank you for the quick reply, but that’s only for a successful Post. If an exception is thrown, all I can do is:

Catch( error =>
        {
            Debug.LogError( error.Message );

…and there’s nothing in error.Message except for the usual "Generic/unknown HTTP error”. I need to be able to check the ResponseHelper like your callback method example:

**Comment by jdnichollsc** [comment]
With exceptions we're getting the `text` response of the UnityWebRequest system if the error is empty https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/HttpBase.cs#L61
So it looks like you need a new property here from the `RequestException` class to get that other info.
Let me do that

**Comment by G0nZZZ** [comment]
I need something like that, what I did is in httpbase.cs, removed the error check line 63 so: 

private static RequestException CreateException(UnityWebRequest request)
{
	var message = request.downloadHandler.text;
	return new RequestException(message, request.isHttpError, request.isNetworkError,      
        request.responseCode);
}

**Comment by jdnichollsc** [comment]
Give me a moment to add the new property from the RequestException 👍

**Comment by jdnichollsc** [comment]
Added!

**Comment by jdnichollsc** [comment]
RestClient.Post(new RequestHelper
{
    Uri = “https://www.testserver.com”,
    Body = new Signup
    {
        email = “myname@server.com",
        password = “12345",
        returnSecureToken = true
    },
    Retries = 5,
    RetrySecondsDelay = 1,
    RetryCallback = (err, retries) =>
    {
        Debug.Log( string.Format( "Retry #{0} Status {1}\nError: {2}", retries, err.StatusCode, err ) );
    }
}).Catch(error => {
    error.Response
}).

**Comment by zsculpt** [comment]
Many thanks for fixing this!

Cheers,

**Comment by jdnichollsc** [comment]
thanks for report this! 💯

**Comment by jscaceres** [comment]
Hi!, is this fix already in the realese in AssetStore or should I donwload the github version? I downloaded the last version in the Asset Store and I can't access `e.Response`.
