### ISSUE TITLE
How can I get response data at the first stage

### ISSUE THREAD

**Issue by ssSolars** [proyecto26/RestClient#62]
I have defined a class:
```
public class A {
    public string A1;
    public string A2;
    public string A3;

   public void Get(string endpoint) {
	 var uri = ip + endpoint + "/" + this.A1 + "/" + this.A2;
	 RestClient.Get(uri, (err, response) => {
		 this.A3 = response.Text; // should be "a3"
	 });
   }
}
```

At another place, I do this 
```
A a = new A();
A.A1= "a1";
A.A2= "a2";
A.Get("endpoint");
print(A.A3);
```

I got an output here which show A.A3 is null, but what I want is "a3". I debug the code, find it will do ``` print(A.A3) ``` first, then ```this.A3 = response.Text; ```.

Could you please give me some advice to help me get the correct result? Thank you!

**Comment by jdnichollsc** [comment]
You need to use Promises 👍 https://github.com/Real-Serious-Games/C-Sharp-Promise
