### ISSUE TITLE
JSON error on "null" response text string

### ISSUE THREAD

**Issue by zsculpt** [proyecto26/RestClient#64]
Line 91 of HttpBase:  body = JsonUtility.FromJson<TResponse>(res.Text);

This will cause an error in JsonUtility "JSON must represent an object type." if the response string from the server is literally the text string "null".

**Comment by jdnichollsc** [comment]
That's an issue from the server. Attach your code please

**Comment by zsculpt** [comment]
All I'm doing is asking for a key in the dataBase that doesn't exist:

RestClient.Get( serverUrl + "NonValidDirectory/" + ".json" ).Then( response =>

**Comment by jdnichollsc** [comment]
So you need to return a status code 404 or 204 (No content) from the server, we only can validate if the response is not null or empty https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/HttpBase.cs#L89

**Comment by zsculpt** [comment]
It’s not my server - it’s Firebase. I was able to fix the error in HttpBase by using:

try
{
    body = JsonUtility.FromJson<TResponse>(res.Text);//__BUG__
}
catch
{
    Debug.LogError( "Invalid JSON format" );
}

**Comment by jdnichollsc** [comment]
Wait, that [line of code](https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/HttpBase.cs#L89) is only executed if you're passing a custom class: `RestClient.Get<MyCustomClass>( serverUrl + "NonValidDirectory/" + ".json" ).Then( response =>`

**Comment by zsculpt** [comment]
Yes that’s correct, sorry:

RestClient.Get<MyDataType>( serverUrl + "NonValidDirectory/" + user.localId + ".json" ).Then( response =>

But the code inside the .Then() promise block doesn’t even get called because the JsonUtility throws the error.

**Comment by jdnichollsc** [comment]
Done, check the last commit! 👍
