### ISSUE TITLE
Query string utilities

### ISSUE THREAD

**Issue by gpiffaretti** [proyecto26/RestClient#65]
This is really helpful, I'd also like to have support for query strings in the RequestHelper, maybe some simple utilities can be added for this

**Comment by jdnichollsc** [comment]
Any pull request is always welcome!

**Comment by jdnichollsc** [comment]
for example, a Dictionary for `Params` 💯

**Comment by Vixxd** [comment]
I am also interested in this feature - following for updates :)

**Comment by jdnichollsc** [comment]
Hello guys, are you agree with these changes? 👍  https://github.com/proyecto26/RestClient/pull/98/files

**Comment by jdnichollsc** [comment]
Done!
