### ISSUE TITLE
Return ResponseHelper with a custom request.

### ISSUE THREAD

**Issue by diego-mws** [proyecto26/RestClient#66]
When I call a request with a custom data type (eg. RestClient.Post<MyClass>) what I get back is the data class filled but I am losing the ResponseHelper.

I think the problem might be inside the Promisify function that does not propagate the response.

private static void Promisify<T>(this Promise<T> promise, RequestException error, ResponseHelper response, T body)
{
    if (error != null && response != null) {
        error.ServerMessage = response.Error ?? error.Message;
    }
    promise.Promisify(error, body);
}

I am focusing on the Promises version of the API. I noted that in the version with callback is possible to retrieve the custom class *and* a ResponseHelper but I would really like to avoid using callbacks.

Could you please add the ResopnseHelper in the outcome of a custom request?

Cheers!

**Comment by jdnichollsc** [comment]
Hi @diego-mws,
In the case of promises, you only can return one value by design, so that's the reason we're returning only the data class filled. So you have 2 options with promises:
1. The data class:
```
RestClient.Get<User>(usersRoute + "/1").Then(myUser => {
});
```
2. The ResponseHelper class:
```
RestClient.Get(usersRoute + "/1").Then(response => {
  var myUser = JsonUtility.FromJson<User>(response.Text);
});
```

**Comment by jdnichollsc** [comment]
Any pull request is always welcome mate!
