### ISSUE TITLE
Error when building on Hololens (UWP)

### ISSUE THREAD

**Issue by Thomas-6freedom** [proyecto26/RestClient#67]
Hello.

I use Unity 2018.3.10f1 with these settings :
![image](https://user-images.githubusercontent.com/49686866/56586385-ee33df00-65df-11e9-8eb0-f94bef57b9e2.png)

![image](https://user-images.githubusercontent.com/49686866/56586397-f7bd4700-65df-11e9-98d4-4f473662d934.png)

![image](https://user-images.githubusercontent.com/49686866/56586414-fee45500-65df-11e9-9268-dd7c56f7cf4b.png)

![image](https://user-images.githubusercontent.com/49686866/56586432-0572cc80-65e0-11e9-8fd0-ab5f07989f3d.png)

And it failed to build :

![image](https://user-images.githubusercontent.com/49686866/56586462-102d6180-65e0-11e9-8d53-852944b28a74.png)

Strangely, I don't have any error when deleting the RSG.Promise_standard.dll. But the RestClient.Get() function does not work.

**Comment by jdnichollsc** [comment]
Hi @Thomas-6freedom,
Can you do me a favor? Can you try with the source code of RSG.Promise instead of using the dll? https://github.com/Real-Serious-Games/C-Sharp-Promise/tree/master/src
You can put the previous code in a folder called `RSG.Promise` next to `RestClient` folder
Let me know please

**Comment by Thomas-6freedom** [comment]
First I tried to "add the reference" by opening my Visual Studio 2017 => Project => Add references then choosing the dll

![image](https://user-images.githubusercontent.com/49686866/56587408-c2b1f400-65e1-11e9-869c-627a2cf09abe.png)

My visual studio does not warn me anymore. But Unity still seems upset.

I'll try what you suggest me.

**Comment by jdnichollsc** [comment]
Let me know if the source code of RSG.Promise to publish a new version from the Unity Store with the source code instead of using dlls :)

**Comment by Thomas-6freedom** [comment]
I removed the two DLL and there meta and add the folder you asked me :

![image](https://user-images.githubusercontent.com/49686866/56587765-626f8200-65e2-11e9-97bc-15df77e36007.png)

**Comment by Thomas-6freedom** [comment]
![image](https://user-images.githubusercontent.com/49686866/56587841-86cb5e80-65e2-11e9-87a5-1e0841c67da4.png)

now I'll try in the headset !

**Comment by jdnichollsc** [comment]
Eureka?

**Comment by Thomas-6freedom** [comment]
There is now errors in the Holotoolkit when trying to deploy to the headset... I'll take a look.
If you have any idea, I'll take it =)

![image](https://user-images.githubusercontent.com/49686866/56588230-3bfe1680-65e3-11e9-9d87-c8c0f22f4ac5.png)

**Comment by jdnichollsc** [comment]
I'm not sure, What's that?

**Comment by Thomas-6freedom** [comment]
At least it's working inside the Unity Editor 
![image](https://user-images.githubusercontent.com/49686866/56588658-14f41480-65e4-11e9-8094-5e6e20c44b8f.png)

**Comment by jdnichollsc** [comment]
OMG, I have the dlls with Unity haha

**Comment by Thomas-6freedom** [comment]
With the Hololens, you build a visual studio project THEN you build & deploy it in the Hololens.
When trying to build this project, I have theses "hololens-related" errors :

![image](https://user-images.githubusercontent.com/49686866/56588937-9cda1e80-65e4-11e9-932f-84f9bb82fe00.png)

**Comment by jdnichollsc** [comment]
Sorry mate, Can you put that issue here? https://github.com/Real-Serious-Games/C-Sharp-Promise/issues

**Comment by Thomas-6freedom** [comment]
There is another way to put the app in the headset :
It's to use the "build tool" given in the SDK. It creates an appx package then you can upload it to your hololens.

Annnd it's working.  I did make the appx and I did send it into my headset.
I could launch my app but I was stuck at the moment I make a RestClient.Get().
I don't know if there is any error because I can't debug the app because I can't plug Visual Studio because of the last screenshot I post...

**Comment by Thomas-6freedom** [comment]
Do I really need all those files ? the .csproj ? the .snk ? 
![image](https://user-images.githubusercontent.com/49686866/56590098-c2682780-65e6-11e9-86ad-fa62b913f337.png)

**Comment by Thomas-6freedom** [comment]
Do you think there could be an issue based on 

1. The fact everything is under a folder named "Plugins" ?
2. The fact that there is two files named "RestClient" ?

**Comment by jdnichollsc** [comment]
Ohh of course, you can remove .csproj and .snk files

**Comment by jdnichollsc** [comment]
@Thomas-6freedom About the second point, try moving /Promises/RestClient.cs to /RestClientPromises.cs and let me know please

**Comment by Thomas-6freedom** [comment]
I succeeded to build from VS !
If you look at this post : https://github.com/proyecto26/RestClient/issues/67#issuecomment-485822251

There is a tons of project on the right tab.
So I deleted all the *.csproj in my project folder
then deleted /App and /UWP 
then I created a build from Unity without enabling C# Project.

Trying to watch if a RestClient.Get() works in the device now.

**Comment by jdnichollsc** [comment]
Ok, sounds amazing!
I'm going to create a new version including the source files of `RSG.Promise` to avoid these issues in the future 👍 
Thanks for your help mate!

**Comment by Thomas-6freedom** [comment]
It does not work inside the Hololens.

This is my code 

![image](https://user-images.githubusercontent.com/49686866/56591222-9baaf080-65e8-11e9-81ac-ffe0387d8a42.png)


And this is my error :

![image](https://user-images.githubusercontent.com/49686866/56591264-b3827480-65e8-11e9-8565-4b4a6b735d31.png)

**Comment by Thomas-6freedom** [comment]
Next, I'll try this : 

https://github.com/proyecto26/RestClient/issues/67#issuecomment-485836990

**Comment by Thomas-6freedom** [comment]
How can I get the status code of the error ?

![image](https://user-images.githubusercontent.com/49686866/56591664-6a7ef000-65e9-11e9-8db6-ad63aabcb929.png)

**Comment by Thomas-6freedom** [comment]
![image](https://user-images.githubusercontent.com/49686866/56592105-42dc5780-65ea-11e9-8281-585955413815.png)

**Comment by jdnichollsc** [comment]
c.StatusCode of our `RequestException` class https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/RequestException.cs#L4

**Comment by jdnichollsc** [comment]
Your image looks an issue with the UnityWebRequest system 🤔

**Comment by Thomas-6freedom** [comment]
I did this little test :

![image](https://user-images.githubusercontent.com/49686866/56592582-42908c00-65eb-11e9-94fd-9d220b78fd41.png)

This is the result

![image](https://user-images.githubusercontent.com/49686866/56592610-520fd500-65eb-11e9-9a5e-d9281dd5747f.png)

**Comment by Thomas-6freedom** [comment]
I will try to do my GET request without RestClient. I'll post the result later.

**Comment by jdnichollsc** [comment]
and what about `request. isNetworkError` and `request. isHttpError`?

**Comment by Thomas-6freedom** [comment]
ok this is what I did :
![image](https://user-images.githubusercontent.com/49686866/56593855-728c5f00-65ec-11e9-9f23-2f2dbb8c3c5e.png)

![image](https://user-images.githubusercontent.com/49686866/56593950-8041e480-65ec-11e9-95a0-3b8bee88d618.png)

and it's working in the editor.

AAAAND not in the Hololens...

![image](https://user-images.githubusercontent.com/49686866/56594403-0c540c00-65ed-11e9-9083-7dea145465a6.png)

**Comment by Thomas-6freedom** [comment]
So for now, I will state that the hololens has some issue to send HTTP request and thus it's not the RestClient fault.

**Comment by jdnichollsc** [comment]
I need HoloLens to debug that haha

**Comment by Thomas-6freedom** [comment]
ok now it's working. I don't know what I have done to make it working.
If anyone stumble across this issue :

- I put a "/" at the end of my URL 

![image](https://user-images.githubusercontent.com/49686866/56600070-352dce80-65f8-11e9-97a0-b1e5b365817c.png)


- I make a first request to test my internet connexion to the same URL.

![image](https://user-images.githubusercontent.com/49686866/56600148-58587e00-65f8-11e9-9d17-ec664a41bd7e.png)

**Comment by Thomas-6freedom** [comment]
Thank you @jdnichollsc for your reaction time which was surprisingly quick ! ❤️

**Comment by jdnichollsc** [comment]
Thanks to you for report this issue! 💯

**Comment by jdnichollsc** [comment]
Done! https://github.com/proyecto26/RestClient/releases/tag/2.5.6

**Comment by antoined73** [comment]
Hello :)

Actually I'm having an issue when running the app on the Hololens.
It builds and deploy well, but every time I try make a request it says : "Proyecto26.RequestException: Cannot resolve destination host".
Like if the Hololens hasn't any wifi connection, weird..

I tried with and without the .dlls (the last version with code included and another version using dlls), changing wifi network. And it does work in unity editor.

I really don't know if you have some ideas to make it work :/
