### ISSUE TITLE
orderBy Query

### ISSUE THREAD

**Issue by EpicPandaGames** [proyecto26/RestClient#69]
Hi, would like to say this is great work. 

This is the first time im working with a REST api so please bare with me.

Im using firebase's realtime database and unity;
When trying to get some filtered data I get a crash of "Unespected node type" in JsonHelper.cs 
line 18: var wrapper = JsonUtility.FromJson<Wrapper<T>>(newJson);

This is because the result from:
A   https://[databaseName]/Leaderboard_0.json?orderBy=%22score%22&startAt=0

Gives a different formatted result from:
B   https://[databaseName]/Leaderboard_0.json

**My question is**: Im I missing something in the way im retrieving the information? or do I need to do something to parse the result when getting filtered queries?

Thanks for the work! 

Result A (BAD): 
`{"12":{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":604,"userID":"12"},"8":{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":640,"userID":"8"},"4":{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":845,"userID":"4"},"11":{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":667,"userID":"11"},"9":{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":957,"userID":"9"},"13":{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":781,"userID":"13"},"5":{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":708,"userID":"5"},"10":{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":125,"userID":"10"},"6":{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":331,"userID":"6"},"1":{"date":"5/8/2019 4:24:22 PM","location":"(10.0, 12.0)","score":949,"userID":"1"},"0":{"date":"5/8/2019 4:24:21 PM","location":"(10.0, 12.0)","score":892,"userID":"0"},"2":{"date":"5/8/2019 4:24:24 PM","location":"(10.0, 12.0)","score":431,"userID":"2"},"7":{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":973,"userID":"7"},"3":{"date":"5/8/2019 4:24:24 PM","location":"(10.0, 12.0)","score":897,"userID":"3"}}`

Result B (GOOD!):
`[{"date":"5/8/2019 4:24:21 PM","location":"(10.0, 12.0)","score":892,"userID":"0"},{"date":"5/8/2019 4:24:22 PM","location":"(10.0, 12.0)","score":949,"userID":"1"},{"date":"5/8/2019 4:24:24 PM","location":"(10.0, 12.0)","score":431,"userID":"2"},{"date":"5/8/2019 4:24:24 PM","location":"(10.0, 12.0)","score":897,"userID":"3"},{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":845,"userID":"4"},{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":708,"userID":"5"},{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":331,"userID":"6"},{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":973,"userID":"7"},{"date":"5/8/2019 4:24:25 PM","location":"(10.0, 12.0)","score":640,"userID":"8"},{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":957,"userID":"9"},{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":125,"userID":"10"},{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":667,"userID":"11"},{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":604,"userID":"12"},{"date":"5/8/2019 4:24:26 PM","location":"(10.0, 12.0)","score":781,"userID":"13"}]`

**Comment by jdnichollsc** [comment]
Can you attach your code please? Because the first one is an object and the second one is an array 😅

**Comment by EpicPandaGames** [comment]
> Can you attach your code please? Because the first one is an object and the second one is an array 😅
Here it is, thanks for the reply!

this is the code getting the ordered query. Same code is used for normal query where the query var is set to ""

`    public void Get()
    {
        string query = "?orderBy=%22score%22&startAt=0";
        string url = DataBaseURL("Leaderboard_0", query);
        //url is https://[databaseName]/Leaderboard_0.json?orderBy=%22score%22&startAt=0
        RequestHelper helper = new RequestHelper();
        helper.Uri = url;
        string log ="";
        RestClient.GetArray<TopScore>(helper).Then(topscores =>
        {   
            foreach(TopScore t in topscores)
            {
                Debug.Log("UserID: " + t.userID);
                Debug.Log("score: " + t.score);
                Debug.Log("location: " + t.location);
                Debug.Log("date: " + t.date);
                log += "UserID: " + t.userID + "\n";
                log += "score: " + t.score + "\n";
                log += "location: " + t.location + "\n";
                log += "date: " + t.date + "\n";
            }
            LogOfLegends.text = log  + topscores.ToString();
        });
    }`

`    [Serializable]
    public class TopScore
    {
        public string userID;

        public int score;

        public string date;

        public string location;

        public override string ToString()
        {
            return UnityEngine.JsonUtility.ToJson(this, true);
        }
    }`

**Comment by jdnichollsc** [comment]
But the `Result A (BAD)` is an object, it's not an array as you can see here.. so I'm not sure how can I help you

**Comment by EpicPandaGames** [comment]
Its fine, just wondering how you handled this sort of thing or if it even happened to you.

Its working with a bit of trimming to the string. 
But the way im testing it is horrible (chapuza) , is there a way to get the string directly instead of Get<> or GetArray<> ?

Also, this is off-topic but im using Firebase Realtime Database because its free, do you recomend any other service like that?

thanks!

**Comment by jdnichollsc** [comment]
Ohh with your last example you can use the RestClient.Get method too. You can use Azure Functions, AWS Lambda, etc but you need to create the database (SQL or NoSQL depending of your business). Firebase is a good service if you don't have restrictions, also if you need reactive data you can use other packages, otherwise you can use HTTP requests and this package is ok for you 👍
