### ISSUE TITLE
Status comming OK, but values aren't reaching to the server

### ISSUE THREAD

**Issue by itsharshdeep** [proyecto26/RestClient#7]
Hi,

I am not able to figure out that this is my bug or plugin ( most probably I know, this is my own issue,) but still try to help me out. 
Sorry, but I don't know what I'm doing wrong, so please guide me once.
I have the following POST REST API
http://vr.azurewebsites.net/api/CustInfoTemps

with params:
```
{
  "CustomerName": "sample string 2",
  "MobileNo": "123",
  "AccessoriesInterior": "sample string 6",
  "AccessoriesExterior": "sample string 7"
}

```
This API is working fine in Postman & RestClient 

I made a wrapper method so that my all friends use this in the same way :
```
public static void POSTWebService <T> (string API, object bodyJson, Action<string, bool> callback){
            var requestOptions = new RequestHelper {
                url = API,
                headers = new Dictionary<string, string> {
                    { "Content-Type", "application/json" }
                }
            };
            RestClient.Post<T> (requestOptions, bodyJson, (err, res, body) => {
                if (!String.IsNullOrEmpty (res.error)) {
                    Debug.LogError ("error " + res.error);
                  callback.Invoke (res.error, false);
                } else {
                  callback.Invoke (JsonUtility.ToJson (body, true), true);
                    Debug.Log ("SUcess " + JsonUtility.ToJson (body, true));
                }
            }); 
        }
```

I'm calling this method with the following code:
```
WebService.POSTWebService<CarCarConfiguredAPIResut> (http://vrappmahindra.azurewebsites.net/api/CustInfoTemps,
				new {
					CustomerName = "Test",
					MobileNo = 123,
					AccessoriesInterior = "Accessoried",
					AccessoriesExterior = "Exterior"
                                   }, SendDataCallBack
			);	
```

I am getting the result of success, but the values aren't reflecting in my server. 

Please let me know what I'm doing wrong.

**Comment by jdnichollsc** [comment]
@itsharshdeep Can you install the nuget package `Web Api Help Pages`? I can't see any documentation of your service and I need to see how is your service getting the data of your request

**Comment by jdnichollsc** [comment]
Also the Content-Type `application/json` is added by default, so you don't need add that header again https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/Extensions.cs#L25

**Comment by itsharshdeep** [comment]
Thanks a lot for quick response. But I didn't get "the nuget package Web Api Help Pages".
 Can you please let me know in details. So that I can answer you well

**Comment by jdnichollsc** [comment]
@itsharshdeep from your web service https://www.nuget.org/packages/Microsoft.AspNet.WebApi.HelpPage/

**Comment by jdnichollsc** [comment]
?

**Comment by itsharshdeep** [comment]
@jdnichollsc : I am really sorry for closing the issue bcz I know nothing about the help page you want me to add. I am only doing the front end part backend is doing some other freelancer. 
So, its hard for me to say something like to him. 

For now, I have used some other alternate plugin for the API functionality bcz that totally works fine. 

But thanks once again for your contribution and making the plugin. :) 👍 💯

**Comment by davidorbelian** [comment]
@itsharshdeep if your back end is made on ASP.NET, probably the issue is related with JsonUtility. I had the same issue and it was resolved when I replaced JsonUtility with Newtonsoft.Json one.

**Comment by jdnichollsc** [comment]
@itsharshdeep  @davidorbelian after reviewing with NodeJS as the Backend, we can't send anonymous objects, a **Serializable** class is required. Example:
```
[Serializable]
public class ServerResponse {
  public string id;
  public DateTime date;
}
[Serializable]
public class User {
  public string firstName;
  public string lastName;
}
RestClient.Post<ServerResponse>("www.myapi.com/myendpoint", new User {
  firstName = "Juan David",
  lastName = "Nicholls Cardona"
}).Then(response => {
  EditorUtility.DisplayDialog("ID: ", response.id, "Ok");
  EditorUtility.DisplayDialog("Date: ", response.date.ToString(), "Ok");
});
```

Best regards, Nicholls
