### ISSUE TITLE
Facing problem with Android

### ISSUE THREAD

**Issue by RahulChute** [proyecto26/RestClient#72]
Hi there. Thanks for a great plugin.
But currently facing a problem, I cant create Android file, apk as i install RestClient using Unity.
It shows only process is happening but nothing happens.
Pls help.
Thanks in advance.

**Comment by jdnichollsc** [comment]
@RahulChute please share your code and logs 👍

**Comment by RahulChute** [comment]
Hi Juan.The issue is solved. Actually the problem was with another plugin i.e. serializer.Thanks for your support. Keep up the good work.Regards.

Sent from Yahoo Mail on Android 
 
  On Wed, 22 May 2019 at 11:35 AM, Juan David Nicholls Cardona<notifications@github.com> wrote:   
@RahulChute please share your code and logs 👍

**Comment by jdnichollsc** [comment]
Excellent! 👍

**Comment by jdnichollsc** [comment]
@RahulChute any good feedback from the [Unity Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501) is also really appreciated! 👯‍♂
