### ISSUE TITLE
.mp4 download starts and then fails

### ISSUE THREAD

**Issue by mikson60** [proyecto26/RestClient#76]
Hi,

I am using the following code to download an .mp4 file from a remote source and save it directly to disk:

`DownloadHandlerFile dh = new DownloadHandlerFile(Application.persistentDataPath + "/123.mp4", false);
            dh.removeFileOnAbort = true;

            RestClient.Get(new RequestHelper
            {
                Uri = uri,
                Method = "GET",
                Timeout = 10,
                ContentType = "application/json",
                Retries = 3,
                RetrySecondsDelay = 2,
                EnableDebug = true,
                DownloadHandler = dh
            })
                //.Progress(progress =>
                //{
                //    Debug.Log("Current progress: " + progress);
                //})
                .Then(response =>
                {
                    Debug.Log("Video downloaded. Check folder!");

                    DirectoryInfo d = new DirectoryInfo(Application.persistentDataPath);
                    if (d != null)
                    {
                        foreach (FileInfo f in d.GetFiles())
                        {
                            Debug.Log(f.Name);
                        }
                    }
                    else
                    {
                        Debug.LogWarning("Directory not found");
                    }
                })
                .Catch(exception =>
                {
                    Debug.LogWarning(exception.Message);
                });

            Debug.Log("should be finished");`

When I start playmode in the editor then the code above is called. At first the download process starts and the video file is created at the path specified. Also, the "should be finished" debug log is called at the end. At around 7-15Mb (the file is around 150Mb and the files I need to download can take up to 2-3Gb space) the download process halts and Retry request is logged to the console. It does 3 retries, they fail (always!). After the last retry an error message "NotSupportedException: String access is not supported" at HttpBase line 66 is called. The function CreateException() is called from the "else" branch of CreateRequestAndRetry function (var err = CreateException(request)).

It should also be noted that if I uncomment the .Then() part then the debug.log(progress) is never called. Also neither the .Then() nor .Catch() are called.

If I create the request manually (without your asset) by executing the code below, the video gets downloaded without a problem:

`           DownloadHandlerFile downloadHandler = new DownloadHandlerFile(path);
            downloadHandler.removeFileOnAbort = true;`

            UnityWebRequest uwr = new UnityWebRequest(uri);
            uwr.method = UnityWebRequest.kHttpVerbGET;
            uwr.downloadHandler = downloadHandler;

            `uwr.SendWebRequest();

            int lastProgress = 0;

            while (!uwr.isDone)
            {
                int progress = (int)(uwr.downloadProgress * 100f);

                if (lastProgress != progress)
                {
                    Debug.Log("Downloaded " + progress.ToString() + "%");
                    lastProgress = progress;
                }
                yield return null;
            }

            if (uwr.isNetworkError || uwr.isHttpError)
            {
                Debug.LogError(uwr.error);
                yield break;
            }
            else
            {
                Debug.Log("Downloaded file to " + path.Replace("/", "\\"));
            }

            Debug.Log("after while");`

In this case "after while" is called after the file is actually downloaded or the download fails.

Unity: 2019.1.4f1

**Comment by jdnichollsc** [comment]
Hi Jens-Stefan, can you try with other `ContentType` because the response of the server is a video instead of a JSON file? Also, can you try with the other generic method we have `RestClient.Request`
Let me know,
Juan

**Comment by jdnichollsc** [comment]
On the other hand, `Debug.Log("should be finished");` is executed before to finish the promise and that's an expected behavior because we're using promises here. If you want to execute code after that you can use the `Finally` method https://github.com/Real-Serious-Games/C-Sharp-Promise#recent-updates

**Comment by jdnichollsc** [comment]
In the case of the progress of a **Request**, you can know that using the `RequestHelper class` directly:
- Creating the request
```
currentRequest = new RequestHelper {};
RestClient.Request(currentRequest)
.Then(response => {})
.Catch(exception => {})
.Finally(() => {});
```
- Checking the progress from your `Update` method (https://docs.unity3d.com/ScriptReference/MonoBehaviour.Update.html)
```
currentRequest.UploadProgress; //The progress by uploading data to the server
currentRequest.UploadedBytes; //The number of bytes of body data the system has uploaded
currentRequest.DownloadProgress; //The progress by downloading data from the server
currentRequest.DownloadedBytes; //The number of bytes of body data the system has downloaded
currentRequest.Abort(); //Abort the request manually
```

**Comment by mikson60** [comment]
> can you try with other `ContentType` because the response of the server is a video instead of a JSON file?

I tried it with "application/octet-stream" and "multipart/form-data" and tried to remove the ContentType assignment completely. The problem still persists.


> Also, can you try with the other generic method we have `RestClient.Request`

What would you propose exactly? I do not need to use a generic method because I am just getting the video file. I do not need to convert from json to C# object or anything else like that.

**Comment by jdnichollsc** [comment]
Sorry mate, I was a little sick, let me try this weekend and let you know 👍

**Comment by jdnichollsc** [comment]
Ok, it works with this other way:

```
var fileUrl = "https://raw.githubusercontent.com/IonDen/ion.sound/master/sounds/bell_ring.ogg";
var fileType = AudioType.OGGVORBIS;

currentRequest = new RequestHelper {
	Uri = fileUrl,
	DefaultContentType = true,
	DownloadHandler = new DownloadHandlerAudioClip(fileUrl, fileType)
}; 

RestClient.Get(currentRequest, (err, res) => {
	if (err == null){
		
		if (res.Request.downloadHandler != null) {
			AudioSource audio = GetComponent<AudioSource>();
			audio.clip = ((DownloadHandlerAudioClip)res.Request.downloadHandler).audioClip;
			audio.Play();
		} else {
			EditorUtility.DisplayDialog ("Error", "downloadHandler is empty :(", "Ok");
		}
	}
	else {
		EditorUtility.DisplayDialog ("Error", err.Message, "Ok");
	}
});
```
Let me update the README 👍
