### ISSUE TITLE
Download local image file

### ISSUE THREAD

**Issue by mikson60** [proyecto26/RestClient#77]
Hi,

I was wondering if you  could provide an example on how to load into a Texture2D variable an image from local storage. I have the path but with my code all I get is an error that is caught: "Specified cast is not valid.".

I have written this functionality without your asset like this:
`using (UnityWebRequest uwr = UnityWebRequestTexture.GetTexture(path))
            {
                yield return uwr.SendWebRequest();

                while (!uwr.isDone)
                {
                    Debug.Log("Accessing image");
                }

                if (uwr.isNetworkError || uwr.isHttpError)
                {
                    Debug.LogError(uwr.error);
                }
                else
                {
                    Debug.Log("Loaded file from " + path.Replace("/", "\\"));
                    var tex = DownloadHandlerTexture.GetContent(uwr);
                    Debug.Log(tex.name);
                }
            }`

But I would like to write this with your code. What I've tried is this:
`public static void GetLocalImage(string path, string id, Action<string, Texture2D> callback)
        {
            RestClient.Get(path).Then(response =>
            {
                var tex = DownloadHandlerTexture.GetContent(response.Request);

                if (tex == null)
                {
                    Debug.LogWarning("Could not get the texture content");
                }
                else
                {
                    callback?.Invoke(id, tex);
                }
            }).Catch(exception =>
            {
                Debug.LogWarning(exception.Message);
            });
        }`

Any help is much appreciated!

**Comment by jdnichollsc** [comment]
we have an example loading textures here https://github.com/proyecto26/RestClient#generic-request-method

**Comment by mikson60** [comment]
I tried to get the texture as was shown in the example code but I still could the "Specified cast is no valid." exception. Do I need to specify any additional arguments?

`public static void GetLocalImage(string id, string path, Action<string, string, Texture2D> callback)
        {
            Debug.Log("GET LOCAL IMAGE");

            RestClient.Get(path).Then(response =>
            {
                var texture = ((DownloadHandlerTexture) response.Request.downloadHandler).texture;
            }).Catch(exception =>
            {
                Debug.LogWarning(exception.Message);
            });
        }`

**Comment by jdnichollsc** [comment]
Do you have any url to debug or can you check the last version 2.5.7 using something like this:
```csharp
RestClient.Request(new RequestHelper { 
  Uri = "https://mysever/downloadfile",
  Method = "GET",
  DefaultContentType = false //Disable JSON content type by default
}).Then(response => {
  //Get resources via downloadHandler to have more control!
  Texture texture = ((DownloadHandlerTexture)response.Request.downloadHandler).texture;
  AudioClip audioClip = ((DownloadHandlerAudioClip)response.Request.downloadHandler).audioClip;
  AssetBundle assetBundle = ((DownloadHandlerAssetBundle)response.Request.downloadHandler).assetBundle;

  EditorUtility.DisplayDialog("Status", response.StatusCode.ToString(), "Ok");
});
```

**Comment by jdnichollsc** [comment]
Nevermind, it's related with the issue #76 and you can find an example now from the README of the project 👍
