### ISSUE TITLE
Succeeded responses on HoloLens treated as errors/exceptions

### ISSUE THREAD

**Issue by are-chris** [proyecto26/RestClient#78]
Hi folks/jdnichollsc,

we are using your REST-library for Unity3D in our hololens project. In EditorPlay-Mode everything seems to work as expected. However when deploying the same code to the hololens we have some struggles.

It seems like responses in most cases are flagged as erroneous although the return code says 200 (success). This means from your framework responses are returned as exceptions (at least in our case) and important information cannot be retrieved anymore.

I could brake it down to the "IsValidRequest" in the Extensions.cs file/class which checks all properties from the unity webrequest.

For us, I introduced a bugfix, changing your function to the following:

```
public static bool IsValidRequest(this UnityWebRequest request, RequestHelper options)
{
#if WINDOWS_UWP
if (request.isDone && request.responseCode == 200)
return true;
#endif
return request.isDone &&
!request.isNetworkError &&
(
!request.isHttpError || options.IgnoreHttpException
);
}
```

I do not know if it is only related to hololens (WINDOWS_UWP) or to the unity-editor version we are using (2017.3.1.p3), maybe you want to see [1] as well.

Cheers,
Christian from AR Experts

[1] https://issuetracker.unity3d.com/issues/networking-unitywebrequest-dot-post-returns-generic-slash-unknown-http-error

**Comment by jdnichollsc** [comment]
Hi Christian, 
This is a library, not a framework because we're using the UnityWebRequest system internally so you can check the official documentation for that issue. We can't include that code in the project because there're other valid http status codes like 202, 204, etc https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

**Comment by are-chris** [comment]
sure, sorry. I meant library, wrote it earlier.

Just wanted you to make aware of the iusse, I was not sure if this came already up. My code is only meant as sample and how we dealt with it. It is far from being valid/usable for all library users.

And thanks for the hint with the other status codes. Maybe I will integrate this into out solutions, I was not aware of this diversity of these codes up to now.

**Comment by jdnichollsc** [comment]
Thanks for reporting this issue mate, let me investigate on this too 👍

**Comment by jdnichollsc** [comment]
@Thomas-6freedom hello mate, sorry to tag you. Do you have experience with this? 😅

**Comment by jdnichollsc** [comment]
Very cool image:

![http status codes](https://user-images.githubusercontent.com/2154886/60626240-c61ae600-9daf-11e9-8030-1efa7a5674b3.jpg)

**Comment by jdnichollsc** [comment]
@are-chris any news? :)
