### ISSUE TITLE
error CS0117: 'JsonHelper' does not contain a definition for 'ArrayToJsonString'

### ISSUE THREAD

**Issue by dlevel7** [proyecto26/RestClient#82]
I get this error with unity 2019.1.8, thanks

**Comment by jdnichollsc** [comment]
Can you share your code please?

**Comment by dlevel7** [comment]
thanks for your reply, there is no code to share I get this error when I import the asset in unity :) is on JsonHelper default code.

**Comment by jdnichollsc** [comment]
Very weird because I can see that method in the code https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Helpers/JsonHelper.cs#L27

**Comment by dlevel7** [comment]
![image](https://user-images.githubusercontent.com/51931826/60676030-8115b300-9e86-11e9-898f-a0147129543e.png)
it is very weird, because the rest of the same methods seem ok, that is why I mentioned the unity version, maybe it has to do anything with that, unity 2019 uses c# 7

**Comment by dlevel7** [comment]
nvm, I had another asset using the same class...

**Comment by jdnichollsc** [comment]
the same class? haha
