### ISSUE TITLE
UIWidget (RSG.Promise)

### ISSUE THREAD

**Issue by Avatarchik** [proyecto26/RestClient#85]
Hi! How can I solve the problem?
https://github.com/UnityTech/UIWidgets/issues/214

**Comment by jdnichollsc** [comment]
Let me check this weekend because I don't know how to move the common logic we have in both projects using promises 🤔

**Comment by zhuxingwei** [comment]
The RSG.Promise library used in UIWidgets is under [UIWidgetsPackageFolder]/Runtime/promise/, simply deleting them all may work ?

**Comment by jdnichollsc** [comment]
Trying to fix the problems with the references, but it looks like UIWidgets has a modified version of RSG Library and that needs to be fixed first in order to solve this issue :)

**Comment by jdnichollsc** [comment]
So if you want to discuss this please from the other repo 👍
