### ISSUE TITLE
Get response error data

### ISSUE THREAD

**Issue by Julien-R44** [proyecto26/RestClient#86]
Sorry for opening an issue for this, but i can't found how to get the response error datas.

For instance, I'm calling my API for registering user, and when the call fails, the server return this : 
```
{
    "message": "The given data was invalid.",
    "errors": {
        "email": [
            "The email has already been taken."
        ],
        "username": [
            "The username is too long."
        ],
    }
}
```

And here the code used in Unity to call the api :
```
RestClient.Post<User>("www.localhost/api/auth/register", payload).Then(response => {
    EditorUtility.DisplayDialog("JSON", JsonUtility.ToJson(response, true), "Ok");
}).Catch(err => {
  // How can i get the response data ? 
  // err.Message only contains the statut code :/
});
```

I would like to get the errors.email or errors.username and display them in my Unity game UI.
How can I do this?

**Comment by jdnichollsc** [comment]
Check here https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Helpers/RequestException.cs
