### ISSUE TITLE
http post requests

### ISSUE THREAD

**Issue by ShaneVidYen** [proyecto26/RestClient#87]
HTTP posts seem to be having trouble as I'm able to get a success however on the server and in the unity console there is no request being sent or response being received is there a way to find out whats gone wrong with the request?

	public void Post(){
		currentRequest = new RequestHelper {
			Uri = basePath + "/vyps-curl/",
			Body = new Post {
                userid = "05-6c4a",
                apikey = "keytest",
		points = 100
			}
		};
		RestClient.Post<Post>(currentRequest)
		.Then(res => this.LogMessage("Success", JsonUtility.ToJson(res, true)))
		.Catch(err => this.LogMessage("Error", err.Message));
	}

**Comment by jdnichollsc** [comment]
Try using the `EnableDebug` property of the RequestHelper class to debug 👍

**Comment by ShaneVidYen** [comment]
Its more that I don't quite understand the documentation completely am I creating a new file or what do I need to edit? as currently I was just editing a file that is already there and changing it to have the url and body.

**Comment by jdnichollsc** [comment]
Check the demo folder of this repository and let me know 👍

**Comment by ShaneVidYen** [comment]
Doing this all in unity and Still a bit unsure so I've edited the main-script post to this I then edited the model post so it has 
key as a string
userid as a string
points as a int
where can I enable debug
I get the feeling i'm probably supposed to make a new file but I don't see anything telling me to do so or not to do so.
------------------------------------------------
	public void Post(){

		currentRequest = new RequestHelper {
			Uri = basePath + "/vypscurlbal/",
			Body = new Post {
				key = "keytest",
                userId = "05-6c4a",
                points = 100,
			}
		};
		RestClient.Post<Post>(currentRequest)
		.Then(res => this.LogMessage("Success", JsonUtility.ToJson(res, true)))
		.Catch(err => this.LogMessage("Error", err.Message));
	}

**Comment by ShaneVidYen** [comment]
Doing this all in unity and Still a bit unsure so I've edited the main-script post to this I then edited the model post so it has 
key as a string
userid as a string
points as a int
where can I enable debug
I get the feeling i'm probably supposed to make a new file but I don't see anything telling me to do so or not to do so.

**Comment by ShaneVidYen** [comment]
public void Post(){

		currentRequest = new RequestHelper {
			Uri = basePath + "/vypscurlbal/",
			Body = new Post {
				key = "keytest",
                userId = "05-6c4a",
                points = 100,
			}
		};
		RestClient.Post<Post>(currentRequest)
		.Then(res => this.LogMessage("Success", JsonUtility.ToJson(res, true)))
		.Catch(err => this.LogMessage("Error", err.Message));
	}

**Comment by jdnichollsc** [comment]
Check the README of the project https://github.com/proyecto26/RestClient#generic-request-method:
```
currentRequest = new RequestHelper {
   ...,
   EnableDebug = true
};
```

**Comment by ShaneVidYen** [comment]
I've tried that It except unity says it causes a compiler error and thats the only change I make when I try that.
public void Post(){

		currentRequest = new RequestHelper {
			Uri = basePath + "/vypscurlbal/",
			Body = new Post {
				key = "c7fd2da37e8f5cc116670710e93f4",
                userId = "05-6c4a",
                points = 100
			}
             EnableDebug = true,
        };
		RestClient.Post<Post>(currentRequest)
		.Then(res => this.LogMessage("Success", JsonUtility.ToJson(res, true)))
		.Catch(err => this.LogMessage("Error", err.Message));
	}

**Comment by ShaneVidYen** [comment]
Is there a method to send this post request without using json

**Comment by jdnichollsc** [comment]
Using the Generic Method 👍

**Comment by ShaneVidYen** [comment]
yes but like where am I putting this generic method in the mainscript? a separate file I'm a bit new to unity and all this

**Comment by jdnichollsc** [comment]
yeah, you need to study a little to understand the basic stuff with Unity + C# 👍
