### ISSUE TITLE
Possible to omit eTag header?

### ISSUE THREAD

**Issue by jinxology** [proyecto26/RestClient#89]
Hey guys, love the Unity asset, thank you for making such a great free resource! 

I'm curious if I can omit headers. I'm sending a GET request to https://timezonedb.com/api to retrieve current UTC time. Initially, the CORS was complaining that I wasn't allowed to send the Content-Type header. I found that I could omit that by setting defaultContentType to false. Now it's complaining about eTag:

**Refused to get unsafe header "ETag"**

Is there a way to see all the request headers being sent, and also to omit particular headers? When I create a RequestHelper, it looks like the Headers list is empty, guessing headers gets added when I actually send the request?

**Comment by jdnichollsc** [comment]
Maybe the **UnityWebRequest** system is adding that header by default?
