### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by hoseininafise** [proyecto26/RestClient#9]
hi
what is this error at the start?after click a button

MissingMethodException: Method not found: 'UnityEngine.Networking.UnityWebRequest.set_timeout'.
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Proyecto26.StaticCoroutine:StartCoroutine(IEnumerator)
Proyecto26.RestClient:GetArray(RequestHelper, Action`2)
Proyecto26.RestClient:GetArray(RequestHelper)
MainScript:Get() (at Assets/MainScript.cs:18)
UnityEngine.EventSystems.EventSystem:Update()
![Uploading error.jpg…]()

tanx in advance to ur attention

**Comment by jdnichollsc** [comment]
@hoseininafise What version of Unity are you using? I can't see your image
