### ISSUE TITLE
4xx Retry?

### ISSUE THREAD

**Issue by CannibalVox** [proyecto26/RestClient#94]
The RestClient seems to issue retries even on 4xx errors, which are normally not retried because they indicate a problem on the client's end.  There doesn't even seem to be any way to decide whether to continue to retry based on the error sent to the RetryCallback.  I really don't like hanging through the retry durations when there is a problem with player input.

**Comment by jdnichollsc** [comment]
Try using `IgnoreHttpException = true,` with the options of the RequestHelper and let me know 👍 

On the other hand you can call `currentRequest.Abort();` too :)
