### ISSUE TITLE
Get array out of Firebase with unique IDS

### ISSUE THREAD

**Issue by sanderyt** [proyecto26/RestClient#96]
Dear Proyecto26,

I have been on this for days and I can't seem to figure it out. With POST I am able to post a data entry, which is given an unique ID (something like -LnS6oOwg14OKdYG1aVN). As you can see below, I have in Firebase a list of "buildings" with an unique ID.

![array_with_unique_ids](https://user-images.githubusercontent.com/52009732/63941958-04a9e580-ca6d-11e9-9257-26e1cbe87ae9.jpg)

I am trying to get this array into Unity, with GetArray<>. But this only works when the unique ids are 0,1,2,3 etc... Could someone help me to get an array into Unity with Firebase, with unique IDS?

Thanks a lot!

**Comment by jdnichollsc** [comment]
**GetArray** works when the response is an Array, **Firebase** returns the data as an **object** instead, so you need to use **Get** method with Firebase and parse the response, example: https://gist.github.com/rotolonico/8473903b1f4a77ff577dff43f303c534#file-databasehandler-cs

More details here: https://medium.com/@rotolonico/firebase-database-in-unity-with-rest-api-42f2cf6a2bbf
