### ISSUE TITLE
How to write data into array ?

### ISSUE THREAD

**Issue by muafakul** [proyecto26/RestClient#99]
help meh i want to write data into https://jsonplaceholder.typicode.com/posts ,,give me example please , i use firebase to make the json

**Comment by jdnichollsc** [comment]
You can send an array using the Body of a POST request, check the README of the project 👍

**Comment by muafakul** [comment]
i can't do it my self maybe i m too stu***d ,,, i m using firebase to make
json , i do it my self , ifollowing this tutorial
https://www.youtube.com/watch?v=Fz0Sl4tW5O0 ,,, still can't

Pada tanggal Rab, 25 Sep 2019 pukul 04.56 Juan David Nicholls Cardona <
notifications@github.com> menulis:

**Comment by muafakul** [comment]
for example i want to add username and score , one by one to array ,,  i dont know how to do it :'(

**Comment by jdnichollsc** [comment]
Please share your code from a gist to be able to help you https://gist.github.com/ 👍

**Comment by muafakul** [comment]
https://gist.github.com/muafakul/15e2c0f962ef61f15ced69e438b44aa3


the result is 
![image](https://user-images.githubusercontent.com/13078369/65570061-14dcb400-df8a-11e9-92fd-0e72d4e7c615.png)

what i want is somethink like this 

{ 
   "alib":[ 
      { 
         "judul":"blablabla",
         "code":"skrtskrtt"
      },
      { 
         "judul":"blablabla",
         "code":"skrtskrtt"
      }
   ]
}

**Comment by muafakul** [comment]
i still waiting

**Comment by jdnichollsc** [comment]
You can't use arrays in Firebase as I know... but you can try this if you want:
`RestClient.Put ("https://stickman-pubg.firebaseio.com/" + playerName + "/0.json", user);`
`RestClient.Put ("https://stickman-pubg.firebaseio.com/" + playerName + "/1.json", user);`
`RestClient.Put ("https://stickman-pubg.firebaseio.com/" + playerName + "/2.json", user);`

Check the official documentation of Firebase instead of this repository 👍

**Comment by muafakul** [comment]
how if i put data into a list ?

**Comment by muafakul** [comment]
yes ,, what i want is write data into a list ,, ,,i almost succest !

**Comment by muafakul** [comment]
### what i doing so far

using System.Collections;
using System.Collections.Generic;
using Proyecto26;
using UnityEngine;
using UnityEngine.UI;

public class PlayerScores : MonoBehaviour {
    public Text scoreText;
    public InputField nameText;
    public InputField codeText;

    QuestionList ql;

    private System.Random random = new System.Random ();
    List<User> userlist = new List<User> ();
    public List<Questions> questionlist = new List<Questions> ();
    User user = new User ();

    public static int playerScore;
    public static string playerName;

    // Start is called before the first frame update
    private void Start () {
        playerScore = random.Next (0, 101);
        scoreText.text = "Score: " + playerScore;
    }

    //    List<Questions> questionlist = new List<Questions> ();

    // var ql = new QuestionList ();
    // ql.list = questionlist;

    public void OnSubmit () {
        //playerName = nameText.text;
        PostToDatabase ();

    
    

    }

    public void OnGetScore () {
        RetrieveFromDatabase ();
    }

    private void UpdateScore () {
        scoreText.text = "Score: " + user.userScore;

    }

    public void PostToDatabase () {


        List<Questions> questionlist = new List<Questions> ();

        questionlist.Add (new Questions () {
            name = nameText.text,
                code = codeText.text,

        });

        ql = new QuestionList ();
        ql.list = questionlist;

        RestClient.Put ("https://nikah-all-anime.firebaseio.com/" + ".json", ql).Then (response => {

        });
    }

    private void RetrieveFromDatabase () {
        RestClient.Get<User> ("https://nikah-all-anime.firebaseio.com/" + nameText.text + ".json").Then (response => {
            user = response;
            UpdateScore ();
        });
    }

}

**Comment by muafakul** [comment]
the result is 
![image](https://user-images.githubusercontent.com/13078369/65870371-4f898680-e3a6-11e9-9a33-6ef9f0c1e4cc.png)


what i want is 

when i put new code and new name ,,it should make new list imean at the 1 then 2 ,,,,
what i did so far is just modify the list at 0
